maxishell: /github/workspace/src/parser/AST.c File Reference
AST.c File Reference
#include "tokens.h"
Functions
t_ast * manage_redirs (t_token **tokens, t_ms_data *data)
t_ast * create_redir_node (t_token *token)
int is_redir_node (t_token *tokens)
t_ast * new_ast_node (void)
void set_command_args (t_ast *command_node, t_token **tokens, int arg_count)
Function Documentation
create_redir_node()
t_ast * create_redir_node (t_token * token)
Definition at line 62 of file AST.c.
{
    t_ast           *node;
    node = new_ast_node();
    node->type = token->type;
    node->args = malloc(sizeof(char *) * 2);
    if (!node->args)
    {
        free(node);
        return (NULL);
    }
    node->args[0] = ft_strdup(token->data);
    node->args[1] = NULL;
    return (node);
}
References s_ast::args, s_token::data, ft_strdup(), new_ast_node(), s_token::type, and s_ast::type.
Referenced by manage_redirs().
is_redir_node()
int is_redir_node (t_token * tokens)
Definition at line 79 of file AST.c.
{
    if (tokens->type == REDIR_IN
        || tokens->type == REDIR_OUT
        || tokens->type == REDIR_APPEND
        || tokens->type == REDIR_HEREDOC)
        return (1);
    return (0);
}
References REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, REDIR_OUT, and s_token::type.
Referenced by manage_redirs().
manage_redirs()
t_ast * manage_redirs (t_token ** tokens, t_ms_data * data)
Definition at line 20 of file AST.c.
{
    t_ast       *command_node;
    t_ast       *redirect_node;
    t_token     *current_token;
    if (!tokens || !*tokens)
        return (NULL);
    command_node = manage_commands(tokens, data);
    current_token = *tokens;
    while (current_token && is_redir_node(current_token))
    {
        redirect_node = create_redir_node(current_token);
        redirect_node->left = command_node;
        *tokens = current_token->next;
        if (*tokens)
        {
            redirect_node->right = create_redir_node(*tokens);
            *tokens = (*tokens)->next;
        }
        else
            redirect_node->right = NULL;
        command_node = redirect_node;
        current_token = *tokens;
    }
    return (command_node);
}
References create_redir_node(), is_redir_node(), s_ast::left, manage_commands(), s_token::next, and s_ast::right.
Referenced by create_pipe_node(), and manage_pipe().
new_ast_node()
t_ast * new_ast_node (void)
Definition at line 89 of file AST.c.
{
    t_ast       *node;
    node = malloc(sizeof(t_ast));
    if (!node)
        return (NULL);
    node->type = NONE;
    node->args = NULL;
    node->left = NULL;
    node->right = NULL;
    return (node);
}
References s_ast::args, s_ast::left, NONE, s_ast::right, and s_ast::type.
Referenced by create_pipe_node(), create_redir_node(), and manage_commands().
set_command_args()
void set_command_args (t_ast * command_node, t_token ** tokens, int arg_count)
Definition at line 48 of file AST.c.
{
    int i;
    i = 0;
    while (i < arg_count)
    {
        command_node->args[i] = ft_strdup((*tokens)->data);
        *tokens = (*tokens)->next;
        i++;
    }
    command_node->args[arg_count] = NULL;
}
References s_ast::args, ft_strdup(), and s_token::next.
Referenced by manage_commands().