maxishell: /github/workspace/src/parser/AST_utils.c File Reference
AST_utils.c File Reference
#include "tokens.h"
#include "shell.h"
Functions
t_ast * parse_tokens (t_token **tokens, t_ms_data *data)
t_ast * create_pipe_node (t_token *next_token, t_token **tokens, t_ms_data *data, t_token *tmp)
t_ast * manage_pipe (t_token **tokens, t_ms_data *data)
t_ast * manage_commands (t_token **tokens, t_ms_data *data)
int cmd_arg_len (t_token *current)
Function Documentation
cmd_arg_len()
int cmd_arg_len (t_token * current)
Definition at line 88 of file AST_utils.c.
{
    int i;
    i = 0;
    while (current && current->type == PHRASE)
    {
        i++;
        current = current->next;
    }
    return (i);
}
References s_token::next, PHRASE, and s_token::type.
Referenced by manage_commands().
create_pipe_node()
t_ast * create_pipe_node (t_token * next_token, t_token ** tokens, t_ms_data * data, t_token * tmp)
Definition at line 30 of file AST_utils.c.
{
    t_ast   *pipe_node;
    pipe_node = new_ast_node();
    if (!pipe_node)
        return (NULL);
    pipe_node->type = next_token->type;
    pipe_node->args = malloc(sizeof(char *) * 2);
    if (!pipe_node->args)
    {
        free(pipe_node);
        return (NULL);
    }
    pipe_node->args[0] = ft_strdup(next_token->data);
    pipe_node->args[1] = NULL;
    pipe_node->left = manage_redirs(&tmp, data);
    *tokens = next_token->next;
    if (next_token->next)
        pipe_node->right = manage_pipe(tokens, data);
    else
        pipe_node->right = NULL;
    return (pipe_node);
}
References s_ast::args, s_token::data, ft_strdup(), s_ast::left, manage_pipe(), manage_redirs(), new_ast_node(), s_token::next, s_ast::right, s_token::type, and s_ast::type.
Referenced by manage_pipe().
manage_commands()
t_ast * manage_commands (t_token ** tokens, t_ms_data * data)
Definition at line 72 of file AST_utils.c.
{
    t_ast       *command_node;
    int         cmd_arg_count;
    command_node = new_ast_node();
    command_node->type = PHRASE;
    cmd_arg_count = cmd_arg_len(*tokens);
    command_node->args = malloc(sizeof(char *) * (cmd_arg_count + 1));
    if (!command_node->args)
        return (NULL);
    set_command_args(command_node, tokens, cmd_arg_count);
    post_process_command_args(command_node, cmd_arg_count, data);
    return (command_node);
}
References s_ast::args, cmd_arg_len(), new_ast_node(), PHRASE, post_process_command_args(), set_command_args(), and s_ast::type.
Referenced by manage_redirs().
manage_pipe()
t_ast * manage_pipe (t_token ** tokens, t_ms_data * data)
Definition at line 56 of file AST_utils.c.
{
    t_token *tmp;
    t_token *next_token;
    tmp = *tokens;
    while (*tokens && (*tokens)->next)
    {
        next_token = (*tokens)->next;
        if (next_token->type == PIPE)
            return (create_pipe_node(next_token, tokens, data, tmp));
        *tokens = next_token;
    }
    return (manage_redirs(&tmp, data));
}
References create_pipe_node(), manage_redirs(), s_token::next, PIPE, and s_token::type.
Referenced by create_pipe_node(), and parse_tokens().
parse_tokens()
t_ast * parse_tokens (t_token ** tokens, t_ms_data * data)
Definition at line 23 of file AST_utils.c.
{
    if (!tokens || !*tokens)
        return (NULL);
    return (manage_pipe(tokens, data));
}
References manage_pipe().
Referenced by main_loop().