maxishell: /github/workspace/src/builtins/env.c File Reference
env.c File Reference
#include "shell.h"
#include "env.h"
#include "libft.h"
#include <stdlib.h>
#include <stdio.h>
#include "exit_status.h"
Functions
void print_env_stack (t_env *envp)
int builtin_env (t_ms_data *data)
Function Documentation
builtin_env()
int builtin_env (t_ms_data * data)
Definition at line 35 of file env.c.
{
    ft_printf("\nbuiltin_env\n");
    if (ft_strcmp(data->args[0], "env") == 0 && data->args[1] == NULL)
        print_env_stack(data->envp);
    else
    {
        ft_putstr_fd("env: '", STDERR_FILENO);
        ft_putstr_fd(data->args[1], STDERR_FILENO);
        ft_putstr_fd("': No such file or directory\n", STDERR_FILENO);
        set_exit_status(&data->exit_status, IS_DIRECTORY);
        set_shell_var(&data->shell_variables, "?", ft_itoa(data->exit_status));
        return (IS_DIRECTORY);
    }
    return (EXIT_SUCCESS);
}
References s_ms_data::args, s_ms_data::envp, s_ms_data::exit_status, EXIT_SUCCESS, ft_itoa(), ft_printf(), ft_putstr_fd(), ft_strcmp(), IS_DIRECTORY, print_env_stack(), set_exit_status(), set_shell_var(), and s_ms_data::shell_variables.
Referenced by execute().
print_env_stack()
void print_env_stack (t_env * envp)
Definition at line 23 of file env.c.
{
    t_env   *curr_node;
    curr_node = envp;
    while (curr_node)
    {
        ft_printf("%s=%s\n", curr_node->key, curr_node->value);
        curr_node = curr_node->next;
    }
}
References ft_printf(), s_env::key, s_env::next, and s_env::value.
Referenced by builtin_env().