maxishell: /github/workspace/src/builtins/builtins_utils.c File Reference
builtins_utils.c File Reference
#include "shell.h"
#include "libft.h"
#include <stdlib.h>
#include <stdio.h>
#include "env.h"
#include "exit_status.h"
#include "tokens.h"
#include "signals.h"
#include "builtins.h"
Functions
void free_signal_context (void)
void clear_history_file (void)
Function Documentation
clear_history_file()
void clear_history_file (void)
Definition at line 31 of file builtins_utils.c.
{
    remove(HISTORY_PATH);
}
References HISTORY_PATH.
Referenced by cleanup_exit_resources(), main(), and main_loop().
free_signal_context()
void free_signal_context (void)
Definition at line 23 of file builtins_utils.c.
{
    t_signal_context    *context;
    context = get_context(NULL);
    free(context);
}
References get_context().
Referenced by cleanup_exit_resources().