maxishell: /github/workspace/inc/builtins.h File Reference
builtins.h File Reference
#include "shell.h"
Functions
int builtin_cd (t_ms_data *data)
int builtin_echo (t_ms_data *data)
int builtin_env (t_ms_data *data)
int builtin_exit (t_ms_data *data)
int builtin_export (t_ms_data *data)
int builtin_pwd (t_ms_data *data)
int builtin_unset (t_ms_data *data)
void free_signal_context (void)
Function Documentation
builtin_cd()
int builtin_cd (t_ms_data * data)
Definition at line 28 of file cd.c.
{
    char    *target_dir;
    char    *home_dir;
    char    *error_message;
    char    cwd[4096];
    home_dir = get_env(data->envp, "HOME");
    target_dir = (char *)data->args[1];
    if (!target_dir)
        target_dir = home_dir;
    if (chdir(target_dir) == -1)
    {
        error_message = ft_strjoin("cd: ", target_dir);
        if (errno == EACCES)
            exit_status_handler(data, PERMISSION_DENIED, error_message);
        if (errno == ENOENT)
            exit_status_handler(data, IS_DIRECTORY, error_message);
        free(error_message);
        return (EXIT_FAILURE);
    }
    set_env(&data->envp, "OLDPWD", get_env(data->envp, "PWD"));
    if (getcwd(cwd, sizeof(cwd)) != NULL)
        set_env(&data->envp, "PWD", cwd);
    return (EXIT_SUCCESS);
}
References s_ms_data::args, s_ms_data::envp, EXIT_FAILURE, exit_status_handler(), EXIT_SUCCESS, ft_strjoin(), get_env(), IS_DIRECTORY, PERMISSION_DENIED, and set_env().
Referenced by execute().
builtin_echo()
int builtin_echo (t_ms_data * data)
Definition at line 23 of file echo.c.
{
    int     newline;
    int     i;
    char    **args;
    newline = 1;
    i = 1;
    args = data->args;
    if (!data || !data->args || !data->args[0])
        return (EXIT_FAILURE);
    handle_std_io(&data->std_out, STDOUT_FILENO);
    if (args[1] && ft_strcmp(args[1], "-n") == 0)
    {
        newline = 0;
        i = 2;
    }
    while (args[i])
    {
        ft_putstr_fd(args[i], STDOUT_FILENO);
        if (args[i + 1])
            ft_putstr_fd(" ", STDOUT_FILENO);
        i++;
    }
    if (newline)
        ft_putchar_fd('\n', STDOUT_FILENO);
    return (EXIT_SUCCESS);
}
References s_ms_data::args, EXIT_FAILURE, EXIT_SUCCESS, ft_putchar_fd(), ft_putstr_fd(), ft_strcmp(), handle_std_io(), and s_ms_data::std_out.
Referenced by execute().
builtin_env()
int builtin_env (t_ms_data * data)
Definition at line 35 of file env.c.
{
    if (ft_strcmp(data->args[0], "env") == 0 && data->args[1] == NULL)
        print_env_stack(data->envp);
    else
    {
        ft_putstr_fd("env: '", STDERR_FILENO);
        ft_putstr_fd(data->args[1], STDERR_FILENO);
        ft_putstr_fd("': No such file or directory\n", STDERR_FILENO);
        set_exit_status(&data->exit_status, IS_DIRECTORY);
        set_shell_var(&data->shell_variables, "?", ft_itoa(data->exit_status));
        return (IS_DIRECTORY);
    }
    return (EXIT_SUCCESS);
}
References s_ms_data::args, s_ms_data::envp, s_ms_data::exit_status, EXIT_SUCCESS, ft_itoa(), ft_putstr_fd(), ft_strcmp(), IS_DIRECTORY, print_env_stack(), set_exit_status(), set_shell_var(), and s_ms_data::shell_variables.
Referenced by execute().
builtin_exit()
int builtin_exit (t_ms_data * data)
Definition at line 61 of file exit.c.
{
    int number;
    number = 0;
    if (!data->args || !data->args[1])
    {
        ft_free_2d_arr(data->args);
        data->args = NULL;
        ft_putendl_fd("exit", STDOUT_FILENO);
        handle_exit(data, 0);
        return (0);
    }
    if (ft_isnumber(data->args[1]) == 0)
        handle_numeric_error(data, data->args[1]);
    else if (data->args[2])
        handle_too_many_args_error(data);
    else
    {
        number = ft_atoi(data->args[1]);
        ft_free_2d_arr(data->args);
        data->args = NULL;
        handle_exit(data, number);
    }
    return (EXIT_SUCCESS);
}
References s_ms_data::args, EXIT_SUCCESS, ft_atoi(), ft_free_2d_arr(), ft_isnumber(), ft_putendl_fd(), handle_exit(), handle_numeric_error(), and handle_too_many_args_error().
Referenced by execute(), and main_loop().
builtin_export()
int builtin_export (t_ms_data * data)
Definition at line 30 of file export.c.
{
    if (data->args == NULL || data->args[1] == NULL)
    {
        print_env(data->envp);
        return (EXIT_SUCCESS);
    }
    if (ft_strcmp(data->args[1], "-p") != 0 && data->args[1][0] == '-')
    {
        exit_status_handler(data, INVALID_OPTION, \
                ft_strjoin("export: ", data->args[1]));
        ft_putendl_fd("export: usage: export [-p]" \
                "[name[=value] ...] or export -p", STDERR_FILENO);
        return (INVALID_OPTION);
    }
    else if (ft_strcmp(data->args[1], "-p") == 0)
    {
        print_env(data->envp);
        return (EXIT_SUCCESS);
    }
    add_env(data);
    return (EXIT_SUCCESS);
}
References add_env(), s_ms_data::args, s_ms_data::envp, exit_status_handler(), EXIT_SUCCESS, ft_putendl_fd(), ft_strcmp(), ft_strjoin(), INVALID_OPTION, and print_env().
Referenced by execute().
builtin_pwd()
int builtin_pwd (t_ms_data * data)
Definition at line 24 of file pwd.c.
{
    char    cwd[4096];
    (void)data;
    if (getcwd(cwd, sizeof(cwd)) != NULL)
        ft_putendl_fd(cwd, STDOUT_FILENO);
    return (EXIT_SUCCESS);
}
References EXIT_SUCCESS, and ft_putendl_fd().
Referenced by execute().
builtin_unset()
int builtin_unset (t_ms_data * data)
Definition at line 29 of file unset.c.
{
    int     i;
    char    *key;
    i = 0;
    while (data->args[++i])
    {
        key = data->args[i];
        if (unset_env(&data->envp, key) == -1)
        {
            return (EXIT_SUCCESS);
        }
    }
    return (EXIT_SUCCESS);
}
References s_ms_data::args, s_ms_data::envp, EXIT_SUCCESS, and unset_env().
Referenced by execute().
free_signal_context()
void free_signal_context (void)
Definition at line 23 of file builtins_utils.c.
{
    t_signal_context    *context;
    context = get_context(NULL);
    free(context);
}
References get_context().
Referenced by cleanup_exit_resources().