maxishell: /github/workspace/src/builtins/cd.c File Reference
cd.c File Reference
#include <stdio.h>
#include "libft.h"
#include "shell.h"
#include "env.h"
#include "execute.h"
#include "exit_status.h"
Functions
int builtin_cd (t_ms_data *data)
Function Documentation
builtin_cd()
int builtin_cd (t_ms_data * data)
Definition at line 28 of file cd.c.
{
    char    *target_dir;
    char    *home_dir;
    char    *error_message;
    char    cwd[4096];
    home_dir = get_env(data->envp, "HOME");
    target_dir = (char *)data->args[1];
    if (!target_dir)
        target_dir = home_dir;
    if (chdir(target_dir) == -1)
    {
        error_message = ft_strjoin("cd: ", target_dir);
        if (errno == EACCES)
            exit_status_handler(data, PERMISSION_DENIED, error_message);
        if (errno == ENOENT)
            exit_status_handler(data, IS_DIRECTORY, error_message);
        free(error_message);
        return (EXIT_FAILURE);
    }
    set_env(&data->envp, "OLDPWD", get_env(data->envp, "PWD"));
    if (getcwd(cwd, sizeof(cwd)) != NULL)
        set_env(&data->envp, "PWD", cwd);
    return (EXIT_SUCCESS);
}
References s_ms_data::args, s_ms_data::envp, EXIT_FAILURE, exit_status_handler(), EXIT_SUCCESS, ft_strjoin(), get_env(), IS_DIRECTORY, PERMISSION_DENIED, and set_env().
Referenced by execute().