maxishell: /github/workspace/src/utils/clean.c File Reference
clean.c File Reference
#include "tokens.h"
#include "env.h"
#include "exit_status.h"
Functions
void free_args (char **args)
void free_env_list (t_env *env)
void free_ms_data (t_ms_data *data)
void loop_cleanup (t_loop_data *loop_data, t_token *tokens_head)
void free_ast (t_ast *node)
void free_all_tokens (t_token *tokens)
Function Documentation
free_all_tokens()
void free_all_tokens (t_token * tokens)
Definition at line 17 of file clean_utils.c.
{
    t_token *temp;
    while (tokens)
    {
        temp = tokens;
        tokens = tokens->next;
        if (temp)
        {
            if (temp->data)
            {
                free(temp->data);
                temp->data = NULL;
            }
        }
        free(temp);
        temp = NULL;
    }
}
Referenced by loop_cleanup().
free_args()
void free_args (char ** args)
Definition at line 24 of file clean.c.
{
    int i;
    i = 0;
    if (args)
    {
        while (args[i] != NULL)
            free(args[i++]);
        free(args);
    }
}
free_ast()
void free_ast (t_ast * node)
Definition at line 74 of file clean.c.
{
    int             i;
    i = 0;
    if (!node)
        return ;
    if (node->args)
    {
        while (node->args && node->args[i])
        {
            free(node->args[i]);
            i++;
        }
        free(node->args);
    }
    free_ast(node->left);
    free_ast(node->right);
    free(node);
}
References s_ast::args, free_ast(), s_ast::left, and s_ast::right.
Referenced by free_ast(), and loop_cleanup().
free_env_list()
void free_env_list (t_env * env)
Definition at line 37 of file clean.c.
{
    t_env   *temp;
    while (env)
    {
        temp = env;
        env = env->next;
        free(env->key);
        free(env->value);
        free(temp);
    }
}
References s_env::key, s_env::next, and s_env::value.
free_ms_data()
void free_ms_data (t_ms_data * data)
Definition at line 51 of file clean.c.
{
    if (data)
    {
        free_shell_var_list(data->envp);
        free_shell_var_list(data->shell_variables);
        free(data->current_dir);
        if (data->std_in >= 0)
            close(data->std_in);
        if (data->std_out >= 0)
            close(data->std_out);
        if (data->std_err >= 0)
            close(data->std_err);
    }
}
References s_ms_data::current_dir, s_ms_data::envp, free_shell_var_list(), s_ms_data::shell_variables, s_ms_data::std_err, s_ms_data::std_in, and s_ms_data::std_out.
Referenced by cleanup_exit_resources(), and main().
loop_cleanup()
void loop_cleanup (t_loop_data * loop_data, t_token * tokens_head)
Definition at line 67 of file clean.c.
{
    free(loop_data->trimmed_input);
    free_all_tokens(tokens_head);
    free_ast(loop_data->tree);
}
References free_all_tokens(), free_ast(), s_loop_data::tree, and s_loop_data::trimmed_input.
Referenced by process_ast_and_io(), and status_handler().