maxishell: /github/workspace/src/builtins/echo.c File Reference
echo.c File Reference
#include "libft.h"
#include "shell.h"
#include "exit_status.h"
#include "execute.h"
Functions
int builtin_echo (t_ms_data *data)
Function Documentation
builtin_echo()
int builtin_echo (t_ms_data * data)
Definition at line 23 of file echo.c.
{
    int     newline;
    int     i;
    char    **args;
    newline = 1;
    i = 1;
    args = data->args;
    if (!data || !data->args || !data->args[0])
        return (EXIT_FAILURE);
    handle_std_io(&data->std_out, STDOUT_FILENO);
    if (args[1] && ft_strcmp(args[1], "-n") == 0)
    {
        newline = 0;
        i = 2;
    }
    while (args[i])
    {
        ft_putstr_fd(args[i], STDOUT_FILENO);
        if (args[i + 1])
            ft_putstr_fd(" ", STDOUT_FILENO);
        i++;
    }
    if (newline)
        ft_putchar_fd('\n', STDOUT_FILENO);
    return (EXIT_SUCCESS);
}
References s_ms_data::args, EXIT_FAILURE, EXIT_SUCCESS, ft_putchar_fd(), ft_putstr_fd(), ft_strcmp(), handle_std_io(), and s_ms_data::std_out.
Referenced by execute().