maxishell: /github/workspace/inc/env.h File Reference
env.h File Reference
Classes
struct s_env
Typedefs
typedef struct s_env t_env
Functions
void init_env (t_env **data_envp, char **envp)
void add_env_node (t_env **data_envp, char *line)
char * get_env (t_env *envp, const char *key)
void set_env (t_env **env, const char *key, const char *value)
int unset_env (t_env **env, const char *name)
char ** env_to_array (t_env *envp)
char * ft_strcdup (const char *s, int c)
void free_env (t_env *envp)
void print_t_env (t_env *tokens)
int handle_add_set_shell_variable (t_env **shell_var, char *line)
void set_shell_var (t_env **shell_var, const char *key, const char *value)
void add_shell_var_node (t_env **shell_var, const char *line)
char * get_shell_variable (t_env *shell_var, const char *key)
Typedef Documentation
t_env
typedef struct s_env t_env
Function Documentation
add_env_node()
void add_env_node (t_env ** data_envp, char * line)
Definition at line 33 of file env.c.
{
    t_env   *new_node;
    t_env   *curr_node;
    char    *key;
    char    *value;
    new_node = (t_env *)malloc(sizeof(t_env) + 1);
    if (!new_node)
        return ;
    key = ft_strcdup(line, '=');
    value = ft_strchr(line, '=') + 1;
    new_node->key = ft_strdup(key);
    new_node->value = ft_strdup(value);
    free(key);
    new_node->next = NULL;
    if (*data_envp == NULL)
    {
        *data_envp = new_node;
        return ;
    }
    curr_node = *data_envp;
    while (curr_node->next != NULL)
        curr_node = curr_node->next;
    curr_node->next = new_node;
}
References ft_strcdup(), ft_strchr(), ft_strdup(), s_env::key, s_env::next, and s_env::value.
Referenced by init_env().
add_shell_var_node()
void add_shell_var_node (t_env ** shell_var, const char * line)
Definition at line 13 of file shell_variables_utils.c.
{
    t_env   *new_node;
    t_env   *curr_node;
    char    *key;
    char    *value;
    new_node = (t_env *)malloc(sizeof(t_env));
    if (!new_node)
        return ;
    key = ft_strcdup(line, '=');
    value = ft_strchr(line, '=') + 1;
    new_node->key = ft_strdup(key);
    new_node->value = ft_strdup(value);
    free(key);
    new_node->next = NULL;
    if (*shell_var == NULL)
    {
        *shell_var = new_node;
        return ;
    }
    curr_node = *shell_var;
    while (curr_node->next != NULL)
        curr_node = curr_node->next;
    curr_node->next = new_node;
}
References ft_strcdup(), ft_strchr(), ft_strdup(), s_env::key, s_env::next, and s_env::value.
Referenced by handle_add_set_shell_variable().
env_to_array()
char ** env_to_array (t_env * envp)
Definition at line 23 of file utils.c.
{
    t_env   *curr_node;
    char    **env_array;
    int     i;
    char    *temp;
    i = 0;
    curr_node = envp;
    while (curr_node)
    {
        i++;
        curr_node = curr_node->next;
    }
    env_array = (char **)malloc(sizeof(char *) * (i + 1));
    i = 0;
    curr_node = envp;
    while (curr_node)
    {
        temp = ft_strjoin(curr_node->key, "=");
        env_array[i] = ft_strjoin(temp, curr_node->value);
        free(temp);
        i++;
        curr_node = curr_node->next;
    }
    env_array[i] = NULL;
    return (env_array);
}
References ft_strjoin(), s_env::key, s_env::next, and s_env::value.
Referenced by new_process(), and test_init_env().
free_env()
void free_env (t_env * envp)
Definition at line 88 of file utils.c.
{
    t_env   *curr_node;
    t_env   *next_node;
    curr_node = envp;
    while (curr_node)
    {
        next_node = curr_node->next;
        free(curr_node->key);
        free(curr_node->value);
        free(curr_node);
        curr_node = next_node;
    }
}
References s_env::key, s_env::next, and s_env::value.
Referenced by env_tests().
ft_strcdup()
char * ft_strcdup (const char * s, int c)
The function ft_strcdup duplicates a string s until the character c is encountered or the end of the string is reached.
Parameters
s The s parameter in the ft_strcdup function is a pointer to a constant character array (string) from which a new string will be duplicated up to the specified character c.
c The parameter c in the ft_strcdup function represents the character that will be used as a delimiter. The function will copy the characters from the input string s until it encounters this delimiter character c, or until the end of the string if the delimiter is not found
Returns
The function ft_strcdup returns a newly allocated string that is a duplicate of the input string s up to the first occurrence of the character c. If memory allocation fails, it returns NULL.
Definition at line 67 of file utils.c.
{
    char    *str;
    size_t  i;
    i = 0;
    while (s[i] && s[i] != c)
        i++;
    str = (char *)malloc(sizeof(char) * (i + 1));
    if (!str)
        return (NULL);
    i = 0;
    while (s[i] && s[i] != c)
    {
        str[i] = s[i];
        i++;
    }
    str[i] = '\0';
    return (str);
}
Referenced by add_env(), add_env_node(), add_shell_var_node(), and handle_add_set_shell_variable().
get_env()
char * get_env (t_env * envp, const char * key)
Definition at line 60 of file env.c.
{
    t_env   *curr_node;
    curr_node = envp;
    while (curr_node)
    {
        if (ft_strcmp(curr_node->key, key) == 0)
            return (curr_node->value);
        curr_node = curr_node->next;
    }
    return (NULL);
}
References ft_strcmp(), s_env::key, s_env::next, and s_env::value.
Referenced by builtin_cd(), expand_env_var(), ft_find_path(), generate_prompt_string(), handle_get_shell_variable(), test_get_env(), test_set_env(), and test_unset_env().
get_shell_variable()
char * get_shell_variable (t_env * shell_var, const char * key)
Definition at line 64 of file shell_variables_utils.c.
{
    t_env   *curr_node;
    curr_node = shell_var;
    while (curr_node)
    {
        if (ft_strcmp(curr_node->key, key) == 0)
            return (curr_node->value);
        curr_node = curr_node->next;
    }
    return (NULL);
}
References ft_strcmp(), s_env::key, s_env::next, and s_env::value.
handle_add_set_shell_variable()
int handle_add_set_shell_variable (t_env ** shell_var, char * line)
Definition at line 11 of file shell_variables.c.
{
    char *key;
    char *value;
    key = NULL;
    value = NULL;
    if (*shell_var == NULL)
        add_shell_var_node(shell_var, line);
    else
    {
        key = ft_strcdup(line, '=');
        value = ft_strchr(line, '=') + 1;
        set_shell_var(shell_var, key, value);
        free(key);
    }
    return (0);
}
References add_shell_var_node(), ft_strcdup(), ft_strchr(), and set_shell_var().
Referenced by handle_local_vars(), and init_ms_data().
init_env()
void init_env (t_env ** data_envp, char ** envp)
Definition at line 24 of file env.c.
{
    int i;
    i = -1;
    while (envp[++i])
        add_env_node(data_envp, envp[i]);
}
References add_env_node().
Referenced by init_ms_data(), test_get_env(), test_init_env(), and test_set_env().
print_t_env()
void print_t_env (t_env * tokens)
Definition at line 104 of file utils.c.
{
    t_env   *token;
    int     i;
    i = 0;
    token = tokens;
    while (token != NULL)
    {
        ft_printf("key[%d]      ->  %s \n", i, token->key);
        ft_printf("value[%d]    ->  %s \n", i, token->value);
        token = token->next;
        i++;
    }
}
References ft_printf(), s_env::key, s_env::next, and s_env::value.
set_env()
void set_env (t_env ** env, const char * key, const char * value)
Definition at line 79 of file env.c.
{
    t_env   *current;
    t_env   *new_env;
    printf("KEY -> %s\nVALUE -> %s\n", key, value);
    current = *env;
    while (current)
    {
        if (ft_strcmp(current->key, key) == 0)
        {
            free(current->value);
            current->value = ft_strdup(value);
            return ;
        }
        current = current->next;
    }
    new_env = malloc(sizeof(t_env));
    new_env->key = ft_strdup(key);
    new_env->value = ft_strdup(value);
    new_env->next = *env;
    *env = new_env;
}
References ft_strcmp(), ft_strdup(), s_env::key, s_env::next, and s_env::value.
Referenced by add_env(), builtin_cd(), test_set_env(), and test_unset_env().
set_shell_var()
void set_shell_var (t_env ** shell_var, const char * key, const char * value)
Definition at line 41 of file shell_variables_utils.c.
{
    t_env   *current;
    t_env   *new_env;
    current = *shell_var;
    while (current)
    {
        if (ft_strcmp(current->key, key) == 0)
        {
            free(current->value);
            current->value = ft_strdup(value);
            return ;
        }
        current = current->next;
    }
    new_env = malloc(sizeof(t_env));
    new_env->key = ft_strdup(key);
    new_env->value = ft_strdup(value);
    new_env->next = *shell_var;
    *shell_var = new_env;
}
References ft_strcmp(), ft_strdup(), s_env::key, s_env::next, and s_env::value.
Referenced by handle_add_set_shell_variable().
unset_env()
int unset_env (t_env ** env, const char * name)
Definition at line 103 of file env.c.
{
    t_env   *current;
    t_env   *prev;
    current = *env;
    prev = NULL;
    while (current)
    {
        if (ft_strcmp(current->key, key) == 0)
        {
            if (prev)
                prev->next = current->next;
            else
                *env = current->next;
            free(current->key);
            free(current->value);
            free(current);
            return (0);
        }
        prev = current;
        current = current->next;
    }
    return (-1);
}
References ft_strcmp(), s_env::key, s_env::next, and s_env::value.
Referenced by builtin_unset(), and test_unset_env().