maxishell: /github/workspace/src/test/env/env_test.c File Reference
env_test.c File Reference
#include <assert.h>
#include "libft.h"
#include "env.h"
#include "shell.h"
#include <stdio.h>
Functions
void env_tests (t_minishell_data *data, char **envp)
void test_init_env (t_minishell_data *data, char **envp)
void test_get_env (t_minishell_data *data, char **envp)
void test_set_env (t_minishell_data *data, char **envp)
void test_unset_env (t_minishell_data *data)
Function Documentation
env_tests()
void env_tests (t_minishell_data * data, char ** envp)
Definition at line 25 of file env_test.c.
{
    printf("\nENV TESTS\n");
    test_init_env(data, envp);
    test_get_env(data, envp);
    test_set_env(data, envp);
    test_unset_env(data);
    free_env(data->envp);
}
References BUFFER_SIZE, s_minishell_data::envp, free_env(), test_get_env(), test_init_env(), test_set_env(), and test_unset_env().
Referenced by main().
test_get_env()
void test_get_env (t_minishell_data * data, char ** envp)
Definition at line 57 of file env_test.c.
{
    char    *value;
    data->envp = NULL;
    init_env(&data->envp, envp);
    value = get_env(data->envp, "LOGNAME");
    assert(value != NULL);
    assert(ft_strcmp(value, getenv("LOGNAME")) == 0);
    printf("\033[0m");
    printf("\033[0;32m");
    printf("get_env     -> OK\n");
    printf("\033[0m");
}
References BUFFER_SIZE, s_minishell_data::envp, ft_strcmp(), get_env(), and init_env().
Referenced by env_tests().
test_init_env()
void test_init_env (t_minishell_data * data, char ** envp)
Definition at line 35 of file env_test.c.
{
    char    **test_envp;
    int     envp_count;
    int     test_envp_count;
    data->envp = NULL;
    init_env(&data->envp, envp);
    test_envp = env_to_array(data->envp);
    envp_count = 0;
    while (envp[envp_count])
        envp_count++;
    test_envp_count = 0;
    while (test_envp[test_envp_count])
        test_envp_count++;
    assert(envp_count == test_envp_count);
    printf("\033[0m");
    printf("\033[0;32m");
    printf("init_env    -> OK\n");
    printf("\033[0m");
}
References BUFFER_SIZE, env_to_array(), s_minishell_data::envp, and init_env().
Referenced by env_tests().
test_set_env()
void test_set_env (t_minishell_data * data, char ** envp)
Definition at line 72 of file env_test.c.
{
    char    *value;
    data->envp = NULL;
    init_env(&data->envp, envp);
    set_env(&data->envp, "TEST", "test");
    value = get_env(data->envp, "TEST");
    assert(value != NULL);
    assert(ft_strcmp(value, "test") == 0);
    printf("\033[0m");
    printf("\033[0;32m");
    printf("set_env     -> OK\n");
    printf("\033[0m");
}
References BUFFER_SIZE, s_minishell_data::envp, ft_strcmp(), get_env(), init_env(), and set_env().
Referenced by env_tests().
test_unset_env()
void test_unset_env (t_minishell_data * data)
Definition at line 88 of file env_test.c.
{
    char    *value;
    set_env(&data->envp, "TEST", "test");
    value = get_env(data->envp, "TEST");
    assert(value != NULL);
    assert(ft_strcmp(value, "test") == 0);
    unset_env(&data->envp, "TEST");
    value = get_env(data->envp, "TEST");
    assert(value == NULL);
    printf("\033[0m");
    printf("\033[0;32m");
    printf("unset_env   -> OK\n");
    printf("\033[0m");
}
References BUFFER_SIZE, s_minishell_data::envp, ft_strcmp(), get_env(), set_env(), and unset_env().
Referenced by env_tests().