maxishell: /github/workspace/src/execute/execute_child.c File Reference
execute_child.c File Reference
#include "builtins.h"
#include "libft.h"
#include <stdio.h>
#include <sys/wait.h>
#include "shell.h"
#include "execute.h"
#include "tokens.h"
#include "pipe.h"
#include "redirection.h"
#include "exit_status.h"
#include "signals.h"
Functions
int execute (t_ms_data *data)
execute distribution function
static int new_process (t_ms_data *data)
static void signal_handler (void)
static void handle_exec_errors (char *exec_path, t_ms_data *data)
static void child_process (t_ms_data *data)
executes a new process
Function Documentation
child_process()
static void child_process (t_ms_data * data) static
executes a new process
--
Parameters
data minishell data structure
Returns
int return status:
- 0: SUCCESS
- 1: ERROR
Definition at line 67 of file execute_child.c.
{
    char    *exec_path;
    handle_std_io(&data->std_in, STDIN_FILENO);
    handle_std_io(&data->std_out, STDOUT_FILENO);
    close_fds(data->std_in, data->std_out);
    signal_handler();
    if (ft_strncmp(data->args[0], "/", 1) == 0)
        exec_path = ft_strdup(data->args[0]);
    else
        exec_path = ft_find_path(data->args[0], data->envp);
    handle_exec_errors(exec_path, data);
}
References s_ms_data::args, close_fds(), s_ms_data::envp, ft_find_path(), ft_strdup(), ft_strncmp(), handle_exec_errors(), handle_std_io(), signal_handler(), s_ms_data::std_in, and s_ms_data::std_out.
Referenced by new_process().
execute()
int execute (t_ms_data * data)
execute distribution function
--
Parameters
data minishell data struct
Returns
int return status:
- 0: success
- 1: error
Definition at line 29 of file execute_child.c.
{
    size_t  i;
    char    *builtin_commands[7];
    int     (*builtin_functions[7])(t_ms_data *);
    builtin_commands[0] = "cd";
    builtin_commands[1] = "echo";
    builtin_commands[2] = "env";
    builtin_commands[3] = "exit";
    builtin_commands[4] = "export";
    builtin_commands[5] = "pwd";
    builtin_commands[6] = "unset";
    builtin_functions[0] = &builtin_cd;
    builtin_functions[1] = &builtin_echo;
    builtin_functions[2] = &builtin_env;
    builtin_functions[3] = &builtin_exit;
    builtin_functions[4] = &builtin_export;
    builtin_functions[5] = &builtin_pwd;
    builtin_functions[6] = &builtin_unset;
    if (data->args[0] == NULL)
        ft_perror("minishel");
    i = -1;
    while (++i < sizeof(builtin_commands) / sizeof(char *))
        if (ft_strcmp(data->args[0], builtin_commands[i]) == 0)
            return ((*builtin_functions[i])(data));
    return (new_process(data));
}
References s_ms_data::args, builtin_cd(), builtin_echo(), builtin_env(), builtin_exit(), builtin_export(), builtin_pwd(), builtin_unset(), ft_perror(), ft_strcmp(), and new_process().
Referenced by execute_ast().
handle_exec_errors()
static void handle_exec_errors (char * exec_path, t_ms_data * data) static
Definition at line 104 of file execute_child.c.
{
    if (exec_path == NULL)
    {
        ft_putstr_fd("maxishell: command not found\n", STDERR_FILENO);
        exit(127);
    }
    if (!data->args || !data->args[0] || !data->envp)
    {
        ft_putstr_fd("maxishell: invalid \
            arguments or environment\n", STDERR_FILENO);
        exit(EXIT_FAILURE);
    }
    if (execve(exec_path, data->args, env_to_array(data->envp)) == -1)
    {
        ft_putstr_fd("minishell: fuck it\n", STDERR_FILENO);
        exit(IS_DIRECTORY);
    }
}
References s_ms_data::args, env_to_array(), s_ms_data::envp, EXIT_FAILURE, ft_putstr_fd(), and IS_DIRECTORY.
Referenced by child_process().
new_process()
static int new_process (t_ms_data * data) static
Definition at line 82 of file execute_child.c.
{
    pid_t   pid;
    int     exit;
    exit = 0;
    handle_std_io(&data->std_in, STDIN_FILENO);
    handle_std_io(&data->std_out, STDOUT_FILENO);
    pid = fork();
    if (pid == -1)
        ft_perror("fork");
    if (pid == 0)
        child_process(data);  // Call the separated child process function
    close_fds(data->std_in, data->std_out);
    waitpid(pid, &exit, 0);
    data->exit_status = WEXITSTATUS(exit);
    if (WIFSIGNALED(exit) && WTERMSIG(exit) == SIGQUIT)
        ft_printf("\n");
    set_shell_var_handler(data);
    return (EXIT_SUCCESS);
}
References child_process(), close_fds(), s_ms_data::exit_status, EXIT_SUCCESS, ft_perror(), ft_printf(), handle_std_io(), set_shell_var_handler(), s_ms_data::std_in, and s_ms_data::std_out.
Referenced by execute().
signal_handler()
static void signal_handler (void) static
Definition at line 124 of file execute_child.c.
{
    struct sigaction    a;
    ft_memset(&a, 0, sizeof(struct sigaction));
    sigemptyset(&a.sa_mask);
    a.sa_handler = SIG_DFL;
    a.sa_flags = 0;
    sigaction(SIGQUIT, &a, NULL);
}
References ft_memset().
Referenced by child_process().