maxishell: /github/workspace/src/execute/execute.c File Reference
execute.c File Reference
#include "builtins.h"
#include "libft.h"
#include <stdio.h>
#include <sys/wait.h>
#include "shell.h"
#include "execute.h"
#include "tokens.h"
#include "pipe.h"
#include "redirection.h"
#include "exit_status.h"
#include "signals.h"
Functions
int execute_ast (t_ast *node, t_ms_data *data)
execute Abstract Syntax Tree
static int execute (t_ms_data *data)
execute distribution function
static int new_process (t_ms_data *data)
executes a new process
static void signal_handler (void)
static void handle_exec_errors (char *exec_path, t_ms_data *data)
Function Documentation
execute()
static int execute (t_ms_data * data) static
execute distribution function
--
Parameters
data minishell data struct
Returns
int return status:
- 0: success
- 1: error
Definition at line 72 of file execute.c.
{
    size_t  i;
    char    *builtin_commands[7];
    int     (*builtin_functions[7])(t_ms_data *);
    builtin_commands[0] = "cd";
    builtin_commands[1] = "echo";
    builtin_commands[2] = "env";
    builtin_commands[3] = "exit";
    builtin_commands[4] = "export";
    builtin_commands[5] = "pwd";
    builtin_commands[6] = "unset";
    builtin_functions[0] = &builtin_cd;
    builtin_functions[1] = &builtin_echo;
    builtin_functions[2] = &builtin_env;
    builtin_functions[3] = &builtin_exit;
    builtin_functions[4] = &builtin_export;
    builtin_functions[5] = &builtin_pwd;
    builtin_functions[6] = &builtin_unset;
    if (data->args[0] == NULL)
        ft_perror("minishel");
    i = -1;
    while (++i < sizeof(builtin_commands) / sizeof(char *))
        if (ft_strcmp(data->args[0], builtin_commands[i]) == 0)
            return ((*builtin_functions[i])(data));
    return (new_process(data));
}
References s_ms_data::args, builtin_cd(), builtin_echo(), builtin_env(), builtin_exit(), builtin_export(), builtin_pwd(), builtin_unset(), ft_perror(), ft_strcmp(), and new_process().
Referenced by execute_ast().
execute_ast()
int execute_ast (t_ast * node, t_ms_data * data)
execute Abstract Syntax Tree
--
Parameters
node Abstract Syntax Tree Node
Parameters
data minishell data struct
Returns
int return status:
- 0: success
- 1: error
Definition at line 41 of file execute.c.
{
    if (!node)
        return (EXIT_FAILURE);
    if (node->type == PIPE)
        return (builtin_pipe(node, data));
    else if (node->type == REDIR_IN)
        return (redirect_in(node, data));
    else if (node->type == REDIR_OUT)
        return (redirect_out(node, data));
    else if (node->type == REDIR_APPEND)
        return (redirect_append(node, data));
    else if (node->type == REDIR_HEREDOC)
        return (redirect_here_doc(node, data));
    else if (node->type == PHRASE)
    {
        data->args = node->args;
        return (execute(data));
    }
    return (EXIT_SUCCESS);
}
References s_ms_data::args, s_ast::args, builtin_pipe(), execute(), EXIT_FAILURE, EXIT_SUCCESS, PHRASE, PIPE, REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, REDIR_OUT, redirect_append(), redirect_here_doc(), redirect_in(), redirect_out(), and s_ast::type.
Referenced by execute_child(), execute_child(), process_ast_and_io(), redirect_append(), redirect_in(), and redirect_out().
handle_exec_errors()
static void handle_exec_errors (char * exec_path, t_ms_data * data) static
Definition at line 137 of file execute.c.
{
    if (!exec_path)
    {
        ft_putstr_fd("maxishell: command not found\n", STDERR_FILENO);
        exit(EXIT_FAILURE);
    }
    if (!data->args || !data->args[0] || !data->envp)
    {
        ft_putstr_fd("maxishell: invalid \
            arguments or environment\n", STDERR_FILENO);
        exit(EXIT_FAILURE);
    }
    if (execve(exec_path, data->args, env_to_array(data->envp)) == -1)
    {
        exit_status_handler(data, IS_DIRECTORY, "maxishell: ");
        exit(IS_DIRECTORY);
    }
}
References s_ms_data::args, env_to_array(), s_ms_data::envp, EXIT_FAILURE, exit_status_handler(), ft_putstr_fd(), and IS_DIRECTORY.
Referenced by new_process().
new_process()
static int new_process (t_ms_data * data) static
executes a new process
--
Parameters
data minishell data structure
Returns
int return status:
- 0: SUCCESS
- 1: ERROR
Definition at line 110 of file execute.c.
{
    pid_t               pid;
    char                *exec_path;
    handle_std_io(&data->std_in, STDIN_FILENO);
    handle_std_io(&data->std_out, STDOUT_FILENO);
    pid = fork();
    if (pid == -1)
        ft_perror("fork");
    if (pid == 0)
    {
        handle_std_io(&data->std_in, STDIN_FILENO);
        handle_std_io(&data->std_out, STDOUT_FILENO);
        close_fds(data->std_in, data->std_out);
        signal_handler();
        exec_path = ft_find_path(data->args[0], data->envp);
        handle_exec_errors(exec_path, data);
    }
    close_fds(data->std_in, data->std_out);
    waitpid(pid, &data->exit_status, 0);
    if (WIFSIGNALED(data->exit_status) \
            && WTERMSIG(data->exit_status) == SIGQUIT)
        ft_printf("\n");
    return (EXIT_SUCCESS);
}
References s_ms_data::args, close_fds(), s_ms_data::envp, s_ms_data::exit_status, EXIT_SUCCESS, ft_find_path(), ft_perror(), ft_printf(), handle_exec_errors(), handle_std_io(), signal_handler(), s_ms_data::std_in, and s_ms_data::std_out.
Referenced by execute().
signal_handler()
static void signal_handler (void) static
Definition at line 157 of file execute.c.
{
    struct sigaction    a;
    ft_memset(&a, 0, sizeof(struct sigaction));
    sigemptyset(&a.sa_mask);
    a.sa_handler = SIG_DFL;
    a.sa_flags = 0;
    sigaction(SIGQUIT, &a, NULL);
}
References ft_memset().
Referenced by new_process().