maxishell: /github/workspace/inc/execute.h File Reference
execute.h File Reference
#include "shell.h"
#include "tokens.h"
Functions
int execute (t_minishell_data *data)
execute distribution function checks if the command is a builtin or a new process
int execute_ast (t_ast *node, t_minishell_data *data)
execute Abstract Syntax Tree
int new_process (t_minishell_data *data)
executes a new process
char * ft_find_path (char *cmd, t_env *envp)
function find the full path of the executed command
void ft_free_2d_arr (char **arr)
clean up 2d array
int ft_perror (char *str)
return error message and exit
void close_fds (int in, int out)
close two file descriptors
void handle_io_fd (t_minishell_data *data)
close temporary input/output file descriptors and reset them to -1
Function Documentation
close_fds()
void close_fds (int in, int out)
close two file descriptors
--
Parameters
fds file descriptors
Definition at line 93 of file utils_0.c.
{
    close(in);
    close(out);
}
Referenced by builtin_pipe(), execute_child(), new_process(), and redirect_here_doc().
execute()
int execute (t_minishell_data * data)
execute distribution function checks if the command is a builtin or a new process
--
Parameters
data minishell data struct
Returns
int return status:
- 0: success
- 1: error
Definition at line 93 of file execute.c.
{
    size_t  i;
    char    *builtin_commands[7];
    int     (*builtin_functions[7])(t_minishell_data *);
    builtin_commands[0] = "cd";
    builtin_commands[1] = "echo";
    builtin_commands[2] = "env";
    builtin_commands[3] = "exit";
    builtin_commands[4] = "export";
    builtin_commands[5] = "pwd";
    builtin_commands[6] = "unset";
    builtin_functions[0] = &builtin_cd;
    builtin_functions[1] = &builtin_echo;
    builtin_functions[2] = &builtin_env;
    builtin_functions[3] = &builtin_exit;
    builtin_functions[4] = &builtin_export;
    builtin_functions[5] = &builtin_pwd;
    builtin_functions[6] = &builtin_unset;
    if (data->args[0] == NULL)
        return (2);
    i = -1;
    while (++i < sizeof(builtin_commands) / sizeof(char *))
        if (ft_strcmp(data->args[0], builtin_commands[i]) == 0)
            return ((*builtin_functions[i])(data));
    return (new_process(data));
}
References s_minishell_data::args, builtin_cd(), builtin_echo(), builtin_env(), builtin_exit(), builtin_export(), builtin_pwd(), builtin_unset(), ft_strcmp(), and new_process().
Referenced by execute_ast().
execute_ast()
int execute_ast (t_ast * node, t_minishell_data * data)
execute Abstract Syntax Tree
--
Parameters
node Abstract Syntax Tree Node
Parameters
data minishell data struct
Returns
int return status:
- 0: success
- 1: error
Definition at line 41 of file execute.c.
{
    if (!node)
        return (1);
    if (node->type == PIPE)
    {
        printf(RED"PIPE\n"RESET);
        return (builtin_pipe(node, data));
    }
    else if (node->type == ENV_VAR)     // "$()"
    {
        printf(BLU"ENV_VAR\n"RESET);
        //execute_redirect(node, data);
    }
    else if (node->type == REDIR_IN)
    {
        printf(GRN"REDIR_IN\n"RESET);
        return (redirect_in(node, data));
    }
    else if (node->type == REDIR_OUT)   // ">"
    {
        printf(CYA"REDIR_OUT\n"RESET);
        return (redirect_out(node, data));
    }
    else if (node->type == REDIR_APPEND) // ">>"
    {
        printf(CYA"REDIR_APPEND\n"RESET);
        return (redirect_append(node, data));
    }
    else if (node->type == REDIR_HEREDOC) // "<<"
    {
        printf(MAG"REDIR_HEREDOC\n"RESET);
        return (redirect_here_doc(node, data));
    }
    else if (node->type == PHRASE)
    {
        printf(YEL"PHRASE\n"RESET);
        data->args = node->args;
        return (execute(data));
    }
    return (0);
}
References s_minishell_data::args, s_ast::args, BLU, builtin_pipe(), CYA, ENV_VAR, execute(), GRN, MAG, PHRASE, PIPE, RED, REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, REDIR_OUT, redirect_append(), redirect_here_doc(), redirect_in(), redirect_out(), RESET, s_ast::type, and YEL.
Referenced by execute_child(), main_loop(), redirect_append(), redirect_here_doc(), redirect_in(), and redirect_out().
ft_find_path()
char * ft_find_path (char * cmd, t_env * envp)
function find the full path of the executed command
--
Parameters
cmd string from the first argument
Parameters
envp structure with environment variables
Returns
char* returns the full path of the command
Definition at line 32 of file utils_0.c.
{
    char    **path;
    char    *tmp_slash;
    char    *tmp_full_path;
    int     i;
    path = ft_split(get_env(envp, "PATH"), ':');
    i = -1;
    while (path[++i] != NULL)
    {
        tmp_slash = ft_strjoin(path[i], "/");
        tmp_full_path = ft_strjoin(tmp_slash, cmd);
        free(tmp_slash);
        if (access(tmp_full_path, F_OK) == 0)
        {
            ft_free_2d_arr(path);
            return (tmp_full_path);
        }
        free(tmp_full_path);
    }
    ft_free_2d_arr(path);
    return (NULL);
}
References ft_free_2d_arr(), ft_split(), ft_strjoin(), and get_env().
Referenced by new_process().
ft_free_2d_arr()
void ft_free_2d_arr (char ** arr)
clean up 2d array
--
Parameters
arr simple two dimensional array
Definition at line 63 of file utils_0.c.
{
    int i;
    i = -1;
    while (arr[++i] != NULL)
        free(arr[i]);
    free(arr);
}
Referenced by ft_find_path().
ft_perror()
int ft_perror (char * str)
return error message and exit
--
Parameters
str paste the error message
Returns
int return status:
- 1: EXIT_FAILURE
Definition at line 81 of file utils_0.c.
{
    perror (str);
    exit(EXIT_FAILURE);
}
Referenced by builtin_pipe(), execute_child(), new_process(), and redirect_here_doc().
handle_io_fd()
void handle_io_fd (t_minishell_data * data)
close temporary input/output file descriptors and reset them to -1
--
Parameters
data minishell structure
Definition at line 104 of file utils_0.c.
{
    if (data->std_in != -1 && data->std_out != -1)
    {
        close(data->std_in);
        close(data->std_out);
        data->std_in = -1;
        data->std_out = -1;
    }
}
References s_minishell_data::std_in, and s_minishell_data::std_out.
Referenced by main_loop().
new_process()
int new_process (t_minishell_data * data)
executes a new process
--
Parameters
data minishell data structure
Returns
int return status:
- 0: success
- 1: error
Definition at line 131 of file execute.c.
{
    pid_t   pid;
    printf("data->std_in: %d\n", data->std_in);
    printf("data->std_out: %d\n", data->std_out);
    if(data->std_in == -1)
        data->std_in = dup(STDIN_FILENO);
    if(data->std_out == -1)
        data->std_out = dup(STDOUT_FILENO);
    pid = fork();
    if (pid == -1)
        ft_perror("fork");
    if (pid == 0)
    {
        if (data->std_in != -1)
            dup2(data->std_in, STDIN_FILENO);
        if (data->std_out != -1)
            dup2(data->std_out, STDOUT_FILENO);
        close_fds(data->std_in, data->std_out);
        if (execve(ft_find_path(data->args[0], data->envp), \
                data->args, env_to_array(data->envp)) == -1)
            ft_perror("minishell");
    }
    waitpid(pid, &data->exit_status, 0);
    close_fds(data->std_in, data->std_out);
    return (0);
}
References s_minishell_data::args, close_fds(), env_to_array(), s_minishell_data::envp, s_minishell_data::exit_status, ft_find_path(), ft_perror(), s_minishell_data::std_in, and s_minishell_data::std_out.
Referenced by execute().