maxishell: /github/workspace/inc/exit_status.h File Reference
exit_status.h File Reference
#include "shell.h"
#include <errno.h>
Macros
#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#define EXIT_MISUSE 2
#define IS_DIRECTORY 256
#define NUMERIC_REQUIRED 257
#define TOO_MANY_ARGS 258
#define UNKNOWN_COMMAND 259
#define INVALID_ARGUMENT 260
#define PERMISSION_DENIED 261
#define ERROR_EXIT 262
#define NOT_VALID_IDENTIFIER 263
#define INVALID_OPTION 264
Functions
void exit_status_handler (t_ms_data *data, int status_code, char *err_arg)
void set_exit_status (int *exit_status, int status_code)
void set_shell_var_handler (t_ms_data *data)
int ft_perror (char *str)
int ft_isnumber (char *str)
void free_shell_var_list (t_env *shell_var)
void handle_exit (t_ms_data *data, int status)
Macro Definition Documentation
ERROR_EXIT
#define ERROR_EXIT 262
Definition at line 26 of file exit_status.h.
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 17 of file exit_status.h.
EXIT_MISUSE
#define EXIT_MISUSE 2
Definition at line 18 of file exit_status.h.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 16 of file exit_status.h.
INVALID_ARGUMENT
#define INVALID_ARGUMENT 260
Definition at line 24 of file exit_status.h.
INVALID_OPTION
#define INVALID_OPTION 264
Definition at line 28 of file exit_status.h.
IS_DIRECTORY
#define IS_DIRECTORY 256
Definition at line 20 of file exit_status.h.
NOT_VALID_IDENTIFIER
#define NOT_VALID_IDENTIFIER 263
Definition at line 27 of file exit_status.h.
NUMERIC_REQUIRED
#define NUMERIC_REQUIRED 257
Definition at line 21 of file exit_status.h.
PERMISSION_DENIED
#define PERMISSION_DENIED 261
Definition at line 25 of file exit_status.h.
TOO_MANY_ARGS
#define TOO_MANY_ARGS 258
Definition at line 22 of file exit_status.h.
UNKNOWN_COMMAND
#define UNKNOWN_COMMAND 259
Definition at line 23 of file exit_status.h.
Function Documentation
exit_status_handler()
void exit_status_handler (t_ms_data * data, int status_code, char * err_arg)
Definition at line 25 of file exit_status.c.
{
    char    *error_message;
    error_message = NULL;
    if (status_code == IS_DIRECTORY)
        error_message = "No such file or directory";
    else if (status_code == NUMERIC_REQUIRED)
        error_message = "numeric argument required";
    else if (status_code == TOO_MANY_ARGS)
        error_message = "too many arguments";
    else if (status_code == UNKNOWN_COMMAND)
        error_message = "command not found";
    else if (status_code == INVALID_ARGUMENT)
        error_message = "invalid argument";
    else if (status_code == PERMISSION_DENIED)
        error_message = "permission denied";
    else if (status_code == NOT_VALID_IDENTIFIER)
        error_message = "unset: not a valid identifier";
    else if (status_code == INVALID_OPTION)
        error_message = "invalid option";
    else
        error_message = "error";
    ft_puterror(err_arg, error_message);
    set_exit_status(&data->exit_status, status_code);
    set_shell_var_handler(data);
}
References s_ms_data::exit_status, ft_puterror(), INVALID_ARGUMENT, INVALID_OPTION, IS_DIRECTORY, NOT_VALID_IDENTIFIER, NUMERIC_REQUIRED, PERMISSION_DENIED, set_exit_status(), set_shell_var_handler(), TOO_MANY_ARGS, and UNKNOWN_COMMAND.
Referenced by builtin_cd(), builtin_export(), handle_numeric_error(), and handle_too_many_args_error().
free_shell_var_list()
void free_shell_var_list (t_env * shell_var)
Definition at line 90 of file shell_variables_utils.c.
{
    t_env   *curr_node;
    t_env   *next_node;
    curr_node = shell_var;
    while (curr_node)
    {
        next_node = curr_node->next;
        free(curr_node->key);
        free(curr_node->value);
        free(curr_node);
        curr_node = next_node;
    }
}
References s_env::key, s_env::next, and s_env::value.
Referenced by free_ms_data().
ft_isnumber()
int ft_isnumber (char * str)
Definition at line 24 of file exit_status_utils.c.
{
    int i;
    i = 0;
    while (str[i])
    {
        if (!ft_isdigit(str[i]))
            return (0);
        i++;
    }
    return (1);
}
References ft_isdigit().
Referenced by builtin_exit().
ft_perror()
int ft_perror (char * str)
Definition at line 18 of file exit_status_utils.c.
{
    perror (str);
    exit(EXIT_FAILURE);
}
handle_exit()
void handle_exit (t_ms_data * data, int status)
Definition at line 53 of file exit.c.
{
    if (status != 0 && status != TOO_MANY_ARGS)
        ft_putendl_fd("exit", STDOUT_FILENO);
    cleanup_exit_resources(data);
    exit(status);
}
References cleanup_exit_resources(), ft_putendl_fd(), and TOO_MANY_ARGS.
Referenced by builtin_exit(), handle_numeric_error(), handle_too_many_args_error(), and signal_reset_prompt().
set_exit_status()
void set_exit_status (int * exit_status, int status_code)
Definition at line 79 of file exit_status.c.
{
    *exit_status = status_code;
}
Referenced by builtin_env(), and exit_status_handler().
set_shell_var_handler()
void set_shell_var_handler (t_ms_data * data)
Definition at line 53 of file exit_status.c.
{
    char    *tmp_var;
    tmp_var = NULL;
    tmp_var = ft_itoa(data->exit_status);
    set_shell_var(&data->shell_variables, "?", tmp_var);
    free(tmp_var);
}
References s_ms_data::exit_status, ft_itoa(), set_shell_var(), and s_ms_data::shell_variables.
Referenced by exit_status_handler(), and process_ast_and_io().