maxishell: /github/workspace/src/builtins/exit.c File Reference
exit.c File Reference
#include "shell.h"
#include "libft.h"
#include <stdlib.h>
#include <stdio.h>
#include "env.h"
#include "exit_status.h"
#include "tokens.h"
#include "signals.h"
#include "builtins.h"
Functions
void cleanup_exit_resources (t_ms_data *data)
void handle_numeric_error (t_ms_data *data, const char *arg)
void handle_too_many_args_error (t_ms_data *data)
void handle_exit (t_ms_data *data, int status)
int builtin_exit (t_ms_data *data)
Function Documentation
builtin_exit()
int builtin_exit (t_ms_data * data)
Definition at line 66 of file exit.c.
{
    int number;
    number = 0;
    if (data->args[1])
    {
        if (ft_isnumber(data->args[1]) == 0)
            handle_numeric_error(data, data->args[1]);
        else if (data->args[2])
            handle_too_many_args_error(data);
        else
        {
            number = ft_atoi(data->args[1]);
            ft_free_2d_arr(data->args);
            data->args = NULL;
            handle_exit(data, number);
        }
    }
    else
    {
        ft_free_2d_arr(data->args);
        data->args = NULL;
        ft_putendl_fd("exit", STDOUT_FILENO);
        handle_exit(data, 0);
    }
    return (0);
}
References s_ms_data::args, ft_atoi(), ft_free_2d_arr(), ft_isnumber(), ft_putendl_fd(), handle_exit(), handle_numeric_error(), and handle_too_many_args_error().
Referenced by execute(), and main_loop().
cleanup_exit_resources()
void cleanup_exit_resources (t_ms_data * data)
Definition at line 30 of file exit.c.
{
    if (data->args)
    {
        ft_free_2d_arr(data->args);
        data->args = NULL;
    }
    clear_history_file();
    free_ms_data(data);
    free_signal_context();
}
References s_ms_data::args, clear_history_file(), free_ms_data(), free_signal_context(), and ft_free_2d_arr().
Referenced by handle_exit().
handle_exit()
void handle_exit (t_ms_data * data, int status)
Definition at line 58 of file exit.c.
{
    if (status != 0 && status != TOO_MANY_ARGS)
        ft_putendl_fd("exit", STDOUT_FILENO);
    cleanup_exit_resources(data);
    exit(status);
}
References cleanup_exit_resources(), ft_putendl_fd(), and TOO_MANY_ARGS.
Referenced by builtin_exit(), handle_numeric_error(), handle_too_many_args_error(), and signal_reset_prompt().
handle_numeric_error()
void handle_numeric_error (t_ms_data * data, const char * arg)
Definition at line 42 of file exit.c.
{
    char    *temp_str;
    temp_str = ft_strjoin("exit: ", arg);
    exit_status_handler(data, NUMERIC_REQUIRED, temp_str);
    free(temp_str);
    handle_exit(data, 0);
}
References exit_status_handler(), ft_strjoin(), handle_exit(), and NUMERIC_REQUIRED.
Referenced by builtin_exit().
handle_too_many_args_error()
void handle_too_many_args_error (t_ms_data * data)
Definition at line 52 of file exit.c.
{
    exit_status_handler(data, TOO_MANY_ARGS, "exit");
    handle_exit(data, TOO_MANY_ARGS);
}
References exit_status_handler(), handle_exit(), and TOO_MANY_ARGS.
Referenced by builtin_exit().