maxishell: /github/workspace/src/exit_status/exit_status.c File Reference
exit_status.c File Reference
#include "exit_status.h"
#include "libft.h"
#include <unistd.h>
#include "shell.h"
#include <stdio.h>
Functions
void exit_status_handler (t_ms_data *data, int status_code, char *err_arg)
void ft_puterror (char *err_arg, char *error_message)
void set_exit_status (int *exit_status, int status_code)
void set_shell_var_handler (t_ms_data *data)
Function Documentation
exit_status_handler()
void exit_status_handler (t_ms_data * data, int status_code, char * err_arg)
Definition at line 25 of file exit_status.c.
{
    char    *error_message;
    error_message = NULL;
    if (status_code == IS_DIRECTORY)
        error_message = "No such file or directory";
    else if (status_code == NUMERIC_REQUIRED)
        error_message = "numeric argument required";
    else if (status_code == TOO_MANY_ARGS)
        error_message = "too many arguments";
    else if (status_code == UNKNOWN_COMMAND)
        error_message = "command not found";
    else if (status_code == INVALID_ARGUMENT)
        error_message = "invalid argument";
    else if (status_code == PERMISSION_DENIED)
        error_message = "permission denied";
    else if (status_code == NOT_VALID_IDENTIFIER)
        error_message = "unset: not a valid identifier";
    else if (status_code == INVALID_OPTION)
        error_message = "invalid option";
    else
        error_message = "error";
    ft_puterror(err_arg, error_message);
    set_exit_status(&data->exit_status, status_code);
    set_shell_var_handler(data);
}
References s_ms_data::exit_status, ft_puterror(), INVALID_ARGUMENT, INVALID_OPTION, IS_DIRECTORY, NOT_VALID_IDENTIFIER, NUMERIC_REQUIRED, PERMISSION_DENIED, set_exit_status(), set_shell_var_handler(), TOO_MANY_ARGS, and UNKNOWN_COMMAND.
Referenced by builtin_cd(), builtin_export(), handle_numeric_error(), and handle_too_many_args_error().
ft_puterror()
void ft_puterror (char * err_arg, char * error_message)
Definition at line 63 of file exit_status.c.
{
    if (err_arg)
    {
        ft_putstr_fd("bash: ", STDERR_FILENO);
        ft_putstr_fd(err_arg, STDERR_FILENO);
        ft_putstr_fd(": ", STDERR_FILENO);
        ft_putendl_fd(error_message, STDERR_FILENO);
    }
    else
    {
        ft_putstr_fd("bash: ", STDERR_FILENO);
        ft_putendl_fd(error_message, STDERR_FILENO);
    }
}
References ft_putendl_fd(), and ft_putstr_fd().
Referenced by exit_status_handler().
set_exit_status()
void set_exit_status (int * exit_status, int status_code)
Definition at line 79 of file exit_status.c.
{
    *exit_status = status_code;
}
Referenced by builtin_env(), and exit_status_handler().
set_shell_var_handler()
void set_shell_var_handler (t_ms_data * data)
Definition at line 53 of file exit_status.c.
{
    char    *tmp_var;
    tmp_var = NULL;
    tmp_var = ft_itoa(data->exit_status);
    set_shell_var(&data->shell_variables, "?", tmp_var);
    free(tmp_var);
}
References s_ms_data::exit_status, ft_itoa(), set_shell_var(), and s_ms_data::shell_variables.
Referenced by exit_status_handler(), and process_ast_and_io().