maxishell: /github/workspace/src/exit_status/exit_status_utils.c File Reference
exit_status_utils.c File Reference
#include "exit_status.h"
#include <stdio.h>
#include <stdlib.h>
#include "libft.h"
Functions
int ft_perror (char *str)
int ft_isnumber (char *str)
Function Documentation
ft_isnumber()
int ft_isnumber (char * str)
Definition at line 24 of file exit_status_utils.c.
{
    int i;
    i = 0;
    while (str[i])
    {
        if (!ft_isdigit(str[i]))
            return (0);
        i++;
    }
    return (1);
}
References ft_isdigit().
Referenced by builtin_exit().
ft_perror()
int ft_perror (char * str)
Definition at line 18 of file exit_status_utils.c.
{
    perror (str);
    exit(EXIT_FAILURE);
}
References EXIT_FAILURE.
Referenced by builtin_pipe(), execute_child(), execute_child(), new_process(), open_tmp_file(), and setup_pipe_processes().