maxishell: /github/workspace/src/builtins/export.c File Reference
export.c File Reference
#include "env.h"
#include "libft.h"
#include <stdlib.h>
#include "shell.h"
#include <stdio.h>
#include "exit_status.h"
Functions
int builtin_export (t_ms_data *data)
static void print_env (t_env *env)
static void add_env (t_ms_data *data)
Function Documentation
add_env()
static void add_env (t_ms_data * data) static
Definition at line 70 of file export.c.
{
    int     i;
    char    *key;
    char    *curr_arg;
    i = 0;
    key = NULL;
    curr_arg = NULL;
    while (data->args[++i])
    {
        if (ft_strchr(data->args[i], '='))
        {
            curr_arg = data->args[i];
            key = ft_strcdup(curr_arg, '=');
            set_env(&data->envp, key, \
                    ft_strchr(curr_arg, '=') + 1);
            free(key);
        }
        else
        {
            curr_arg = data->args[i];
            key = curr_arg;
            set_env(&data->envp, key, "");
        }
    }
}
References s_ms_data::args, s_ms_data::envp, ft_strcdup(), ft_strchr(), and set_env().
Referenced by builtin_export().
builtin_export()
int builtin_export (t_ms_data * data)
Definition at line 30 of file export.c.
{
    if (data->args == NULL || data->args[1] == NULL)
    {
        print_env(data->envp);
        return (EXIT_SUCCESS);
    }
    if (ft_strcmp(data->args[1], "-p") != 0 && data->args[1][0] == '-')
    {
        exit_status_handler(data, INVALID_OPTION, \
                ft_strjoin("export: ", data->args[1]));
        ft_putendl_fd("export: usage: export [-p]" \
                "[name[=value] ...] or export -p", STDERR_FILENO);
        return (INVALID_OPTION);
    }
    else if (ft_strcmp(data->args[1], "-p") == 0)
    {
        print_env(data->envp);
        return (EXIT_SUCCESS);
    }
    add_env(data);
    return (EXIT_SUCCESS);
}
References add_env(), s_ms_data::args, s_ms_data::envp, exit_status_handler(), EXIT_SUCCESS, ft_putendl_fd(), ft_strcmp(), ft_strjoin(), INVALID_OPTION, and print_env().
Referenced by execute().
print_env()
static void print_env (t_env * env) static
Definition at line 54 of file export.c.
{
    t_env   *curr_node;
    curr_node = env;
    while (curr_node)
    {
        if (!ft_strcmp(curr_node->value, ""))
            ft_printf("declare -x %s\n", curr_node->key);
        else
            ft_printf("declare -x %s=\"%s\"\n", \
                curr_node->key, curr_node->value);
        curr_node = curr_node->next;
    }
}
References ft_printf(), ft_strcmp(), s_env::key, s_env::next, and s_env::value.
Referenced by builtin_export().