maxishell: /github/workspace/lib/libft/src/ft_isdigit.c File Reference
ft_isdigit.c File Reference
Functions
int ft_isdigit (int c)
Function Documentation
ft_isdigit()
int ft_isdigit (int c)
Definition at line 13 of file ft_isdigit.c.
{
    return (c >= '0' && c <= '9');
}
Referenced by ft_is_double(), ft_is_num(), ft_isalnum(), ft_isnumber(), tmp_adj(), and token_adj().