maxishell: /github/workspace/lib/libft/src/ft_print_unsigned_dec.c File Reference
ft_print_unsigned_dec.c File Reference
#include "libft.h"
Functions
int ft_num_len (unsigned int num)
char * ft_uitoa (unsigned int n)
int ft_print_unsigned_dec (unsigned int n)
Function Documentation
ft_num_len()
int ft_num_len (unsigned int num)
Definition at line 15 of file ft_print_unsigned_dec.c.
{
    int len;
    len = 0;
    while (num != 0)
    {
        len++;
        num = num / 10;
    }
    return (len);
}
Referenced by ft_uitoa().
ft_print_unsigned_dec()
int ft_print_unsigned_dec (unsigned int n)
Definition at line 47 of file ft_print_unsigned_dec.c.
{
    int     count;
    char    *num;
    count = 0;
    if (n == 0)
        count += write(1, "0", 1);
    else
    {
        num = ft_uitoa(n);
        count += ft_print_str(num);
        free(num);
    }
    return (count);
}
References ft_print_str(), and ft_uitoa().
Referenced by ft_formatssssss().
ft_uitoa()
char * ft_uitoa (unsigned int n)
Definition at line 28 of file ft_print_unsigned_dec.c.
{
    char    *num;
    int     len;
    len = ft_num_len(n);
    num = (char *)malloc(sizeof(char) * (len + 1));
    if (!num)
        return (0);
    num[len] = '\0';
    while (n != 0)
    {
        num[len - 1] = n % 10 + 48;
        n = n / 10;
        len--;
    }
    return (num);
}
References ft_num_len().
Referenced by ft_print_unsigned_dec().