maxishell: /github/workspace/lib/libft/src/ft_printf.c File Reference
ft_printf.c File Reference
#include "libft.h"
Functions
int ft_formatssssss (va_list args, const char format)
int ft_printf (const char *str,...)
Function Documentation
ft_formatssssss()
int ft_formatssssss (va_list args, const char format)
Definition at line 15 of file ft_printf.c.
{
    int len;
    len = 0;
    if (format == 'c')
        len += ft_print_char(va_arg(args, int));
    else if (format == 's')
        len += ft_print_str(va_arg(args, char *));
    else if (format == 'p')
        len += ft_print_ptr(va_arg(args, unsigned long long));
    else if (format == 'd' || format == 'i')
        len += ft_print_int(va_arg(args, int));
    else if (format == 'u')
        len += ft_print_unsigned_dec(va_arg(args, unsigned int));
    else if (format == 'x' || format == 'X')
        len += ft_print_unsigned_hex(va_arg(args, unsigned int), format);
    else if (format == '%')
        len += ft_print_percent();
    return (len);
}
References ft_print_char(), ft_print_int(), ft_print_percent(), ft_print_ptr(), ft_print_str(), ft_print_unsigned_dec(), and ft_print_unsigned_hex().
Referenced by ft_printf().
ft_printf()
int ft_printf (const char * str, ...)
Definition at line 37 of file ft_printf.c.
{
    int     i;
    va_list args;
    int     len;
    i = 0;
    len = 0;
    va_start(args, str);
    while (str[i])
    {
        if (str[i] == '%')
        {
            len += ft_formatssssss(args, str[i + 1]);
            i++;
        }
        else
            len += ft_print_char(str[i]);
        i++;
    }
    va_end(args);
    return (len);
}
References ft_formatssssss(), and ft_print_char().
Referenced by append_word_if_valid(), env_tests(), ft_print_2d_arr(), initialise(), input_error_checks(), main(), new_process(), pipe_tests(), print_ast_args(), print_ast_node(), print_env(), print_env_stack(), print_maxishell(), print_stack(), print_t_env(), print_tokens(), signal_reset_prompt(), test_get_env(), test_init_env(), test_set_env(), and test_unset_env().