maxishell: /github/workspace/lib/libft/src/ft_strcmp.c File Reference
ft_strcmp.c File Reference
#include "libft.h"
Functions
int ft_strcmp (const char *s1, const char *s2)
Function Documentation
ft_strcmp()
int ft_strcmp (const char * s1, const char * s2)
Definition at line 24 of file ft_strcmp.c.
{
    while (*s1 != '\0' || *s2 != '\0')
    {
        if (*s1 != *s2)
            return ((unsigned char)*s1 - (unsigned char)*s2);
        s1++;
        s2++;
    }
    return (0);
}
Referenced by builtin_echo(), builtin_env(), builtin_export(), execute(), exit_status_adj(), expand_env_and_loc_var(), get_env(), get_shell_variable(), open_file(), open_tmp_file(), print_env(), set_env(), set_shell_var(), str_start_adj(), test_get_env(), test_set_env(), test_unset_env(), unset_env(), and write_heredoc_lines().