maxishell: /github/workspace/lib/libft/src/ft_print_char.c File Reference
ft_print_char.c File Reference
#include "libft.h"
Functions
int ft_print_char (int c)
Function Documentation
ft_print_char()
int ft_print_char (int c)
Definition at line 15 of file ft_print_char.c.
{
    ft_putchar_fd(c, 1);
    return (1);
}
References ft_putchar_fd().
Referenced by ft_formatssssss(), and ft_printf().