maxishell: /github/workspace/lib/libft/src/ft_free_2d_arr.c File Reference
ft_free_2d_arr.c File Reference
#include "libft.h"
Functions
void ft_free_2d_arr (char **arr)
Function Documentation
ft_free_2d_arr()
void ft_free_2d_arr (char ** arr)
Definition at line 15 of file ft_free_2d_arr.c.
{
    int i;
    if (!arr)
        return ;
    i = -1;
    while (arr[++i] != NULL)
        free(arr[i]);
    free(arr);
}
Referenced by builtin_exit(), cleanup_exit_resources(), ft_find_path(), process_and_reassemble(), and split_loc_vars().