maxishell: /github/workspace/lib/libft/src/ft_remove_quotes.c File Reference
ft_remove_quotes.c File Reference
#include "libft.h"
Functions
char * ft_remove_quotes (char *str, char quote_type)
Function Documentation
ft_remove_quotes()
char * ft_remove_quotes (char * str, char quote_type)
Definition at line 15 of file ft_remove_quotes.c.
{
    int     len;
    char    *new_str;
    len = ft_strlen(str);
    new_str = NULL;
    if (len > 1 && str[0] == quote_type && str[len - 1] == quote_type)
    {
        new_str = ft_strndup(str + 1, len - 2);
        return (new_str);
    }
    return (ft_strdup(str));
}
References ft_strdup(), ft_strlen(), and ft_strndup().
Referenced by handle_add_set_shell_variable(), and post_process_command_args().