maxishell: /github/workspace/lib/libft/src/ft_split.c File Reference
ft_split.c File Reference
#include "libft.h"
Functions
static int count_words (const char *s, char c)
static char * strndup (const char *s, size_t n)
static void split_into_words (char **result, const char *s, char c)
char ** ft_split (const char *s, char c)
Function Documentation
count_words()
static int count_words (const char * s, char c) static
Definition at line 32 of file ft_split.c.
{
    int count;
    int in_word;
    count = 0;
    in_word = 0;
    while (*s)
    {
        if (*s != c)
        {
            if (!in_word)
            {
                in_word = 1;
                count++;
            }
        }
        else
            in_word = 0;
        s++;
    }
    return (count);
}
Referenced by ft_split().
ft_split()
char ** ft_split (const char * s, char c)
Definition at line 95 of file ft_split.c.
{
    char    **result;
    int     word_count;
    if (!s)
        return (NULL);
    word_count = count_words(s, c);
    result = malloc(sizeof(char *) * (word_count + 1));
    if (!result)
        return (NULL);
    split_into_words(result, s, c);
    return (result);
}
References count_words(), and split_into_words().
Referenced by builtin_pipe_test(), ft_find_path(), main_loop(), process_and_reassemble(), and split_loc_vars().
split_into_words()
static void split_into_words (char ** result, const char * s, char c) static
Definition at line 68 of file ft_split.c.
{
    int         i;
    int         in_word;
    const char  *start;
    i = 0;
    in_word = 0;
    while (*s)
    {
        if (*s != c && !in_word)
        {
            start = s;
            in_word = 1;
        }
        else if (*s == c && in_word)
        {
            result[i++] = strndup(start, s - start);
            in_word = 0;
        }
        s++;
    }
    if (in_word)
        result[i++] = strndup(start, s - start);
    result[i] = NULL;
}
References strndup().
Referenced by ft_split().
strndup()
static char * strndup (const char * s, size_t n) static
Definition at line 56 of file ft_split.c.
{
    char    *dup;
    dup = malloc(n + 1);
    if (!dup)
        return (NULL);
    ft_memcpy(dup, s, n);
    dup[n] = '\0';
    return (dup);
}
References ft_memcpy().
Referenced by split_into_words().