maxishell: /github/workspace/lib/libft/src/ft_substr.c File Reference
ft_substr.c File Reference
#include "libft.h"
Functions
char * ft_substr (char const *s, unsigned int start, size_t len)
Function Documentation
ft_substr()
char * ft_substr (char const * s, unsigned int start, size_t len)
Definition at line 27 of file ft_substr.c.
{
    char    *new_str;
    size_t  i;
    size_t  j;
    size_t  size;
    size = ft_strlen(s) - start;
    if (start > ft_strlen(s))
        size = 0;
    else if (size > len)
        size = len;
    new_str = (char *)malloc(size + 1);
    if (!s || !new_str)
        return (0);
    i = start;
    j = 0;
    while (i < ft_strlen(s) && j < len)
        new_str[j++] = s[i++];
    new_str[j] = '\0';
    return (new_str);
}
References ft_strlen().
Referenced by append_literal(), ev_loop(), expand_variable(), and post_process_command_args().