maxishell: /github/workspace/lib/libft/src/ft_strcat.c File Reference
ft_strcat.c File Reference
#include "libft.h"
Functions
char * ft_strcat (char *dest, char *src)
Function Documentation
ft_strcat()
char * ft_strcat (char * dest, char * src)
Definition at line 26 of file ft_strcat.c.
{
    int i;
    int j;
    i = 0;
    while (dest[i] != '\0')
        i++;
    j = 0;
    while (src[j] != '\0')
    {
        dest[i + j] = src[j];
        j++;
    }
    dest[i + j] = '\0';
    return (dest);
}
Referenced by assemble_result(), generate_prompt(), and token_adj().