maxishell: /github/workspace/lib/libft/src/ft_putendl_fd.c File Reference
ft_putendl_fd.c File Reference
#include "libft.h"
Functions
void ft_putendl_fd (char *s, int fd)
Function Documentation
ft_putendl_fd()
void ft_putendl_fd (char * s, int fd)
Definition at line 21 of file ft_putendl_fd.c.
{
    if (s)
    {
        ft_putstr_fd(s, fd);
        ft_putchar_fd('\n', fd);
    }
}
References ft_putchar_fd(), and ft_putstr_fd().
Referenced by builtin_exit(), builtin_export(), builtin_pwd(), ft_puterror(), and handle_exit().