maxishell: /github/workspace/lib/libft/src/ft_print_str.c File Reference
ft_print_str.c File Reference
#include "libft.h"
Functions
int ft_print_str (char *str)
Function Documentation
ft_print_str()
int ft_print_str (char * str)
Definition at line 15 of file ft_print_str.c.
{
    int len;
    len = 0;
    if (str == NULL)
    {
        ft_putstr_fd("(null)", 1);
        return (6);
    }
    while (*str)
    {
        ft_putchar_fd(*str++, 1);
        len++;
    }
    return (len);
}
References ft_putchar_fd(), and ft_putstr_fd().
Referenced by ft_formatssssss(), ft_print_int(), and ft_print_unsigned_dec().