maxishell: /github/workspace/lib/libft/src/ft_isalnum.c File Reference
ft_isalnum.c File Reference
#include "libft.h"
Functions
int ft_isalnum (int c)
Function Documentation
ft_isalnum()
int ft_isalnum (int c)
Definition at line 15 of file ft_isalnum.c.
{
    return (ft_isalpha(c) || ft_isdigit(c));
}
References ft_isalpha(), and ft_isdigit().
Referenced by ev_loop(), and handle_local_vars().