maxishell: /github/workspace/lib/libft/src/ft_strndup.c File Reference
ft_strndup.c File Reference
#include "libft.h"
Functions
char * ft_strndup (const char *s, size_t n)
Function Documentation
ft_strndup()
char * ft_strndup (const char * s, size_t n)
Definition at line 23 of file ft_strndup.c.
{
    size_t  len;
    char    *new;
    len = ft_strlen(s);
    if (!s)
        return (NULL);
    new = malloc((n + 1) * sizeof(char));
    if (!new)
        return (NULL);
    if (n > len)
        n = len;
    ft_strlcpy(new, s, n + 1);
    return (new);
}
References ft_strlcpy(), and ft_strlen().
Referenced by add_env_node(), append_word_if_valid(), final_quote_removal(), ft_add_segment(), ft_remove_all_edge_quotes(), and ft_remove_quotes().