maxishell: /github/workspace/lib/libft/src/ft_strdup.c File Reference
ft_strdup.c File Reference
#include "libft.h"
Functions
char * ft_strdup (const char *s)
Function Documentation
ft_strdup()
char * ft_strdup (const char * s)
Definition at line 23 of file ft_strdup.c.
{
    size_t  n;
    char    *new;
    n = ft_strlen(s);
    if (!s)
        return (NULL);
    new = malloc((n + 1) * sizeof(char));
    if (!new)
        return (NULL);
    ft_strlcpy(new, s, n + 1);
    return (new);
}
References ft_strlcpy(), and ft_strlen().
Referenced by add_env_node(), add_new_env(), add_shell_var_node(), append_expanded_var(), child_process(), create_pipe_node(), create_redir_node(), expand_env_and_loc_var(), expand_variable(), finalize_token(), ft_find_path(), ft_itoa(), ft_remove_all_edge_quotes(), ft_remove_quotes(), get_env_variable(), get_exit_status(), list_to_array(), new_token(), process_argument(), redirect_here_doc(), set_command_args(), set_env(), set_shell_var(), split_loc_vars(), tmp_adj(), and token_adj().