maxishell: /github/workspace/lib/libft/src/ft_strjoin_free.c File Reference
ft_strjoin_free.c File Reference
#include "libft.h"
Functions
char * ft_strjoin_free (char *s1, char *s2)
Function Documentation
ft_strjoin_free()
char * ft_strjoin_free (char * s1, char * s2)
Definition at line 15 of file ft_strjoin_free.c.
{
    char    *result;
    if (!s1 || !s2)
        return (NULL);
    result = ft_strjoin(s1, s2);
    free(s1);
    return (result);
}
References ft_strjoin().
Referenced by append_expanded_var(), ev_loop(), and expand_variable().