maxishell: /github/workspace/lib/libft/src/ft_print_ptr.c File Reference
ft_print_ptr.c File Reference
#include "libft.h"
Functions
int ft_ptr_len (uintptr_t num)
void ft_put_ptr (uintptr_t num)
int ft_print_ptr (unsigned long long ptr)
Function Documentation
ft_print_ptr()
int ft_print_ptr (unsigned long long ptr)
Definition at line 44 of file ft_print_ptr.c.
{
    int print_length;
    print_length = 0;
    if (ptr == 0)
        print_length += write(1, "(nil)", 5);
    else
    {
        print_length += write(1, "0x", 2);
        ft_put_ptr(ptr);
        print_length += ft_ptr_len(ptr);
    }
    return (print_length);
}
References ft_ptr_len(), and ft_put_ptr().
Referenced by ft_formatssssss().
ft_ptr_len()
int ft_ptr_len (uintptr_t num)
Definition at line 15 of file ft_print_ptr.c.
{
    int len;
    len = 0;
    while (num != 0)
    {
        len++;
        num = num / 16;
    }
    return (len);
}
Referenced by ft_print_ptr().
ft_put_ptr()
void ft_put_ptr (uintptr_t num)
Definition at line 28 of file ft_print_ptr.c.
{
    if (num >= 16)
    {
        ft_put_ptr(num / 16);
        ft_put_ptr(num % 16);
    }
    else
    {
        if (num <= 9)
            ft_putchar_fd((num + '0'), 1);
        else
            ft_putchar_fd((num - 10 + 'a'), 1);
    }
}
References ft_put_ptr(), and ft_putchar_fd().
Referenced by ft_print_ptr(), and ft_put_ptr().