maxishell: /github/workspace/lib/libft/src/ft_putstr_fd.c File Reference
ft_putstr_fd.c File Reference
#include "libft.h"
Functions
void ft_putstr_fd (char *s, int fd)
Function Documentation
ft_putstr_fd()
void ft_putstr_fd (char * s, int fd)
Definition at line 20 of file ft_putstr_fd.c.
{
    if (s)
        write(fd, s, ft_strlen(s));
}
References ft_strlen().
Referenced by builtin_echo(), builtin_env(), ft_print_str(), ft_putendl_fd(), ft_puterror(), ft_putnbr_fd(), handle_exec_errors(), and handle_get_shell_variable().