maxishell: /github/workspace/lib/libft/src/ft_itoa.c File Reference
ft_itoa.c File Reference
#include "libft.h"
Functions
static int count_digits (int n)
char * ft_itoa (int n)
Function Documentation
count_digits()
static int count_digits (int n) static
Definition at line 23 of file ft_itoa.c.
{
    int count;
    count = 0;
    if (n <= 0)
        count = 1;
    else
        count = 0;
    while (n != 0)
    {
        count++;
        n /= 10;
    }
    return (count);
}
Referenced by ft_itoa().
ft_itoa()
char * ft_itoa (int n)
Definition at line 40 of file ft_itoa.c.
{
    int     len;
    char    *str;
    if (n == INT_MIN)
        return (ft_strdup("-2147483648"));
    if (n == 0)
        return (ft_strdup("0"));
    len = count_digits(n);
    str = (char *)malloc(len + 1);
    if (!str)
        return (NULL);
    str[len--] = '\0';
    if (n < 0)
    {
        str[0] = '-';
        n = -n;
    }
    while (n)
    {
        str[len--] = n % 10 + '0';
        n /= 10;
    }
    return (str);
}
References count_digits(), and ft_strdup().
Referenced by builtin_env(), exit_status_handler(), expand_env_and_loc_var(), ft_print_int(), handle_exit(), and shell_variable_update().