maxishell: /github/workspace/lib/libft/src/ft_strjoin.c File Reference
ft_strjoin.c File Reference
#include "libft.h"
Functions
char * ft_strjoin (char const *s1, char const *s2)
Function Documentation
ft_strjoin()
char * ft_strjoin (char const * s1, char const * s2)
Definition at line 23 of file ft_strjoin.c.
{
    size_t  len;
    char    *pt;
    char    *result;
    if (!s1 || !s2)
        return (NULL);
    len = ft_strlen(s1) + ft_strlen (s2) + 1;
    if (len == 0)
        return (NULL);
    pt = (char *)malloc(sizeof(char) * len);
    if (!pt)
        return (NULL);
    result = pt;
    while (*s1)
        *pt++ = *s1++;
    while (*s2)
        *pt++ = *s2++;
    *pt = '\0';
    return (result);
}
References ft_strlen().
Referenced by append_literal(), builtin_cd(), builtin_export(), env_to_array(), generate_prompt_string(), handle_numeric_error(), process_argument(), and relative_path_handle().