maxishell: /github/workspace/lib/libft/src/ft_print_unsigned_hex.c File Reference
ft_print_unsigned_hex.c File Reference
#include "libft.h"
Functions
int ft_hex_len (unsigned int n)
void ft_put_hex (unsigned int n, const char upper_lower)
int ft_print_unsigned_hex (unsigned int n, const char upper_lower)
Function Documentation
ft_hex_len()
int ft_hex_len (unsigned int n)
Definition at line 15 of file ft_print_unsigned_hex.c.
{
    int len;
    len = 0;
    while (n != 0)
    {
        n = n / 16;
        len++;
    }
    return (len);
}
Referenced by ft_print_unsigned_hex().
ft_print_unsigned_hex()
int ft_print_unsigned_hex (unsigned int n, const char upper_lower)
Definition at line 49 of file ft_print_unsigned_hex.c.
{
    if (n == 0)
    {
        ft_putchar_fd('0', 1);
        return (1);
    }
    else
        ft_put_hex(n, upper_lower);
    return (ft_hex_len(n));
}
References ft_hex_len(), ft_put_hex(), and ft_putchar_fd().
Referenced by ft_formatssssss().
ft_put_hex()
void ft_put_hex (unsigned int n, const char upper_lower)
Definition at line 28 of file ft_print_unsigned_hex.c.
{
    if (n >= 16)
    {
        ft_put_hex(n / 16, upper_lower);
        ft_put_hex(n % 16, upper_lower);
    }
    else
    {
        if (n <= 9)
            ft_putchar_fd((n + '0'), 1);
        else
        {
            if (upper_lower == 'x')
                ft_putchar_fd((n - 10 + 'a'), 1);
            if (upper_lower == 'X')
                ft_putchar_fd((n - 10 + 'A'), 1);
        }
    }
}
References ft_put_hex(), and ft_putchar_fd().
Referenced by ft_print_unsigned_hex(), and ft_put_hex().