maxishell: /github/workspace/lib/libft/src/ft_print_2d_arr.c File Reference
ft_print_2d_arr.c File Reference
#include "libft.h"
Functions
void ft_print_2d_arr (char **arr, char *name)
Function Documentation
ft_print_2d_arr()
void ft_print_2d_arr (char ** arr, char * name)
Definition at line 15 of file ft_print_2d_arr.c.
{
    int i;
    i = 0;
    if (ft_strlen(name) > 0)
        ft_printf(GRN"-----         %s[]        -----\n"RESET, name);
    while (arr && arr[i])
    {
        ft_printf(GRN"arr[%d]:  %s      at add: %p  \n"RESET, \
            i, arr[i], arr[i]);
        i++;
    }
}
References ft_printf(), ft_strlen(), GRN, and RESET.
Referenced by final_quote_removal().