maxishell: /github/workspace/src/parser/heredoc.c File Reference
heredoc.c File Reference
#include "tokens.h"
Functions
char * check_heredoc (char *line)
char * heredoc (char *eof)
Function Documentation
check_heredoc()
char * check_heredoc (char * line)
Definition at line 15 of file heredoc.c.
{
    char    **parsed;
    parsed = ft_split(line, ' ');
    if (!ft_strcmp(parsed[0], "cat") && !ft_strcmp(parsed[1], "<<"))
        return (heredoc("EOF"));
    else
        return (line);
}
References ft_split(), ft_strcmp(), and heredoc().
heredoc()
char * heredoc (char * eof)
Definition at line 26 of file heredoc.c.
{
    char    *line;
    char    *comb;
    comb = "";
    while (1)
    {
        line = readline("heredoc>");
        if (!ft_strcmp(line, eof))
            return (comb);
        comb = ft_strjoin(ft_strjoin(comb, line), "\n");
        free(line);
    }
}
References ft_strcmp(), and ft_strjoin().
Referenced by check_heredoc().