maxishell: /github/workspace/src/utils/initialise.c File Reference
initialise.c File Reference
#include "tokens.h"
#include "env.h"
#include "signals.h"
Functions
void init_ms_data (t_ms_data *data, char **argv, char **envp)
void initialise (int argc, char **argv)
Function Documentation
init_ms_data()
void init_ms_data (t_ms_data * data, char ** argv, char ** envp)
Definition at line 20 of file initialise.c.
{
    (void)argv;
    data->args = NULL;
    data->envp = NULL;
    init_env(&data->envp, envp);
    data->shell_variables = NULL;
    handle_add_set_shell_variable(&data->shell_variables, "_=/usr/bin/env");
    set_shell_var(&data->shell_variables, "?", "0");
    data->current_dir = getcwd(NULL, 0);
    data->exit_status = 0;
    data->std_in = -1;
    data->std_out = -1;
    data->std_err = 2;
}
References s_ms_data::args, s_ms_data::current_dir, s_ms_data::envp, s_ms_data::exit_status, handle_add_set_shell_variable(), init_env(), set_shell_var(), s_ms_data::shell_variables, s_ms_data::std_err, s_ms_data::std_in, and s_ms_data::std_out.
Referenced by main().
initialise()
void initialise (int argc, char ** argv)
Definition at line 36 of file initialise.c.
{
    if (argc > 1)
    {
        ft_printf("Usage: %s\n", argv[0]);
        exit(EXIT_FAILURE);
    }
    read_history(HISTORY_PATH);
}
References EXIT_FAILURE, ft_printf(), and HISTORY_PATH.
Referenced by main().