maxishell: /github/workspace/src/check_tokenise/input_checker.c File Reference
input_checker.c File Reference
#include "tokens.h"
Functions
void free_op_strings (t_loop_data *data, char *tail, char *new)
int check_operators (t_loop_data *loop_data)
int check_redirections (const char *str)
int check_open_quotes (const char *str)
int input_error_checks (t_loop_data *loop_data)
Function Documentation
check_open_quotes()
int check_open_quotes (const char * str)
Definition at line 76 of file input_checker.c.
{
    int single_quote_open;
    int double_quote_open;
    single_quote_open = 0;
    double_quote_open = 0;
    while (*str)
    {
        if (*str == '\'' && !double_quote_open)
        {
            single_quote_open = !single_quote_open;
        }
        else if (*str == '"' && !single_quote_open)
            double_quote_open = !double_quote_open;
        str++;
    }
    return (single_quote_open || double_quote_open);
}
Referenced by input_error_checks().
check_operators()
int check_operators (t_loop_data * loop_data)
Definition at line 22 of file input_checker.c.
{
    char    *input;
    char    *tail;
    char    *new_input;
    char    *final_input;
    input = loop_data->trimmed_input;
    if (*input == '&' || *input == '|')
        return (1);
    while (*input)
    {
        if (*input == '|' && *(input + 1) == '\0')
        {
            tail = readline("> ");
            if (tail == NULL)
                break ;
            new_input = ft_strcat_const(loop_data->trimmed_input, " ");
            final_input = ft_strcat_const(new_input, tail);
            free_op_strings(loop_data, tail, new_input);
            loop_data->trimmed_input = final_input;
            free(final_input);
            break ;
        }
        input++;
    }
    return (0);
}
References free_op_strings(), ft_strcat_const(), and s_loop_data::trimmed_input.
Referenced by input_error_checks().
check_redirections()
int check_redirections (const char * str)
Definition at line 51 of file input_checker.c.
{
    int single_quotes;
    int double_quotes;
    single_quotes = 0;
    double_quotes = 0;
    while (*str)
    {
        if (*str == '\'')
            single_quotes++;
        if (*str == '\"')
            double_quotes++;
        if ((!(single_quotes % 2) && !(double_quotes % 2))
            && (*str == '>' || *str == '<'))
        {
            if (!valid_operator(&str))
                return (1);
        }
        else
            str++;
    }
    return (0);
}
References valid_operator().
Referenced by input_error_checks().
free_op_strings()
void free_op_strings (t_loop_data * data, char * tail, char * new)
Definition at line 15 of file input_checker.c.
{
    free(data->trimmed_input);
    free(new);
    free(tail);
}
References s_loop_data::trimmed_input.
Referenced by check_operators().
input_error_checks()
int input_error_checks (t_loop_data * loop_data)
Definition at line 96 of file input_checker.c.
{
    const char  *str = loop_data->trimmed_input;
    if (check_redirections(str))
        ft_printf("Input error: invalid redirection.\n");
    else if (check_operators(loop_data))
        ft_printf("Input error: invalid operator.\n");
    else if (check_open_quotes(str))
        ft_printf("Input error: open quote.\n");
    else
        return (0);
    return (1);
}
References check_open_quotes(), check_operators(), check_redirections(), ft_printf(), and s_loop_data::trimmed_input.
Referenced by main_loop().