maxishell: /github/workspace/lib/libft/inc/libft.h File Reference
libft.h File Reference
#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>
#include <limits.h>
#include <unistd.h>
#include <stdarg.h>
#include <signal.h>
#include <stdbool.h>
#include <math.h>
Macros
#define BUFFER_SIZE 32
#define TRUE 1
#define FALSE 0
#define STDIN 0
#define STDOUT 1
#define STDERR 2
#define RESET "\033[0m"
#define BLK "\033[0;30m"
#define RED "\033[0;31m"
#define GRN "\033[0;32m"
#define YEL "\033[0;33m"
#define BLU "\033[0;34m"
#define MAG "\033[0;35m"
#define CYA "\033[0;36m"
#define WHI "\033[0;37m"
#define B_BLK "\033[1;30m"
#define B_RED "\033[1;31m"
#define B_GRN "\033[1;32m"
#define B_YEL "\033[1;33m"
#define B_BLU "\033[1;34m"
#define B_MAG "\033[1;35m"
#define B_CYA "\033[1;36m"
#define B_WHI "\033[1;37m"
Functions
int ft_abs (int n)
int ft_isalpha (int c)
int ft_isdigit (int c)
int ft_isalnum (int c)
int ft_isascii (int c)
int ft_isprint (int c)
int ft_toupper (int c)
int ft_tolower (int c)
int ft_print_int (int n)
int ft_print_char (int c)
int ft_print_percent (void)
int ft_print_str (char *str)
int list_len_char (char a[])
int list_len_str (char *a[])
int ft_atoi (const char *str)
int ft_is_num (const char *n)
int ft_ptr_len (uintptr_t num)
int ft_len_2d_arr (char **array)
int ft_is_double (const char *n)
int isnum_from_str (const char *str)
int ft_printf (const char *format,...)
int find_max_in_list (int a[], int size)
int ft_print_ptr (unsigned long long ptr)
int ft_print_unsigned_dec (unsigned int n)
int list_repeat_check_int (int a[], int size)
int ft_count_bits (unsigned char current_char)
int ft_strcmp (const char *s1, const char *s2)
int list_repeat_check_str (char *a[], int size)
int ft_strncmp (const char *s1, const char *s2, size_t n)
int ft_memcmp (const void *s1, const void *s2, size_t n)
int ft_print_unsigned_hex (unsigned int num, const char format)
char * ft_itoa (int n)
char * ft_strdup (const char *s)
char * ft_get_next_line (int fd)
char * ft_strchr (const char *s, int c)
char * ft_strcat (char *dest, char *src)
char * ft_strrchr (const char *s, int c)
char ** ft_split (char const *s, char c)
char * ft_strndup (const char *s, size_t n)
char * ft_strjoin_free (char *s1, char *s2)
char * ft_strcpy (char *dest, const char *src)
char * ft_strjoin (char const *s1, char const *s2)
char * ft_strtrim (char const *s1, char const *set)
char * ft_remove_quotes (char *str, char quote_type)
char * ft_strstr (const char *big, const char *little)
char * ft_strcat_const (const char *dest, const char *src)
char * ft_strmapi (char const *s, char(*f)(unsigned int, char))
char * ft_substr (char const *s, unsigned int start, size_t len)
char ** ft_realloc_array (char **array, int old_size, int new_size)
char * ft_strnstr (const char *haystack, const char *needle, size_t len)
void ft_put_ptr (uintptr_t num)
void ft_free_2d_arr (char **arr)
void ft_bzero (void *s, size_t n)
void ft_putnbr_fd (int n, int fd)
void ft_putchar_fd (char c, int fd)
void ft_putstr_fd (char *s, int fd)
void ft_putendl_fd (char *s, int fd)
void * ft_memset (void *s, int c, size_t n)
void * ft_calloc (size_t count, size_t size)
void ft_print_2d_arr (char **arr, char *name)
void * ft_memchr (const void *s, int c, size_t n)
void * ft_memcpy (void *dest, const void *src, size_t n)
void * ft_memmove (void *dest, const void *src, size_t n)
void ft_striteri (char *s, void(*f)(unsigned int, char *))
size_t ft_strlen (const char *s)
size_t ft_strlcpy (char *dest, const char *src, size_t size)
size_t ft_strlcat (char *dest, const char *src, size_t size)
double ft_atof (const char *str)
long ft_atol (const char *nptr)
const char * ft_exclude_delimiters (const char *str, char *delims)
Macro Definition Documentation
B_BLK
#define B_BLK "\033[1;30m"
Definition at line 122 of file libft.h.
B_BLU
#define B_BLU "\033[1;34m"
Definition at line 126 of file libft.h.
B_CYA
#define B_CYA "\033[1;36m"
Definition at line 128 of file libft.h.
B_GRN
#define B_GRN "\033[1;32m"
Definition at line 124 of file libft.h.
B_MAG
#define B_MAG "\033[1;35m"
Definition at line 127 of file libft.h.
B_RED
#define B_RED "\033[1;31m"
Definition at line 123 of file libft.h.
B_WHI
#define B_WHI "\033[1;37m"
Definition at line 129 of file libft.h.
B_YEL
#define B_YEL "\033[1;33m"
Definition at line 125 of file libft.h.
BLK
#define BLK "\033[0;30m"
Definition at line 113 of file libft.h.
BLU
#define BLU "\033[0;34m"
Definition at line 117 of file libft.h.
BUFFER_SIZE
#define BUFFER_SIZE 32
Definition at line 25 of file libft.h.
CYA
#define CYA "\033[0;36m"
Definition at line 119 of file libft.h.
FALSE
#define FALSE 0
Definition at line 105 of file libft.h.
GRN
#define GRN "\033[0;32m"
Definition at line 115 of file libft.h.
MAG
#define MAG "\033[0;35m"
Definition at line 118 of file libft.h.
RED
#define RED "\033[0;31m"
Definition at line 114 of file libft.h.
RESET
#define RESET "\033[0m"
Definition at line 111 of file libft.h.
STDERR
#define STDERR 2
Definition at line 109 of file libft.h.
STDIN
#define STDIN 0
Definition at line 107 of file libft.h.
STDOUT
#define STDOUT 1
Definition at line 108 of file libft.h.
TRUE
#define TRUE 1
Definition at line 104 of file libft.h.
WHI
#define WHI "\033[0;37m"
Definition at line 120 of file libft.h.
YEL
#define YEL "\033[0;33m"
Definition at line 116 of file libft.h.
Function Documentation
find_max_in_list()
int find_max_in_list (int a[], int size)
Definition at line 15 of file find_max_in_list.c.
{
    int max;
    int i;
    max = INT_MIN;
    i = 0;
    while (i < size)
    {
        if (a[i] > max)
            max = a[i];
        i++;
    }
    return (max);
}
ft_abs()
int ft_abs (int n)
Definition at line 15 of file ft_abs.c.
{
    if (n < 0)
        return (-n);
    return (n);
}
ft_atof()
double ft_atof (const char * str)
Definition at line 15 of file ft_atof.c.
{
    double  res;
    double  neg;
    double  divider;
    size_t  i;
    divider = 0.1;
    res = 0;
    neg = 1;
    i = -1;
    while (str[i] < '0' || str[i] > '9')
        if (str[i++] == '-')
            neg = -1;
    while (str[i] >= '0' && str[i] <= '9')
    {
        res = res * 10 + str[i++] - 48;
    }
    if (str[i] == '.' || str[i] == ',')
        i++;
    while (str[i] >= '0' && str[i] <= '9')
    {
        res = res + (str[i] - 48) * divider;
        divider /= 10;
        i++;
    }
    return (res * neg);
}
ft_atoi()
int ft_atoi (const char * str)
Referenced by builtin_exit().
ft_atol()
long ft_atol (const char * nptr)
Definition at line 15 of file ft_atol.c.
{
    int     i;
    int     neg;
    long    res;
    i = 0;
    neg = 1;
    res = 0;
    while (nptr[i] == '\t' || nptr[i] == '\v' || nptr[i] == '\n'
        || nptr[i] == '\f' || nptr[i] == '\r' || nptr[i] == ' ')
        i++;
    if (nptr[i] == '-' || nptr[i] == '+')
    {
        if (nptr[i] == '-')
            neg = -neg;
        i++;
    }
    while (nptr[i] >= '0' && nptr[i] <= '9')
        res = res * 10 + (nptr[i++] - 48);
    return (res * neg);
}
ft_bzero()
void ft_bzero (void * s, size_t n)
Definition at line 21 of file ft_bzero.c.
{
    char    *p;
    p = s;
    while (n--)
        *p++ = '\0';
}
ft_calloc()
void * ft_calloc (size_t count, size_t size)
Definition at line 23 of file ft_calloc.c.
{
    void    *ptr;
    if (size != 0 && count > SIZE_MAX / size)
        return (NULL);
    ptr = malloc(count * size);
    if (!ptr)
        return (NULL);
    ft_memset(ptr, 0, count * size);
    return (ptr);
}
References ft_memset().
ft_count_bits()
int ft_count_bits (unsigned char current_char)
Definition at line 13 of file ft_count_bits.c.
{
    int i;
    i = 0;
    while (current_char)
    {
        i += 1;
        current_char >>= 1;
    }
    return (i);
}
ft_exclude_delimiters()
const char * ft_exclude_delimiters (const char * str, char * delims)
Definition at line 15 of file ft_exclude_delimiters.c.
{
    while (*str && (ft_strchr(delims, *str) != NULL))
        str++;
    return (str);
}
References ft_strchr().
Referenced by valid_operator().
ft_free_2d_arr()
void ft_free_2d_arr (char ** arr)
Definition at line 15 of file ft_free_2d_arr.c.
{
    int i;
    if (!arr)
        return ;
    i = -1;
    while (arr[++i] != NULL)
        free(arr[i]);
    free(arr);
}
ft_get_next_line()
char * ft_get_next_line (int fd)
ft_is_double()
int ft_is_double (const char * n)
Definition at line 15 of file ft_is_double.c.
{
    unsigned long   i;
    int             p;
    i = 0;
    while (n[i] && (n[i] == '\t' || n[i] == '\n' || n[i] == '\v'
            || n[i] == '\f' || n[i] == '\r' || n[i] == ' '))
        i++;
    if (n[i] && (n[i] == '+' || n[i] == '-'))
        i++;
    if (!n[i])
        return (FALSE);
    p = FALSE;
    while (n[i])
    {
        if (!ft_isdigit(n[i]) && n[i] != '.' && n[i] != ',')
            return (FALSE);
        if ((n[i] == '.' || n[i] == ',') && p == TRUE)
            return (FALSE);
        if (n[i] == '.' || n[i] == ',')
            p = TRUE;
        i++;
    }
    return (TRUE);
}
References FALSE, ft_isdigit(), and TRUE.
ft_is_num()
int ft_is_num (const char * n)
Definition at line 15 of file ft_is_num.c.
{
    unsigned long   i;
    i = 0;
    while (n[i] && (n[i] == '\t' || n[i] == '\n' || n[i] == '\v'
            || n[i] == '\f' || n[i] == '\r' || n[i] == ' '))
        i++;
    if (n[i] && (n[i] == '+' || n[i] == '-'))
        i++;
    if (!n[i])
        return (FALSE);
    while (n[i])
    {
        if (!ft_isdigit(n[i]))
            return (FALSE);
        i++;
    }
    return (TRUE);
}
References FALSE, ft_isdigit(), and TRUE.
ft_isalnum()
int ft_isalnum (int c)
Definition at line 15 of file ft_isalnum.c.
{
    return (ft_isalpha(c) || ft_isdigit(c));
}
References ft_isalpha(), and ft_isdigit().
Referenced by ev_loop(), and handle_local_vars().
ft_isalpha()
int ft_isalpha (int c)
Definition at line 13 of file ft_isalpha.c.
{
    return ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'));
}
Referenced by ft_isalnum().
ft_isascii()
int ft_isascii (int c)
Definition at line 13 of file ft_isascii.c.
{
    return (c >= 0 && c <= 127);
}
ft_isdigit()
int ft_isdigit (int c)
Definition at line 13 of file ft_isdigit.c.
{
    return (c >= '0' && c <= '9');
}
Referenced by ft_is_double(), ft_is_num(), ft_isalnum(), ft_isnumber(), tmp_adj(), and token_adj().
ft_isprint()
int ft_isprint (int c)
Definition at line 13 of file ft_isprint.c.
{
    return (c >= ' ' && c <= '~');
}
ft_itoa()
char * ft_itoa (int n)
Definition at line 40 of file ft_itoa.c.
{
    int     len;
    char    *str;
    if (n == INT_MIN)
        return (ft_strdup("-2147483648"));
    if (n == 0)
        return (ft_strdup("0"));
    len = count_digits(n);
    str = (char *)malloc(len + 1);
    if (!str)
        return (NULL);
    str[len--] = '\0';
    if (n < 0)
    {
        str[0] = '-';
        n = -n;
    }
    while (n)
    {
        str[len--] = n % 10 + '0';
        n /= 10;
    }
    return (str);
}
References count_digits(), and ft_strdup().
Referenced by builtin_env(), ft_print_int(), set_shell_var_handler(), and shell_variable_update().
ft_len_2d_arr()
int ft_len_2d_arr (char ** array)
Definition at line 15 of file ft_len_2d_arr.c.
{
    int count;
    count = 0;
    while (array && array[count])
        count++;
    return (count);
}
Referenced by split_loc_vars().
ft_memchr()
void * ft_memchr (const void * s, int c, size_t n)
Definition at line 29 of file ft_memchr.c.
{
    const unsigned char *st;
    unsigned char       ct;
    st = s;
    ct = (unsigned char)c;
    while (n--)
    {
        if (*st == ct)
            return ((void *)st);
        st++;
    }
    return (NULL);
}
ft_memcmp()
int ft_memcmp (const void * s1, const void * s2, size_t n)
Definition at line 23 of file ft_memcmp.c.
{
    const unsigned char     *st1;
    const unsigned char     *st2;
    st1 = s1;
    st2 = s2;
    while (n--)
    {
        if (*st1 != *st2)
            return (*st1 - *st2);
        st1++;
        st2++;
    }
    return (0);
}
ft_memcpy()
void * ft_memcpy (void * dest, const void * src, size_t n)
Definition at line 22 of file ft_memcpy.c.
{
    char        *d;
    const char  *s;
    if (!dest && !src)
        return (NULL);
    s = src;
    d = dest;
    while (n--)
        *d++ = *s++;
    return (dest);
}
Referenced by ft_memmove(), and strndup().
ft_memmove()
void * ft_memmove (void * dest, const void * src, size_t n)
Definition at line 24 of file ft_memmove.c.
{
    char            *d;
    const char      *s;
    d = dest;
    s = src;
    if (d == s)
        return (dest);
    if (d < s || d >= s + n)
        ft_memcpy(d, s, n);
    else
    {
        d += n;
        s += n;
        while (n--)
            *(--d) = *(--s);
    }
    return (dest);
}
References ft_memcpy().
ft_memset()
void * ft_memset (void * s, int c, size_t n)
Definition at line 28 of file ft_memset.c.
{
    unsigned char   *ptr;
    ptr = s;
    while (n-- > 0)
        *ptr++ = (unsigned char)c;
    return (s);
}
Referenced by ft_calloc(), and signal_handler().
ft_print_2d_arr()
void ft_print_2d_arr (char ** arr, char * name)
Definition at line 15 of file ft_print_2d_arr.c.
{
    int i;
    i = 0;
    if (ft_strlen(name) > 0)
        ft_printf(GRN"-----         %s[]        -----\n"RESET, name);
    while (arr && arr[i])
    {
        ft_printf(GRN"arr[%d]:  %s      at add: %p  \n"RESET, \
            i, arr[i], arr[i]);
        i++;
    }
}
References ft_printf(), ft_strlen(), GRN, and RESET.
Referenced by final_quote_removal(), and split_loc_vars().
ft_print_char()
int ft_print_char (int c)
Definition at line 15 of file ft_print_char.c.
{
    ft_putchar_fd(c, 1);
    return (1);
}
References ft_putchar_fd().
Referenced by ft_formatssssss(), and ft_printf().
ft_print_int()
int ft_print_int (int n)
Definition at line 15 of file ft_print_int.c.
{
    int     len;
    char    *num;
    num = ft_itoa(n);
    len = ft_print_str(num);
    free(num);
    return (len);
}
References ft_itoa(), and ft_print_str().
Referenced by ft_formatssssss().
ft_print_percent()
int ft_print_percent (void)
Definition at line 15 of file ft_print_percent.c.
{
    ft_putchar_fd('%', 1);
    return (1);
}
References ft_putchar_fd().
Referenced by ft_formatssssss().
ft_print_ptr()
int ft_print_ptr (unsigned long long ptr)
Definition at line 44 of file ft_print_ptr.c.
{
    int print_length;
    print_length = 0;
    if (ptr == 0)
        print_length += write(1, "(nil)", 5);
    else
    {
        print_length += write(1, "0x", 2);
        ft_put_ptr(ptr);
        print_length += ft_ptr_len(ptr);
    }
    return (print_length);
}
References ft_ptr_len(), and ft_put_ptr().
Referenced by ft_formatssssss().
ft_print_str()
int ft_print_str (char * str)
Definition at line 15 of file ft_print_str.c.
{
    int len;
    len = 0;
    if (str == NULL)
    {
        ft_putstr_fd("(null)", 1);
        return (6);
    }
    while (*str)
    {
        ft_putchar_fd(*str++, 1);
        len++;
    }
    return (len);
}
References ft_putchar_fd(), and ft_putstr_fd().
Referenced by ft_formatssssss(), ft_print_int(), and ft_print_unsigned_dec().
ft_print_unsigned_dec()
int ft_print_unsigned_dec (unsigned int n)
Definition at line 47 of file ft_print_unsigned_dec.c.
{
    int     count;
    char    *num;
    count = 0;
    if (n == 0)
        count += write(1, "0", 1);
    else
    {
        num = ft_uitoa(n);
        count += ft_print_str(num);
        free(num);
    }
    return (count);
}
References ft_print_str(), and ft_uitoa().
Referenced by ft_formatssssss().
ft_print_unsigned_hex()
int ft_print_unsigned_hex (unsigned int num, const char format)
Definition at line 49 of file ft_print_unsigned_hex.c.
{
    if (n == 0)
    {
        ft_putchar_fd('0', 1);
        return (1);
    }
    else
        ft_put_hex(n, upper_lower);
    return (ft_hex_len(n));
}
References ft_hex_len(), ft_put_hex(), and ft_putchar_fd().
Referenced by ft_formatssssss().
ft_printf()
int ft_printf (const char * format, ...)
Definition at line 37 of file ft_printf.c.
{
    int     i;
    va_list args;
    int     len;
    i = 0;
    len = 0;
    va_start(args, str);
    while (str[i])
    {
        if (str[i] == '%')
        {
            len += ft_formatssssss(args, str[i + 1]);
            i++;
        }
        else
            len += ft_print_char(str[i]);
        i++;
    }
    va_end(args);
    return (len);
}
References ft_formatssssss(), and ft_print_char().
Referenced by append_word_if_valid(), env_tests(), ft_print_2d_arr(), initialise(), input_error_checks(), main(), new_process(), pipe_tests(), print_ast_args(), print_ast_node(), print_env(), print_env_stack(), print_maxishell(), print_stack(), print_t_env(), print_tokens(), test_get_env(), test_init_env(), test_set_env(), and test_unset_env().
ft_ptr_len()
int ft_ptr_len (uintptr_t num)
Definition at line 15 of file ft_print_ptr.c.
{
    int len;
    len = 0;
    while (num != 0)
    {
        len++;
        num = num / 16;
    }
    return (len);
}
Referenced by ft_print_ptr().
ft_put_ptr()
void ft_put_ptr (uintptr_t num)
Definition at line 28 of file ft_print_ptr.c.
{
    if (num >= 16)
    {
        ft_put_ptr(num / 16);
        ft_put_ptr(num % 16);
    }
    else
    {
        if (num <= 9)
            ft_putchar_fd((num + '0'), 1);
        else
            ft_putchar_fd((num - 10 + 'a'), 1);
    }
}
References ft_put_ptr(), and ft_putchar_fd().
Referenced by ft_print_ptr(), and ft_put_ptr().
ft_putchar_fd()
void ft_putchar_fd (char c, int fd)
Definition at line 20 of file ft_putchar_fd.c.
{
    write(fd, &c, 1);
}
Referenced by builtin_echo(), ft_print_char(), ft_print_percent(), ft_print_str(), ft_print_unsigned_hex(), ft_put_hex(), ft_put_ptr(), ft_putendl_fd(), and ft_putnbr_fd().
ft_putendl_fd()
void ft_putendl_fd (char * s, int fd)
Definition at line 21 of file ft_putendl_fd.c.
{
    if (s)
    {
        ft_putstr_fd(s, fd);
        ft_putchar_fd('\n', fd);
    }
}
References ft_putchar_fd(), and ft_putstr_fd().
Referenced by builtin_exit(), builtin_export(), builtin_pwd(), ft_puterror(), and handle_exit().
ft_putnbr_fd()
void ft_putnbr_fd (int n, int fd)
Definition at line 20 of file ft_putnbr_fd.c.
{
    if (n == -2147483648)
        ft_putstr_fd("-2147483648", fd);
    else
    {
        if (n < 0)
        {
            ft_putchar_fd('-', fd);
            n = -n;
        }
        if (n >= 10)
            ft_putnbr_fd(n / 10, fd);
        ft_putchar_fd((n % 10) + '0', fd);
    }
}
References ft_putchar_fd(), ft_putnbr_fd(), and ft_putstr_fd().
Referenced by ft_putnbr_fd().
ft_putstr_fd()
void ft_putstr_fd (char * s, int fd)
Definition at line 20 of file ft_putstr_fd.c.
{
    if (s)
        write(fd, s, ft_strlen(s));
}
References ft_strlen().
Referenced by builtin_echo(), builtin_env(), ft_print_str(), ft_putendl_fd(), ft_puterror(), ft_putnbr_fd(), handle_exec_errors(), and handle_get_shell_variable().
ft_realloc_array()
char ** ft_realloc_array (char ** array, int old_size, int new_size)
Definition at line 15 of file ft_realloc_array.c.
{
    char    **new_array;
    int     i;
    new_array = malloc(sizeof(char *) * (new_size + 1));
    if (!new_array)
        exit(1);
    i = 0;
    while (i < old_size)
    {
        new_array[i] = array[i];
        i++;
    }
    while (i < new_size)
    {
        new_array[i] = NULL;
        i++;
    }
    free(array);
    return (new_array);
}
Referenced by handle_split_allocation().
ft_remove_quotes()
char * ft_remove_quotes (char * str, char quote_type)
Definition at line 15 of file ft_remove_quotes.c.
{
    int     len;
    char    *new_str;
    len = ft_strlen(str);
    new_str = NULL;
    if (len > 1 && str[0] == quote_type && str[len - 1] == quote_type)
    {
        new_str = ft_strndup(str + 1, len - 2);
        return (new_str);
    }
    return (ft_strdup(str));
}
References ft_strdup(), ft_strlen(), and ft_strndup().
Referenced by handle_add_set_shell_variable(), and post_process_command_args().
ft_split()
char ** ft_split (char const * s, char c)
Definition at line 95 of file ft_split.c.
{
    char    **result;
    int     word_count;
    if (!s)
        return (NULL);
    word_count = count_words(s, c);
    result = malloc(sizeof(char *) * (word_count + 1));
    if (!result)
        return (NULL);
    split_into_words(result, s, c);
    return (result);
}
References count_words(), and split_into_words().
Referenced by builtin_pipe_test(), ft_find_path(), main_loop(), and process_and_reassemble().
ft_strcat()
char * ft_strcat (char * dest, char * src)
Definition at line 26 of file ft_strcat.c.
{
    int i;
    int j;
    i = 0;
    while (dest[i] != '\0')
        i++;
    j = 0;
    while (src[j] != '\0')
    {
        dest[i + j] = src[j];
        j++;
    }
    dest[i + j] = '\0';
    return (dest);
}
Referenced by assemble_result(), generate_prompt(), and token_adj().
ft_strcat_const()
char * ft_strcat_const (const char * dest, const char * src)
Definition at line 15 of file ft_strcat_const.c.
{
    int     i;
    int     j;
    char    *result;
    result = malloc(sizeof(char) * (ft_strlen(dest) + ft_strlen(src) + 1));
    if (!result)
        return (NULL);
    i = 0;
    while (dest[i] != '\0')
    {
        result[i] = dest[i];
        i++;
    }
    j = 0;
    while (src[j] != '\0')
    {
        result[i + j] = src[j];
        j++;
    }
    result[i + j] = '\0';
    return (result);
}
References ft_strlen().
Referenced by check_operators().
ft_strchr()
char * ft_strchr (const char * s, int c)
Definition at line 25 of file ft_strchr.c.
{
    unsigned char   uc;
    uc = (unsigned char)c;
    while (*s != '\0' && *s != uc)
        s++;
    if (*s == uc)
        return ((char *)s);
    return (NULL);
}
Referenced by add_env(), add_env_node(), add_shell_var_node(), ft_exclude_delimiters(), handle_add_set_shell_variable(), handle_local_vars(), handle_phrase(), and tokenise().
ft_strcmp()
int ft_strcmp (const char * s1, const char * s2)
Definition at line 24 of file ft_strcmp.c.
{
    while (*s1 != '\0' || *s2 != '\0')
    {
        if (*s1 != *s2)
            return ((unsigned char)*s1 - (unsigned char)*s2);
        s1++;
        s2++;
    }
    return (0);
}
Referenced by builtin_echo(), builtin_env(), builtin_export(), execute(), exit_status_adj(), expand_env_and_loc_var(), get_env(), get_shell_variable(), open_file(), open_tmp_file(), print_env(), set_env(), set_shell_var(), str_start_adj(), test_get_env(), test_set_env(), test_unset_env(), unset_env(), and write_heredoc_lines().
ft_strcpy()
char * ft_strcpy (char * dest, const char * src)
Definition at line 25 of file ft_strcpy.c.
{
    unsigned int    i;
    i = 0;
    while (src[i] != '\0')
    {
        dest[i] = src[i];
        i++;
    }
    dest[i] = src[i];
    return (dest);
}
Referenced by generate_prompt(), and token_adj().
ft_strdup()
char * ft_strdup (const char * s)
Definition at line 23 of file ft_strdup.c.
{
    size_t  n;
    char    *new;
    n = ft_strlen(s);
    if (!s)
        return (NULL);
    new = malloc((n + 1) * sizeof(char));
    if (!new)
        return (NULL);
    ft_strlcpy(new, s, n + 1);
    return (new);
}
References ft_strlcpy(), and ft_strlen().
Referenced by add_env_node(), add_new_env(), add_shell_var_node(), append_expanded_var(), child_process(), create_pipe_node(), create_redir_node(), expand_env_and_loc_var(), expand_variable(), finalize_token(), ft_find_path(), ft_itoa(), ft_remove_all_edge_quotes(), ft_remove_quotes(), get_env_variable(), get_exit_status(), list_to_array(), new_token(), process_argument(), redirect_here_doc(), set_command_args(), set_env(), set_shell_var(), split_loc_vars(), tmp_adj(), and token_adj().
ft_striteri()
void ft_striteri (char * s, void(*)(unsigned int, char *) f)
Definition at line 28 of file ft_striteri.c.
{
    unsigned int    i;
    i = 0;
    if (!s || !f)
        return ;
    while (s[i] != '\0')
    {
        f(i, &s[i]);
        i++;
    }
}
ft_strjoin()
char * ft_strjoin (char const * s1, char const * s2)
Definition at line 23 of file ft_strjoin.c.
{
    size_t  len;
    char    *pt;
    char    *result;
    if (!s1 || !s2)
        return (NULL);
    len = ft_strlen(s1) + ft_strlen (s2) + 1;
    if (len == 0)
        return (NULL);
    pt = (char *)malloc(sizeof(char) * len);
    if (!pt)
        return (NULL);
    result = pt;
    while (*s1)
        *pt++ = *s1++;
    while (*s2)
        *pt++ = *s2++;
    *pt = '\0';
    return (result);
}
References ft_strlen().
Referenced by append_literal(), builtin_cd(), builtin_export(), env_to_array(), ft_strjoin_free(), generate_prompt_string(), handle_numeric_error(), and relative_path_handle().
ft_strjoin_free()
char * ft_strjoin_free (char * s1, char * s2)
Definition at line 15 of file ft_strjoin_free.c.
{
    char    *result;
    if (!s1 || !s2)
        return (NULL);
    result = ft_strjoin(s1, s2);
    free(s1);
    return (result);
}
References ft_strjoin().
Referenced by append_expanded_var(), ev_loop(), and expand_variable().
ft_strlcat()
size_t ft_strlcat (char * dest, const char * src, size_t size)
Definition at line 26 of file ft_strlcat.c.
{
    char        *d;
    const char  *s;
    size_t      len_dst;
    size_t      remaining_space;
    len_dst = 0;
    s = src;
    d = dst;
    while (size > 0 && *d != '\0')
    {
        d++;
        size--;
        len_dst++;
    }
    remaining_space = size;
    if (remaining_space == 0)
        return (len_dst + ft_strlen(src));
    while (--remaining_space > 0 && *s != '\0')
        *d++ = *s++;
    *d = '\0';
    return (len_dst + ft_strlen(src));
}
References ft_strlen().
ft_strlcpy()
size_t ft_strlcpy (char * dest, const char * src, size_t size)
Definition at line 25 of file ft_strlcpy.c.
{
    char        *d;
    const char  *s;
    size_t      n;
    d = dst;
    s = src;
    n = size;
    if (n > 0)
    {
        while (--n > 0 && *s != '\0')
            *d++ = *s++;
        *d = '\0';
    }
    while (*s != '\0')
        s++;
    return (s - src);
}
Referenced by ft_strdup(), and ft_strndup().
ft_strlen()
size_t ft_strlen (const char * s)
Definition at line 15 of file ft_strlen.c.
{
    size_t  i;
    i = 0;
    while (s[i])
        i++;
    return (i);
}
Referenced by final_quote_removal(), ft_print_2d_arr(), ft_putstr_fd(), ft_remove_all_edge_quotes(), ft_remove_quotes(), ft_strcat_const(), ft_strdup(), ft_strjoin(), ft_strlcat(), ft_strndup(), ft_strnstr(), ft_strstr(), ft_strtrim(), ft_substr(), generate_prompt(), generate_prompt_string(), handle_trailing_quote(), post_process_command_args(), print_tokens(), process_single_token(), token_adj(), and write_heredoc_lines().
ft_strmapi()
char * ft_strmapi (char const * s, char(*)(unsigned int, char) f)
Definition at line 28 of file ft_strmapi.c.
{
    char    *result;
    size_t  len;
    size_t  i;
    if (!s || !f)
        return (NULL);
    len = 0;
    while (s[len] != '\0')
        len++;
    result = (char *)malloc((len + 1) * sizeof(char));
    if (!result)
        return (NULL);
    i = 0;
    while (i < len)
    {
        result[i] = f(i, s[i]);
        i++;
    }
    result[len] = '\0';
    return (result);
}
ft_strncmp()
int ft_strncmp (const char * s1, const char * s2, size_t n)
Definition at line 24 of file ft_strncmp.c.
{
    while (n > 0 && (*s1 != '\0' || *s2 != '\0'))
    {
        if (*s1 != *s2)
            return ((unsigned char)*s1 - (unsigned char)*s2);
        s1++;
        s2++;
        n--;
    }
    return (0);
}
Referenced by child_process(), ft_find_path(), ft_strnstr(), ft_strstr(), generate_prompt_string(), list_repeat_check_str(), and main_loop().
ft_strndup()
char * ft_strndup (const char * s, size_t n)
Definition at line 23 of file ft_strndup.c.
{
    size_t  len;
    char    *new;
    len = ft_strlen(s);
    if (!s)
        return (NULL);
    new = malloc((n + 1) * sizeof(char));
    if (!new)
        return (NULL);
    if (n > len)
        n = len;
    ft_strlcpy(new, s, n + 1);
    return (new);
}
References ft_strlcpy(), and ft_strlen().
Referenced by add_env_node(), append_word_if_valid(), final_quote_removal(), ft_add_segment(), ft_remove_all_edge_quotes(), and ft_remove_quotes().
ft_strnstr()
char * ft_strnstr (const char * haystack, const char * needle, size_t len)
Definition at line 25 of file ft_strnstr.c.
{
    size_t  little_len;
    if (!big && n == 0)
        return (NULL);
    little_len = ft_strlen(little);
    if (little[0] == '\0')
        return ((char *)big);
    while (*big != '\0' && n >= little_len)
    {
        if (ft_strncmp(big, little, little_len) == 0)
            return ((char *)big);
        big++;
        n--;
    }
    return (NULL);
}
References ft_strlen(), and ft_strncmp().
ft_strrchr()
char * ft_strrchr (const char * s, int c)
Definition at line 24 of file ft_strrchr.c.
{
    unsigned char   uc;
    const char      *last_occurrence;
    last_occurrence = NULL;
    uc = (unsigned char)c;
    while (*s != '\0')
    {
        if (*s == uc)
            last_occurrence = s;
        s++;
    }
    if (*s == uc)
        return ((char *)s);
    return ((char *)last_occurrence);
}
ft_strstr()
char * ft_strstr (const char * big, const char * little)
Definition at line 24 of file ft_strstr.c.
{
    size_t  little_len;
    if (!big)
        return (NULL);
    little_len = ft_strlen(little);
    if (little[0] == '\0')
        return ((char *)big);
    while (*big != '\0')
    {
        if (ft_strncmp(big, little, little_len) == 0)
            return ((char *)big);
        big++;
    }
    return (NULL);
}
References ft_strlen(), and ft_strncmp().
ft_strtrim()
char * ft_strtrim (char const * s1, char const * set)
Definition at line 39 of file ft_strtrim.c.
{
    char    *str;
    size_t  i;
    size_t  start;
    size_t  end;
    if (!s1 || !set)
        return (NULL);
    start = 0;
    while (s1[start] && ft_char_in_set(s1[start], set))
        start++;
    end = ft_strlen(s1);
    while (end > start && ft_char_in_set(s1[end - 1], set))
        end--;
    str = (char *)malloc(sizeof(*s1) * (end - start + 1));
    if (!str)
        return (NULL);
    i = 0;
    while (start < end)
        str[i++] = s1[start++];
    str[i] = 0;
    return (str);
}
References ft_char_in_set(), and ft_strlen().
Referenced by trim_input().
ft_substr()
char * ft_substr (char const * s, unsigned int start, size_t len)
Definition at line 27 of file ft_substr.c.
{
    char    *new_str;
    size_t  i;
    size_t  j;
    size_t  size;
    size = ft_strlen(s) - start;
    if (start > ft_strlen(s))
        size = 0;
    else if (size > len)
        size = len;
    new_str = (char *)malloc(size + 1);
    if (!s || !new_str)
        return (0);
    i = start;
    j = 0;
    while (i < ft_strlen(s) && j < len)
        new_str[j++] = s[i++];
    new_str[j] = '\0';
    return (new_str);
}
References ft_strlen().
Referenced by append_literal(), ev_loop(), expand_variable(), and post_process_command_args().
ft_tolower()
int ft_tolower (int c)
Definition at line 15 of file ft_tolower.c.
{
    if (c >= 'A' && c <= 'Z')
        return (c + ('a' - 'A'));
    return (c);
}
ft_toupper()
int ft_toupper (int c)
Definition at line 15 of file ft_toupper.c.
{
    if (c >= 'a' && c <= 'z')
        return (c - ('a' - 'A'));
    return (c);
}
isnum_from_str()
int isnum_from_str (const char * str)
Definition at line 15 of file isnum_from_str.c.
{
    if (!str || *str == '\0')
        return (0);
    if (*str == '-' || *str == '+')
    {
        str++;
        if (*str == '\0')
            return (0);
    }
    while (*str)
    {
        if (*str < '0' || *str > '9')
            return (0);
        str++;
    }
    return (1);
}
list_len_char()
int list_len_char (char a[])
Definition at line 13 of file list_len_char.c.
{
    int i;
    i = 0;
    while (a[i] != '\0')
        i++;
    return (i);
}
list_len_str()
int list_len_str (char * a[])
Definition at line 15 of file list_len_str.c.
{
    int i;
    i = 0;
    while (a[i])
        i++;
    return (i);
}
list_repeat_check_int()
int list_repeat_check_int (int a[], int size)
Definition at line 15 of file list_repeat_check_int.c.
{
    int i;
    int j;
    i = 0;
    while (i < size - 1)
    {
        j = i + 1;
        while (j < size)
        {
            if (a[i] == a[j])
                return (1);
            j++;
        }
        i++;
    }
    return (0);
}
list_repeat_check_str()
int list_repeat_check_str (char * a[], int size)
Definition at line 15 of file list_repeat_check_str.c.
{
    int i;
    int j;
    i = 0;
    while (i < size - 1)
    {
        j = i + 1;
        while (j < size)
        {
            if (ft_strncmp(a[i], a[j], size) == 0)
                return (1);
            j++;
        }
        i++;
    }
    return (0);
}
References ft_strncmp().