maxishell: /github/workspace/src/parser/loc_env_var_handler_utils_utils.c File Reference
loc_env_var_handler_utils_utils.c File Reference
#include "tokens.h"
Functions
char * expand_env_and_loc_var (char *arg, t_ms_data *data)
void final_quote_removal (int arg_count, t_ast *command_node)
char * get_env_variable (char *arg, t_ms_data *data)
void handle_trailing_quote (char *arg)
char * get_exit_status (t_ms_data *data)
Function Documentation
expand_env_and_loc_var()
char * expand_env_and_loc_var (char * arg, t_ms_data * data)
Definition at line 45 of file loc_env_var_handler_utils_utils.c.
{
    char    *env_value_dup;
    arg = exit_status_adj(arg);
    if (ft_strcmp(arg, "$?") == 0)
        return (get_exit_status(data));
    else if (arg[0] == '$')
    {
        handle_trailing_quote(arg);
        env_value_dup = get_env_variable(arg, data);
        return (env_value_dup);
    }
    return (ft_strdup(""));
}
References exit_status_adj(), ft_strcmp(), ft_strdup(), get_env_variable(), get_exit_status(), and handle_trailing_quote().
Referenced by ev_loop().
final_quote_removal()
void final_quote_removal (int arg_count, t_ast * command_node)
Definition at line 21 of file loc_env_var_handler_utils_utils.c.
{
    int     i;
    size_t  len;
    char    *arg;
    char    *trimmed_arg;
    i = 0;
    ft_print_2d_arr(command_node->args, "final-quote_removal");
    while (i < arg_count)
    {
        arg = command_node->args[i];
        len = ft_strlen(arg);
        if ((arg[0] == '"' && arg[len - 1] == '"') || (arg[0] == '\''
                && arg[len - 1] == '\''))
        {
            trimmed_arg = ft_strndup(arg + 1, len - 2);
            free(command_node->args[i]);
            command_node->args[i] = trimmed_arg;
        }
        i++;
    }
}
References s_ast::args, ft_print_2d_arr(), ft_strlen(), and ft_strndup().
get_env_variable()
char * get_env_variable (char * arg, t_ms_data * data)
Definition at line 77 of file loc_env_var_handler_utils_utils.c.
{
    char    *env_value;
    env_value = get_env(data->envp, arg + 1);
    if (!env_value)
        env_value = get_env(data->shell_variables, arg + 1);
    if (env_value)
        return (ft_strdup(env_value));
    return (ft_strdup(""));
}
References s_ms_data::envp, ft_strdup(), get_env(), and s_ms_data::shell_variables.
Referenced by expand_env_and_loc_var().
get_exit_status()
char * get_exit_status (t_ms_data * data)
Definition at line 61 of file loc_env_var_handler_utils_utils.c.
{
    char    *exit_status;
    char    *exit_status_dup;
    exit_status = get_shell_variable(data->shell_variables, "?");
    exit_status_dup = ft_strdup(exit_status);
    return (exit_status_dup);
}
References ft_strdup(), get_shell_variable(), and s_ms_data::shell_variables.
Referenced by expand_env_and_loc_var().
handle_trailing_quote()
void handle_trailing_quote (char * arg)
Definition at line 71 of file loc_env_var_handler_utils_utils.c.
{
    if (arg[ft_strlen(arg) - 1] == '"')
        arg[ft_strlen(arg) - 1] = '\0';
}
References ft_strlen().
Referenced by expand_env_and_loc_var().