maxishell: /github/workspace/src/parser/loc_env_var_handler_utils.c File Reference
loc_env_var_handler_utils.c File Reference
#include "tokens.h"
Functions
char * ev_loop (char **start, t_ms_data *data, char *str_start, char *expanded_str)
char * expand_variable (char **start, t_ms_data *data)
void handle_local_vars (t_ms_data *data, char *arg)
char ** ft_add_segment (char **result, char *start, size_t length, int *count)
char ** ft_split_preserve_quotes (char *str, char delimiter)
Function Documentation
ev_loop()
char * ev_loop (char ** start, t_ms_data * data, char * str_start, char * expanded_str)
Definition at line 15 of file loc_env_var_handler_utils.c.
{
    char    *var_name;
    char    *var_start;
    char    *expanded_var;
    char    *tmp;
    int     len_before_var;
    var_start = *start;
    (*start)++;
    while (**start && (ft_isalnum(**start) || **start == '_'))
        (*start)++;
    var_name = ft_substr(var_start, 0, *start - var_start);
    expanded_var = expand_env_and_loc_var(var_name, data);
    free(var_name);
    len_before_var = var_start - str_start;
    tmp = ft_substr(str_start, 0, len_before_var);
    expanded_str = ft_strjoin_free(expanded_str, tmp);
    free(tmp);
    expanded_str = ft_strjoin_free(expanded_str, expanded_var);
    free(expanded_var);
    return (expanded_str);
}
References expand_env_and_loc_var(), ft_isalnum(), ft_strjoin_free(), and ft_substr().
Referenced by expand_variable().
expand_variable()
char * expand_variable (char ** start, t_ms_data * data)
Definition at line 40 of file loc_env_var_handler_utils.c.
{
    char    *expanded_str;
    char    *str_start;
    char    *result;
    result = NULL;
    str_start = *start;
    expanded_str = ft_strdup("");
    while (**start && **start != '\0')
    {
        if (**start == '$')
        {
            expanded_str = ev_loop(start, data, str_start, expanded_str);
            str_start = *start;
            str_start = str_start_adj(str_start);
        }
        else
            (*start)++;
    }
    if (str_start != *start)
    {
        result = ft_substr(str_start, 0, *start - str_start);
        expanded_str = ft_strjoin_free(expanded_str, result);
        free(result);
    }
    return (expanded_str);
}
References ev_loop(), ft_strdup(), ft_strjoin_free(), ft_substr(), and str_start_adj().
Referenced by process_argument(), and process_single_token().
ft_add_segment()
char ** ft_add_segment (char ** result, char * start, size_t length, int * count)
Definition at line 91 of file loc_env_var_handler_utils.c.
{
    result = realloc(result, (*count + 1) * sizeof(char *));
    result[*count] = ft_strndup(start, length);
    (*count)++;
    return (result);
}
References ft_strndup().
Referenced by add_segment_on_delimiter(), and ft_split_preserve_quotes().
ft_split_preserve_quotes()
char ** ft_split_preserve_quotes (char * str, char delimiter)
Definition at line 99 of file loc_env_var_handler_utils.c.
{
    int     count;
    int     in_quotes;
    char    *start;
    char    **result;
    in_quotes = 0;
    start = str;
    result = initialize_result_array(&count);
    if (!result)
        return (NULL);
    while (*str)
    {
        in_quotes = toggle_quotes(in_quotes, *str);
        if (*str == delimiter && !in_quotes)
            result = add_segment_on_delimiter(result, &start, str, &count);
        str++;
    }
    if (str != start)
        result = ft_add_segment(result, start, str - start, &count);
    return (finalize_result_array(result, count));
}
References add_segment_on_delimiter(), finalize_result_array(), ft_add_segment(), initialize_result_array(), and toggle_quotes().
Referenced by split_loc_vars().
handle_local_vars()
void handle_local_vars (t_ms_data * data, char * arg)
Definition at line 69 of file loc_env_var_handler_utils.c.
{
    char    *p;
    int     valid_var;
    p = arg;
    valid_var = 1;
    if (arg[0] != '=' && ft_strchr(arg, '='))
    {
        while (p < ft_strchr(arg, '='))
        {
            if (!ft_isalnum(*p++))
            {
                valid_var = 0;
                break ;
            }
        }
        if (valid_var)
            handle_add_set_shell_variable(&data->shell_variables, arg);
    }
}
References ft_isalnum(), ft_strchr(), handle_add_set_shell_variable(), and s_ms_data::shell_variables.
Referenced by post_process_command_args().