maxishell: /github/workspace/src/parser/loc_env_var_handler.c File Reference
loc_env_var_handler.c File Reference
#include <tokens.h>
#include "libft.h"
Functions
void handle_local_vars (t_ms_data *data, char *arg)
char * process_argument (char *arg, t_ms_data *data)
void handle_split_allocation (t_ast *command_node, int *current_size, int required_size)
void split_loc_vars (t_ast *command_node, char *processed_arg, int *current_size, int *i)
void post_process_command_args (t_ast *command_node, int arg_count, t_ms_data *data)
char * append_expanded_var (char *processed_arg, char *tmp_ad, char *expanded_var)
Function Documentation
append_expanded_var()
char * append_expanded_var (char * processed_arg, char * tmp_ad, char * expanded_var)
Definition at line 97 of file loc_env_var_handler.c.
{
    char    *tmp;
    char    *tmp_2;
    tmp = ft_strjoin_free(processed_arg, expanded_var);
    tmp_ad = tmp_adj(tmp);
    free(expanded_var);
    tmp_2 = ft_strdup(tmp_ad);
    free(tmp_ad);
    return (tmp_2);
}
References ft_strdup(), ft_strjoin_free(), and tmp_adj().
Referenced by process_argument().
handle_local_vars()
void handle_local_vars (t_ms_data * data, char * arg)
Definition at line 69 of file loc_env_var_handler_utils.c.
{
    char    *p;
    int     valid_var;
    p = arg;
    valid_var = 1;
    if (arg[0] != '=' && ft_strchr(arg, '='))
    {
        while (p < ft_strchr(arg, '='))
        {
            if (!ft_isalnum(*p++))
            {
                valid_var = 0;
                break ;
            }
        }
        if (valid_var)
            handle_add_set_shell_variable(&data->shell_variables, arg);
    }
}
Referenced by post_process_command_args().
handle_split_allocation()
void handle_split_allocation (t_ast * command_node, int * current_size, int required_size)
Definition at line 19 of file loc_env_var_handler.c.
{
    if (required_size > *current_size)
    {
        command_node->args = ft_realloc_array(command_node->args, \
                                                *current_size, required_size);
        *current_size = required_size;
    }
}
References s_ast::args, and ft_realloc_array().
Referenced by split_loc_vars().
post_process_command_args()
void post_process_command_args (t_ast * command_node, int arg_count, t_ms_data * data)
Definition at line 67 of file loc_env_var_handler.c.
{
    int     i;
    char    *processed_arg;
    int     current_size;
    char    *tmp_proc_arg;
    i = 0;
    tmp_proc_arg = NULL;
    current_size = arg_count;
    while (i < current_size)
    {
        if (!is_in_single_quotes(command_node->args[i]))
        {
            handle_local_vars(data, command_node->args[i]);
            tmp_proc_arg = process_argument(command_node->args[i], data);
        }
        else
            tmp_proc_arg = ft_substr(command_node->args[i], 1, \
                                        ft_strlen(command_node->args[i]) - 2);
        free(command_node->args[i]);
        processed_arg = ft_remove_quotes(tmp_proc_arg, '\"');
        free(tmp_proc_arg);
        split_loc_vars(command_node, processed_arg, &current_size, &i);
        free(processed_arg);
    }
    command_node->args[current_size] = NULL;
}
References s_ast::args, ft_remove_quotes(), ft_strlen(), ft_substr(), handle_local_vars(), is_in_single_quotes(), process_argument(), and split_loc_vars().
Referenced by manage_commands().
process_argument()
char * process_argument (char * arg, t_ms_data * data)
Definition at line 111 of file loc_env_var_handler.c.
{
    char    *start;
    char    *processed_arg;
    char    *tmp_ad;
    char    *expanded_var;
    tmp_ad = NULL;
    processed_arg = ft_strdup("");
    start = arg;
    while (*start != '\0')
    {
        if (*start == '$')
        {
            expanded_var = expand_variable(&start, data);
            if (expanded_var != NULL)
            {
                processed_arg = append_expanded_var(processed_arg, \
                                    tmp_ad, expanded_var);
                free(tmp_ad);
            }
        }
        else
            processed_arg = append_literal(&start, processed_arg);
    }
    return (processed_arg);
}
References append_expanded_var(), append_literal(), expand_variable(), and ft_strdup().
Referenced by post_process_command_args().
split_loc_vars()
void split_loc_vars (t_ast * command_node, char * processed_arg, int * current_size, int * i)
Definition at line 30 of file loc_env_var_handler.c.
{
    char    **split_arg;
    int     split_count;
    int     required_size;
    int     j;
    split_arg = ft_split_preserve_quotes(processed_arg, ' ');
    split_count = ft_len_2d_arr(split_arg);
    if (split_count > 1)
    {
        required_size = *i + split_count;
        handle_split_allocation(command_node, current_size, required_size);
        j = 0;
        while (j < split_count)
        {
            command_node->args[*i + j] = ft_strdup(split_arg[j]);
            j++;
        }
        *i += split_count;
    }
    else
    {
        command_node->args[*i] = ft_strdup(processed_arg);
        (*i)++;
    }
    ft_print_2d_arr(split_arg, "split_arg");
    if (split_arg != NULL)
    {
        printf("here!\n");
        ft_free_2d_arr(split_arg);
        printf("here after free!\n");
    }
}
References s_ast::args, ft_free_2d_arr(), ft_len_2d_arr(), ft_print_2d_arr(), ft_split_preserve_quotes(), ft_strdup(), and handle_split_allocation().
Referenced by post_process_command_args().