maxishell: /github/workspace/src/parser/loc_env_var_handler_heredoc_utils.c File Reference
loc_env_var_handler_heredoc_utils.c File Reference
#include "shell.h"
#include "tokens.h"
#include "redirection.h"
#include "execute.h"
#include <fcntl.h>
#include <sys/wait.h>
#include "signals.h"
Functions
char * token_adj (char *arg)
Function Documentation
token_adj()
char * token_adj (char * arg)
Definition at line 21 of file loc_env_var_handler_heredoc_utils.c.
{
    char    *ptr;
    char    *new_arg;
    if (*arg == '\"')
    {
        ptr = arg + 1;
        while (*ptr && *ptr != '\"')
        {
            if (!ft_isdigit(*ptr))
                return (ft_strdup(arg));
            ptr++;
        }
        if (*ptr == '\0')
        {
            new_arg = malloc(ft_strlen(arg) + 2);
            if (!new_arg)
                return (NULL);
            ft_strcpy(new_arg, arg);
            ft_strcat(new_arg, "\"");
            return (new_arg);
        }
        if (*ptr == '\"' && *(ptr + 1) == '\0')
            return (ft_strdup(arg));
    }
    return (ft_strdup(arg));
}
References ft_isdigit(), ft_strcat(), ft_strcpy(), ft_strdup(), and ft_strlen().
Referenced by finalize_token().