maxishell: /github/workspace/src/parser/loc_env_var_handler_utils_utils_utils.c File Reference
loc_env_var_handler_utils_utils_utils.c File Reference
#include "tokens.h"
Functions
char * exit_status_adj (char *arg)
int is_in_single_quotes (char *arg)
char * str_start_adj (char *arg)
char * tmp_adj (char *arg)
char * append_literal (char **start, char *processed_arg)
Function Documentation
append_literal()
char * append_literal (char ** start, char * processed_arg)
Definition at line 74 of file loc_env_var_handler_utils_utils_utils.c.
{
    char    *literal_part;
    char    *literal_start;
    char    *tmp;
    literal_start = *start;
    while (**start != '\0' && **start != '$')
        (*start)++;
    literal_part = ft_substr(literal_start, 0, *start - literal_start);
    tmp = ft_strjoin(processed_arg, literal_part);
    free(literal_part);
    free(processed_arg);
    return (tmp);
}
References ft_strjoin(), and ft_substr().
Referenced by process_argument().
exit_status_adj()
char * exit_status_adj (char * arg)
Definition at line 21 of file loc_env_var_handler_utils_utils_utils.c.
{
    if (ft_strcmp(arg, "$") == 0)
        return ("$?");
    return (arg);
}
References ft_strcmp().
Referenced by expand_env_and_loc_var().
is_in_single_quotes()
int is_in_single_quotes (char * arg)
Definition at line 28 of file loc_env_var_handler_utils_utils_utils.c.
{
    int len;
    if (!arg || arg[0] != '\'')
        return (0);
    len = 0;
    while (arg[len] != '\0')
        len++;
    if (arg[len - 1] == '\'')
        return (1);
    return (0);
}
Referenced by post_process_command_args().
str_start_adj()
char * str_start_adj (char * arg)
Definition at line 42 of file loc_env_var_handler_utils_utils_utils.c.
{
    if (!ft_strcmp(arg, "?") || !ft_strcmp(arg, "?\""))
        return ("");
    else if (!ft_strcmp(arg, "?\'"))
        return ("\'");
    return (arg);
}
References ft_strcmp().
Referenced by expand_variable().
tmp_adj()
char * tmp_adj (char * arg)
Definition at line 51 of file loc_env_var_handler_utils_utils_utils.c.
{
    char    *ptr;
    char    *tmp_adj_dup;
    if (*arg == '\"')
    {
        ptr = arg + 1;
        while (*ptr)
        {
            if (!ft_isdigit(*ptr))
                return (arg);
            ptr++;
        }
        tmp_adj_dup = ft_strdup(arg + 1);
        free(arg);
        return (tmp_adj_dup);
    }
    tmp_adj_dup = ft_strdup(arg);
    free(arg);
    return (tmp_adj_dup);
}
References ft_isdigit(), and ft_strdup().
Referenced by append_expanded_var().