maxishell: /github/workspace/src/parser/loc_env_var_handler_heredoc.c File Reference
loc_env_var_handler_heredoc.c File Reference
#include "shell.h"
#include "tokens.h"
#include "redirection.h"
#include "execute.h"
#include <fcntl.h>
#include <sys/wait.h>
#include "signals.h"
Functions
static char * assemble_result (char **tokens, size_t result_len)
char * token_adj (char *arg)
char * finalize_token (char *tmp_token, char *orig_token)
size_t process_single_token (char **token, t_ms_data *data)
size_t process_tokens (char **tokens, t_ms_data *data)
char * process_and_reassemble (char *line, t_ms_data *data)
Function Documentation
assemble_result()
static char * assemble_result (char ** tokens, size_t result_len) static
Definition at line 96 of file loc_env_var_handler_heredoc.c.
{
    char    *result;
    int     i;
    result = malloc(result_len + 1);
    if (!result)
        return (NULL);
    *result = '\0';
    i = 0;
    while (tokens[i])
    {
        ft_strcat(result, tokens[i]);
        if (tokens[i + 1])
            ft_strcat(result, " ");
        i++;
    }
    return (result);
}
References ft_strcat().
Referenced by process_and_reassemble().
finalize_token()
char * finalize_token (char * tmp_token, char * orig_token)
Definition at line 74 of file loc_env_var_handler_heredoc.c.
{
    char    *processed_token;
    char    *new_token;
    if (tmp_token)
    {
        processed_token = token_adj(tmp_token);
        if (processed_token != tmp_token)
        {
            new_token = ft_strdup(processed_token);
            free(tmp_token);
        }
        else
            new_token = tmp_token;
        free(processed_token);
    }
    else
        new_token = ft_strdup(orig_token);
    return (new_token);
}
References ft_strdup(), new_token(), and token_adj().
Referenced by process_single_token().
process_and_reassemble()
char * process_and_reassemble (char * line, t_ms_data * data)
Definition at line 27 of file loc_env_var_handler_heredoc.c.
{
    char    **tokens;
    size_t  result_len;
    char    *result;
    tokens = ft_split(line, ' ');
    free(line);
    if (!tokens)
        return (NULL);
    result_len = process_tokens(tokens, data);
    result = assemble_result(tokens, result_len);
    ft_free_2d_arr(tokens);
    return (result);
}
References assemble_result(), ft_free_2d_arr(), ft_split(), and process_tokens().
Referenced by redirect_here_doc().
process_single_token()
size_t process_single_token (char ** token, t_ms_data * data)
Definition at line 58 of file loc_env_var_handler_heredoc.c.
{
    char    *orig_token;
    char    *tmp_token;
    char    *new_token;
    size_t  new_len;
    orig_token = *token;
    tmp_token = expand_variable(token, data);
    new_token = finalize_token(tmp_token, orig_token);
    *token = new_token;
    free(orig_token);
    new_len = ft_strlen(new_token) + 1;
    return (new_len);
}
References expand_variable(), finalize_token(), ft_strlen(), and new_token().
Referenced by process_tokens().
process_tokens()
size_t process_tokens (char ** tokens, t_ms_data * data)
Definition at line 43 of file loc_env_var_handler_heredoc.c.
{
    int     i;
    size_t  result_len;
    result_len = 0;
    i = 0;
    while (tokens[i])
    {
        result_len += process_single_token(&tokens[i], data);
        i++;
    }
    return (result_len);
}
References process_single_token().
Referenced by process_and_reassemble().
token_adj()
char * token_adj (char * arg)
Definition at line 21 of file loc_env_var_handler_heredoc_utils.c.
{
    char    *ptr;
    char    *new_arg;
    if (*arg == '\"')
    {
        ptr = arg + 1;
        while (*ptr && *ptr != '\"')
        {
            if (!ft_isdigit(*ptr))
                return (ft_strdup(arg));
            ptr++;
        }
        if (*ptr == '\0')
        {
            new_arg = malloc(ft_strlen(arg) + 2);
            if (!new_arg)
                return (NULL);
            ft_strcpy(new_arg, arg);
            ft_strcat(new_arg, "\"");
            return (new_arg);
        }
        if (*ptr == '\"' && *(ptr + 1) == '\0')
            return (ft_strdup(arg));
    }
    return (ft_strdup(arg));
}
References ft_isdigit(), ft_strcat(), ft_strcpy(), ft_strdup(), and ft_strlen().
Referenced by finalize_token().