maxishell: /github/workspace/src/parser/loc_env_var_handler_utils_utils_utils_utils.c File Reference
loc_env_var_handler_utils_utils_utils_utils.c File Reference
#include "tokens.h"
Functions
char ** initialize_result_array (int *count)
int toggle_quotes (int in_quotes, char current_char)
char ** add_segment_on_delimiter (char **result, char **start, char *str, int *count)
char ** finalize_result_array (char **result, int count)
Function Documentation
add_segment_on_delimiter()
char ** add_segment_on_delimiter (char ** result, char ** start, char * str, int * count)
Definition at line 33 of file loc_env_var_handler_utils_utils_utils_utils.c.
{
    result = ft_add_segment(result, *start, str - *start, count);
    *start = str + 1;
    return (result);
}
References ft_add_segment().
Referenced by ft_split_preserve_quotes().
finalize_result_array()
char ** finalize_result_array (char ** result, int count)
Definition at line 41 of file loc_env_var_handler_utils_utils_utils_utils.c.
{
    char    **temp;
    temp = realloc(result, sizeof(char *) * (count + 1));
    if (!temp)
    {
        free(result);
        return (NULL);
    }
    result = temp;
    result[count] = NULL;
    return (result);
}
Referenced by ft_split_preserve_quotes().
initialize_result_array()
char ** initialize_result_array (int * count)
Definition at line 15 of file loc_env_var_handler_utils_utils_utils_utils.c.
{
    char    **result;
    *count = 0;
    result = malloc(sizeof(char *));
    if (!result)
        return (NULL);
    return (result);
}
Referenced by ft_split_preserve_quotes().
toggle_quotes()
int toggle_quotes (int in_quotes, char current_char)
Definition at line 26 of file loc_env_var_handler_utils_utils_utils_utils.c.
{
    if (current_char == '"' || current_char == '\'')
        return (!in_quotes);
    return (in_quotes);
}
Referenced by ft_split_preserve_quotes().