maxishell: /github/workspace/src/main.c File Reference
main.c File Reference
#include "tokens.h"
#include "execute.h"
#include "shell.h"
#include "pipe.h"
#include "signals.h"
#include "exit_status.h"
#include "builtins.h"
Functions
int status_handler (int status, t_loop_data *loop_data, t_token *token_head)
void process_ast_and_io (t_ms_data *data, t_loop_data *loop_data, t_token *tokens_head)
void main_loop (t_ms_data *data, t_loop_data *loop_data)
int main (int argc, char **argv, char **envp)
Function Documentation
main()
int main (int argc, char ** argv, char ** envp)
Definition at line 82 of file main.c.
{
    t_ms_data       data;
    t_loop_data     loop_data;
    print_maxishell();
    init_ms_data(&data, argv, envp);
    initialise(argc, argv);
    main_loop(&data, &loop_data);
    free_ms_data(&data);
    clear_history_file();
    return (0);
}
References clear_history_file(), free_ms_data(), init_ms_data(), initialise(), main_loop(), and print_maxishell().
main_loop()
void main_loop (t_ms_data * data, t_loop_data * loop_data)
Definition at line 55 of file main.c.
{
    t_token *tokens_start;
    while (1)
    {
        set_signals_interactive(data);
        loop_data->input = readline("🌴 maxishell> ");
        set_signals_noninteractive();
        if (!loop_data->input || !ft_strncmp(loop_data->input, "exit", 4))
        {
            data->args = ft_split(loop_data->input, ' ');
            builtin_exit(data);
        }
        make_history(loop_data->input);
        loop_data->trimmed_input = trim_input(loop_data->input);
        if (input_error_checks(loop_data))
            continue ;
        loop_data->tokens = tokenise(loop_data->trimmed_input);
        tokens_start = loop_data->tokens;
        loop_data->tree = parse_tokens(&loop_data->tokens, data);
        print_ast_root(loop_data->tree);
        process_ast_and_io(data, loop_data, tokens_start);
    }
    clear_history_file();
}
References s_ms_data::args, builtin_exit(), clear_history_file(), ft_split(), ft_strncmp(), s_loop_data::input, input_error_checks(), make_history(), parse_tokens(), print_ast_root(), process_ast_and_io(), set_signals_interactive(), set_signals_noninteractive(), tokenise(), s_loop_data::tokens, s_loop_data::tree, trim_input(), and s_loop_data::trimmed_input.
Referenced by main().
process_ast_and_io()
void process_ast_and_io (t_ms_data * data, t_loop_data * loop_data, t_token * tokens_head)
Definition at line 39 of file main.c.
{
    int status;
    status = execute_ast(loop_data->tree, data);
    printf("execute ast exit status -> %d\n", status);
    data->exit_status = status;
    set_shell_var_handler(data);
    if (status_handler(status, loop_data, tokens_head))
    {
        handle_io_fd(data);
        loop_cleanup(loop_data, tokens_head);
    }
}
References execute_ast(), s_ms_data::exit_status, handle_io_fd(), loop_cleanup(), set_shell_var_handler(), status_handler(), and s_loop_data::tree.
Referenced by main_loop().
status_handler()
int status_handler (int status, t_loop_data * loop_data, t_token * token_head)
Definition at line 28 of file main.c.
{
    if (status == EXIT_FAILURE)
    {
        loop_cleanup(loop_data, tokens_head);
        return (0);
    }
    return (1);
}
References EXIT_FAILURE, and loop_cleanup().
Referenced by process_ast_and_io().