maxishell: /github/workspace/src/parser/parser_helper_helpers.c File Reference
parser_helper_helpers.c File Reference
#include "tokens.h"
#include "execute.h"
Functions
void final_quote_removal (int arg_count, t_ast *command_node)
char * expand_env_var (char *arg, t_ms_data *data)
void handle_local_vars (t_ms_data *data, char *arg)
void post_process_command_args (t_ast *command_node, int arg_count, t_ms_data *data)
Function Documentation
expand_env_var()
char * expand_env_var (char * arg, t_ms_data * data)
Definition at line 39 of file parser_helper_helpers.c.
{
    char    *env_value;
    if (ft_strcmp(arg, "$?") == 0)
        return (ft_itoa(data->exit_status));
    else if (arg[0] == '$')
    {
        if (arg[ft_strlen(arg) - 1] == '"')
            arg[ft_strlen(arg) - 1] = '\0';
        env_value = get_env(data->envp, arg + 1);
        if (env_value)
            return (ft_strdup(env_value));
    }
    return (ft_strdup(arg));
}
References s_ms_data::envp, s_ms_data::exit_status, ft_itoa(), ft_strcmp(), ft_strdup(), ft_strlen(), and get_env().
Referenced by post_process_command_args().
final_quote_removal()
void final_quote_removal (int arg_count, t_ast * command_node)
Definition at line 16 of file parser_helper_helpers.c.
{
    int     i;
    size_t  len;
    char    *arg;
    char    *trimmed_arg;
    i = 0;
    while (i < arg_count)
    {
        arg = command_node->args[i];
        len = ft_strlen(arg);
        if ((arg[0] == '"' && arg[len - 1] == '"') || (arg[0] == '\'' \
            && arg[len - 1] == '\''))
        {
            trimmed_arg = ft_strndup(arg + 1, len - 2);
            free(command_node->args[i]);
            command_node->args[i] = trimmed_arg;
        }
        i++;
    }
}
References s_ast::args, ft_strlen(), and ft_strndup().
Referenced by post_process_command_args().
handle_local_vars()
void handle_local_vars (t_ms_data * data, char * arg)
Definition at line 56 of file parser_helper_helpers.c.
{
    char    *p;
    int     valid_var;
    p = arg;
    valid_var = 1;
    if (arg[0] != '=' && strchr(arg, '='))
    {
        while (p < strchr(arg, '='))
        {
            if (!ft_isalnum(*p++))
            {
                valid_var = 0;
                break ;
            }
        }
        if (valid_var)
            handle_add_set_shell_variable(&data->shell_variables, arg);
    }
}
References ft_isalnum(), handle_add_set_shell_variable(), and s_ms_data::shell_variables.
Referenced by post_process_command_args().
post_process_command_args()
void post_process_command_args (t_ast * command_node, int arg_count, t_ms_data * data)
Definition at line 78 of file parser_helper_helpers.c.
{
    int     i;
    char    *arg;
    char    *processed_arg;
    i = 0;
    while (i < arg_count)
    {
        arg = command_node->args[i];
        handle_local_vars(data, arg);
        processed_arg = NULL;
        if (arg[0] == '$' || (arg[0] == '"' && arg[1] == '$'))
        {
            if (arg[0] == '"')
                processed_arg = expand_env_var(arg + 1, data);
            else
                processed_arg = expand_env_var(arg, data);
        }
        else if (arg[0] == '\'')
            processed_arg = ft_strdup(arg);
        else
            processed_arg = ft_strdup(arg);
        free(command_node->args[i]);
        command_node->args[i] = processed_arg;
        i++;
    }
    final_quote_removal(arg_count, command_node);
}
References s_ast::args, expand_env_var(), final_quote_removal(), ft_strdup(), and handle_local_vars().
Referenced by manage_commands().