maxishell: /github/workspace/src/parser/parser_helpers.c File Reference
parser_helpers.c File Reference
#include "tokens.h"
Functions
t_ast * new_ast_node (t_token_type type)
t_ast * create_redir (t_token **tokens, t_token *tmp, t_ms_data *data)
int arg_len (t_token *current)
void set_command_args (t_ast *command_node, t_token **tokens, int arg_count)
t_ast * manage_commands (t_token **tokens, t_ms_data *data)
char * expand_env_var (char *arg, t_ms_data *data)
void post_process_command_args (t_ast *command_node, int arg_count, t_ms_data *data)
Function Documentation
arg_len()
int arg_len (t_token * current)
Definition at line 48 of file parser_helpers.c.
{
    int arg_count;
    arg_count = 0;
    while (current && current->type == PHRASE)
    {
        arg_count++;
        current = current->next;
    }
    return (arg_count);
}
References s_token::next, PHRASE, and s_token::type.
Referenced by manage_commands().
create_redir()
t_ast * create_redir (t_token ** tokens, t_token * tmp, t_ms_data * data)
Definition at line 35 of file parser_helpers.c.
{
    t_ast   *redirect_node;
    redirect_node = new_ast_node((*tokens)->type);
    *tokens = (*tokens)->next->next;
    redirect_node->left = manage_redirs(tokens, data);
    redirect_node->right = create_redir_node(tmp->next);
    free(tmp->data);
    free(tmp);
    return (redirect_node);
}
References create_redir_node(), s_token::data, s_ast::left, manage_redirs(), new_ast_node(), s_token::next, and s_ast::right.
Referenced by manage_redirs().
expand_env_var()
char * expand_env_var (char * arg, t_ms_data * data)
Definition at line 80 of file parser_helpers.c.
{
    if (strcmp(arg, "$?") == 0) {
        return ft_itoa(data->exit_status);
    } else if (arg[0] == '$') {
        if (arg[strlen(arg) - 1] == '"')
        {
            arg[strlen(arg) - 1] = '\0';
        }
        char *env_value = get_env(data->envp, arg + 1);
        if (env_value) {
            return ft_strdup(env_value);
        }
    }
    return ft_strdup(arg);
}
References s_ms_data::envp, s_ms_data::exit_status, ft_itoa(), ft_strcmp(), ft_strdup(), ft_strlen(), and get_env().
Referenced by post_process_command_args().
manage_commands()
t_ast * manage_commands (t_token ** tokens, t_ms_data * data)
Definition at line 130 of file parser_helpers.c.
{
    t_ast       *command_node;
    int         arg_count;
    command_node = new_ast_node(PHRASE);
    arg_count = arg_len(*tokens);
    command_node->args = malloc(sizeof(char *) * (arg_count + 1));
    if (!command_node->args)
        return (NULL);
    set_command_args(command_node, tokens, arg_count);
    post_process_command_args(command_node, arg_count, data);
    return (command_node);
}
References arg_len(), s_ast::args, new_ast_node(), PHRASE, post_process_command_args(), and set_command_args().
Referenced by manage_redirs().
new_ast_node()
t_ast * new_ast_node (t_token_type type)
Definition at line 21 of file parser_helpers.c.
{
    t_ast       *node;
    node = malloc(sizeof(t_ast));
    if (!node)
        return (NULL);
    node->type = type;
    node->args = NULL;
    node->left = NULL;
    node->right = NULL;
    return (node);
}
References s_ast::args, s_ast::left, s_ast::right, and s_ast::type.
Referenced by create_redir(), manage_commands(), manage_pipe(), and manage_redirs().
post_process_command_args()
void post_process_command_args (t_ast * command_node, int arg_count, t_ms_data * data)
Definition at line 96 of file parser_helpers.c.
{
    size_t len;
    for (int i = 0; i < arg_count; i++) {
        char *arg = command_node->args[i];
        char *processed_arg = NULL;
        if (arg[0] == '$' || (arg[0] == '"' && arg[1] == '$')) {
            if (arg[0] == '"') {
                processed_arg = expand_env_var(arg + 1, data);
            } else {
                processed_arg = expand_env_var(arg, data);
            }
            printf(GRN"Expanded argument: %s\n"RESET, processed_arg);
        } else if (arg[0] == '\'') {
            processed_arg = ft_strdup(arg);
            printf(GRN"Unmodified argument: %s\n"RESET, processed_arg);
        } else {
            processed_arg = ft_strdup(arg);
        }
        free(command_node->args[i]);
        command_node->args[i] = processed_arg;
    }
    for (int i = 0; i < arg_count; i++) {
        char *arg = command_node->args[i];
        printf("current arg -> %s\n", arg);
        len = ft_strlen(arg);
        if ((arg[0] == '"' && arg[len - 1] == '"') || (arg[0] == '\'' && arg[len - 1] == '\'')) {
            char *trimmed_arg = ft_strndup(arg + 1, len - 2);
            free(command_node->args[i]);
            command_node->args[i] = trimmed_arg;
        }
    }
}
References s_ast::args, expand_env_var(), final_quote_removal(), ft_strdup(), ft_strlen(), ft_strndup(), GRN, and RESET.
Referenced by manage_commands().
set_command_args()
void set_command_args (t_ast * command_node, t_token ** tokens, int arg_count)
Definition at line 61 of file parser_helpers.c.
{
    int     i;
    t_token *tmp;
    i = 0;
    while (i < arg_count)
    {
        command_node->args[i] = ft_strdup((*tokens)->data);
        tmp = *tokens;
        *tokens = (*tokens)->next;
        free(tmp->data);
        free(tmp);
        i++;
    }
    command_node->args[arg_count] = NULL;
}
References s_ast::args, s_token::data, ft_strdup(), and s_token::next.
Referenced by manage_commands().