maxishell: /github/workspace/src/utils/prompt.c File Reference
prompt.c File Reference
#include "tokens.h"
#include "env.h"
Functions
char * generate_prompt (t_minishell_data *data)
char * generate_prompt_string (t_minishell_data *data, char *pwd, char *home_dir)
void print_maxishell (void)
Function Documentation
generate_prompt()
char * generate_prompt (t_minishell_data * data)
Definition at line 31 of file prompt.c.
{
    char    *prompt;
    size_t  prompt_len;
/*
     char   *pwd;
     char   *home_dir;
     home_dir = NULL;
     pwd = NULL;
     pwd = generate_prompt_string(data, pwd, home_dir);
*/
    if (data->std_in == -1)
        prompt_len = ft_strlen("minishell:~> ") + 1;
    else
        prompt_len = ft_strlen("> ") + 1;
/*
     prompt_len = ft_strlen("🌴\e[1m @maxishell:~> \e[m") + \
            ft_strlen(get_env(data->envp, "LOGNAME")) + \
            ft_strlen(pwd) + \
            1;
*/
    prompt = (char *)malloc(prompt_len);
    if (!prompt)
        exit(EXIT_FAILURE);
    if (data->std_in == -1)
        ft_strcpy(prompt, "minishell:~> ");
    else
        ft_strcpy(prompt, "> ");
/*
    ft_strcpy(prompt, "🌴\e[1m ");
    ft_strcat(prompt, get_env(data->envp, "LOGNAME"));
    ft_strcat(prompt, "@maxishell:");
    ft_strcat(prompt, pwd);
    ft_strcat(prompt, "> \e[m");
*/
    return (prompt);
}
References ft_strcpy(), ft_strlen(), and s_minishell_data::std_in.
Referenced by main_loop().
generate_prompt_string()
char * generate_prompt_string (t_minishell_data * data, char * pwd, char * home_dir)
Definition at line 71 of file prompt.c.
{
    char    *temp_pwd;
    pwd = get_env(data->envp, "PWD");
    if (pwd)
    {
        home_dir = get_env(data->envp, "HOME");
        if (home_dir && ft_strncmp(pwd, home_dir, ft_strlen(home_dir)) == 0)
        {
            temp_pwd = ft_strjoin("~", pwd + ft_strlen(home_dir));
            free(pwd);
            pwd = temp_pwd;
        }
    }
    return (pwd);
}
References s_minishell_data::envp, ft_strjoin(), ft_strlen(), ft_strncmp(), and get_env().
print_maxishell()
void print_maxishell (void)
Definition at line 90 of file prompt.c.
{
    ft_printf("\033[1;33m\n\n\n\n\n");
    ft_printf("███╗░░░███╗░█████╗░██╗░░██╗██╗░██████╗██╗░"
        "░██╗███████╗██╗░░░░░██╗░░░░░\n");
    ft_printf("████╗░████║██╔══██╗╚██╗██╔╝██║██╔════╝██║░"
        "░██║██╔════╝██║░░░░░██║░░░░░\n");
    ft_printf("██╔████╔██║███████║░╚███╔╝░██║╚█████╗░█████"
        "██║█████╗░░██║░░░░░██║░░░░░\n");
    ft_printf("██║╚██╔╝██║██╔══██║░██╔██╗░██║░╚═══██╗██╔══"
        "██║██╔══╝░░██║░░░░░██║░░░░░\n");
    ft_printf("██║░╚═╝░██║██║░░██║██╔╝╚██╗██║██████╔╝██║░░"
        "██║███████╗███████╗███████╗\n");
    ft_printf("╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═════╝░╚═╝░░"
        "╚═╝╚══════╝╚══════╝╚══════╝\n");
    ft_printf("\n");
    ft_printf("            \033[1;34m"
        "Version 0.0.0\033[0m\n");
    ft_printf("           \033[1;36m"
        "By Димас и Ромас\033[0m\n");
    ft_printf("\n");
}
References ft_printf().
Referenced by main().