maxishell: /github/workspace/src/redirection/utils.c File Reference
utils.c File Reference
#include "shell.h"
#include <fcntl.h>
#include "libft.h"
#include "tokens.h"
Functions
int open_file (t_ast *node, char *direction)
open file in the context of redirection
char * ft_get_next_line (int fd)
static char * extract_line (char **saved)
static char * read_from_fd (int fd, char *saved, char *buf)
char * ft_strjoin_gnl (char *s1, char const *s2)
Function Documentation
extract_line()
static char * extract_line (char ** saved) static
Definition at line 118 of file utils.c.
{
    char    *new_line_ptr;
    char    *line;
    char    *temp;
    new_line_ptr = ft_strchr(*saved, '\n');
    if (new_line_ptr)
    {
        line = ft_substr(*saved, 0, new_line_ptr - *saved + 1);
        temp = *saved;
        *saved = ft_strdup(new_line_ptr + 1);
        free(temp);
        return (line);
    }
    if (**saved)
    {
        line = ft_strdup(*saved);
        free(*saved);
        *saved = NULL;
        return (line);
    }
    return (NULL);
}
References BUFFER_SIZE, ft_strchr(), ft_strdup(), and ft_substr().
Referenced by ft_get_next_line().
ft_get_next_line()
char * ft_get_next_line (int fd)
Definition at line 41 of file utils.c.
{
    static char *saved = NULL;
    char        *line;
    char        *buf;
    if (fd < 0 || BUFFER_SIZE < 1 || fd > 4095)
        return (NULL);
    buf = malloc(BUFFER_SIZE + 1);
    if (!buf)
        return (NULL);
    saved = read_from_fd(fd, saved, buf);
    if (!saved)
    {
        free(saved);
        saved = NULL;
        return (NULL);
    }
    line = extract_line(&saved);
    if (line == NULL)
    {
        free(saved);
        saved = NULL;
    }
    return (line);
}
References BUFFER_SIZE, extract_line(), and read_from_fd().
ft_strjoin_gnl()
char * ft_strjoin_gnl (char * s1, char const * s2)
Definition at line 68 of file utils.c.
{
    char    *str;
    size_t  s1_len;
    size_t  s2_len;
    if (!s2)
        return (NULL);
    if (s1)
        s1_len = ft_strlen(s1);
    else
        s1_len = 0;
    s2_len = ft_strlen(s2);
    str = (char *)malloc(s1_len + s2_len + 1);
    if (!str)
        return (NULL);
    if (s1)
        ft_strlcpy(str, s1, s1_len + 1);
    else
        str[0] = '\0';
    ft_memcpy(str + s1_len, s2, s2_len + 1);
    return (str);
}
References BUFFER_SIZE, ft_memcpy(), ft_strlcpy(), and ft_strlen().
Referenced by read_from_fd().
open_file()
int open_file (t_ast * node, char * direction)
open file in the context of redirection
-- "<" - read
">" - write
">>" - append
"tty" - open /dev/tty
Parameters
node current node in the AST
Parameters
direction type of redirection
Returns
int file descriptor
Definition at line 24 of file utils.c.
{
    int fd;
    if ((ft_strcmp(direction, "<") == 0) || (ft_strcmp(direction, "read") == 0))
        fd = open(node->args[0], O_RDONLY);
    else if (ft_strcmp(direction, ">") == 0)
        fd = open(node->args[0], O_WRONLY | O_CREAT | O_TRUNC, 0644);
    else if ((ft_strcmp(direction, ">>") == 0) || (ft_strcmp(direction, "temp") == 0))
        fd = open(node->args[0], O_WRONLY | O_CREAT | O_APPEND, 0644);
    else if (ft_strcmp(direction, "tty") == 0)
        fd = open("/dev/tty", O_RDWR);
    else
        fd = -1;
    return (fd);
}
References s_ast::args, and ft_strcmp().
Referenced by redirect_append(), redirect_in(), and redirect_out().
read_from_fd()
static char * read_from_fd (int fd, char * saved, char * buf) static
Definition at line 92 of file utils.c.
{
    int     chars_read;
    char    *temp;
    chars_read = read(fd, buf, BUFFER_SIZE);
    while (chars_read > 0)
    {
        buf[chars_read] = '\0';
        temp = saved;
        saved = ft_strjoin_gnl(saved, buf);
        free(temp);
        if (ft_strchr(saved, '\n'))
            break ;
        chars_read = read(fd, buf, BUFFER_SIZE);
    }
    free(buf);
    if (chars_read < 0)
    {
        free(saved);
        saved = NULL;
        return (NULL);
    }
    return (saved);
}
References BUFFER_SIZE, ft_strchr(), and ft_strjoin_gnl().
Referenced by ft_get_next_line().