maxishell: /github/workspace/src/redirection/redirect_in.c File Reference
redirect_in.c File Reference
#include "tokens.h"
#include "shell.h"
#include "redirection.h"
#include "execute.h"
#include <string.h>
#include <sys/wait.h>
Functions
int redirect_in (t_ast *node, t_ms_data *data)
redirection input in context of executing AST
Function Documentation
redirect_in()
int redirect_in (t_ast * node, t_ms_data * data)
redirection input in context of executing AST
--
Parameters
node current node in the AST
Parameters
data minishell structure data
Returns
status:
0: success
1: error
Definition at line 32 of file redirect_in.c.
{
    pid_t   pid;
    int     status;
    int     local_fd;
    pid = fork();
    if (pid == -1)
        return (EXIT_FAILURE);
    if (pid == 0)
    {
        if (data->std_in == -1)
        {
            data->std_in = open_file(node->right, "<");
            if (data->std_in == -1)
                return (EXIT_FAILURE);
        }
        else
        {
            local_fd = open_file(node->right, "<");
            if (local_fd == -1)
                return (EXIT_FAILURE);
            dup2(local_fd, STDIN_FILENO);
            close(local_fd);
        }
        if (!node->left->args[0])
        {
            close(data->std_in);
            exit(EXIT_SUCCESS);
        }
        else
        {
            status = execute_ast(node->left, data);
            exit(status);
        }
    }
    waitpid(pid, &status, 0);
    return (WEXITSTATUS(status));
}
References s_ast::args, execute_ast(), EXIT_FAILURE, EXIT_SUCCESS, s_ast::left, open_file(), s_ast::right, and s_ms_data::std_in.
Referenced by execute_ast().