maxishell: /github/workspace/src/redirection/redirect_heredoc.c File Reference
redirect_heredoc.c File Reference
#include "shell.h"
#include "tokens.h"
#include "redirection.h"
#include "execute.h"
#include <fcntl.h>
#include <sys/wait.h>
Functions
int redirect_here_doc (t_ast *node, t_ms_data *data)
static int open_tmp_file (const char *type)
static void execute_child (t_ast *node, t_ms_data *data, int *file_fd)
static char * assemble_result (char **tokens, size_t result_len)
This function handle "<<" heredoc functionality.
char * process_and_reassemble (char *line, t_ms_data *data)
Function Documentation
assemble_result()
static char * assemble_result (char ** tokens, size_t result_len) static
This function handle "<<" heredoc functionality.
--
Parameters
node current node in the AST
Parameters
data minishell data structure
Returns
status:
0: success
1: error
Definition at line 34 of file redirect_heredoc.c.
{
    char    *result;
    int     i;
    result = malloc(result_len + 1);
    if (!result)
        return (NULL);
    *result = '\0';
    i = 0;
    while (tokens[i])
    {
        ft_strcat(result, tokens[i]);
        if (tokens[i + 1])
            ft_strcat(result, " ");
        i++;
    }
    free(tokens);
    return (result);
}
References ft_strcat().
Referenced by process_and_reassemble().
execute_child()
static void execute_child (t_ast * node, t_ms_data * data, int * file_fd) static
Definition at line 120 of file redirect_heredoc.c.
{
    pid_t   pid;
    pid = fork();
    if (pid == -1)
        ft_perror("fork");
    if (pid == 0)
    {
        data->std_in = dup(*file_fd);
        execute_ast(node, data);
        exit(0);
    }
    close(*file_fd);
    waitpid(pid, &data->exit_status, 0);
}
References execute_ast(), s_ms_data::exit_status, ft_perror(), and s_ms_data::std_in.
Referenced by redirect_here_doc().
open_tmp_file()
static int open_tmp_file (const char * type) static
Definition at line 106 of file redirect_heredoc.c.
{
    int file_fd;
    file_fd = -1;
    if (ft_strcmp(type, "w") == 0)
        file_fd = open("/tmp/heredoc", O_WRONLY | O_CREAT | O_TRUNC, 0644);
    else if (ft_strcmp(type, "r") == 0)
        file_fd = open("/tmp/heredoc", O_RDONLY);
    if (file_fd < 0)
        ft_perror("open");
    return (file_fd);
}
References ft_perror(), and ft_strcmp().
Referenced by redirect_here_doc().
process_and_reassemble()
char * process_and_reassemble (char * line, t_ms_data * data)
Definition at line 55 of file redirect_heredoc.c.
{
    char    **tokens;
    size_t  result_len;
    int     i;
    char    *processed_token;
    tokens = ft_split(line, ' ');
    if (!tokens)
        return (NULL);
    result_len = 0;
    i = 0;
    while (tokens[i])
    {
        processed_token = expand_env_and_loc_var(tokens[i], data);
        free(tokens[i]);
        tokens[i] = processed_token;
        result_len += ft_strlen(tokens[i]) + 1;
        i++;
    }
    return (assemble_result(tokens, result_len));
}
References assemble_result(), expand_env_and_loc_var(), ft_split(), and ft_strlen().
Referenced by redirect_here_doc().
redirect_here_doc()
int redirect_here_doc (t_ast * node, t_ms_data * data)
Definition at line 78 of file redirect_heredoc.c.
{
    char    *line;
    char    *eof;
    int     file_fd;
    line = NULL;
    if (node->right->args[0] == NULL)
        return (1);
    file_fd = open_tmp_file("w");
    eof = ft_strdup(node->right->args[0]);
    line = process_and_reassemble(readline("> "), data);
    while (line && (ft_strcmp(line, eof) != 0))
    {
        write(file_fd, line, ft_strlen(line));
        write(file_fd, "\n", 1);
        free(line);
        line = process_and_reassemble(readline("> "), data);
    }
    free(line);
    free(eof);
    close(file_fd);
    file_fd = open_tmp_file("r");
    execute_child(node->left, data, &file_fd);
    unlink("/tmp/heredoc");
    return (0);
}
References s_ast::args, execute_child(), ft_strcmp(), ft_strdup(), ft_strlen(), s_ast::left, open_tmp_file(), process_and_reassemble(), and s_ast::right.
Referenced by execute_ast().