maxishell: /github/workspace/src/redirection/redirect_append.c File Reference
redirect_append.c File Reference
#include "tokens.h"
#include "shell.h"
#include "redirection.h"
#include "execute.h"
#include "pipe.h"
#include <sys/wait.h>
Functions
static int open_and_redirect (t_ast *node, t_ms_data *data)
int redirect_append (t_ast *node, t_ms_data *data)
Function Documentation
open_and_redirect()
static int open_and_redirect (t_ast * node, t_ms_data * data) static
Definition at line 20 of file redirect_append.c.
{
    int fd;
    if (data->std_out == -1)
    {
        data->std_out = open_file(node->right, ">>");
        if (data->std_out == -1)
            return (EXIT_FAILURE);
    }
    else
    {
        fd = open_file(node->right, ">>");
        if (fd == -1)
            return (EXIT_FAILURE);
        dup2(fd, STDOUT_FILENO);
        close(fd);
    }
    return (EXIT_SUCCESS);
}
References EXIT_FAILURE, EXIT_SUCCESS, open_file(), s_ast::right, and s_ms_data::std_out.
Referenced by redirect_append().
redirect_append()
int redirect_append (t_ast * node, t_ms_data * data)
Definition at line 41 of file redirect_append.c.
{
    pid_t   pid;
    int     exec_status;
    int     status;
    pid = fork();
    if (pid == -1)
        return (EXIT_FAILURE);
    if (pid == 0)
    {
        if (open_and_redirect(node, data) != 0)
            exit(EXIT_FAILURE);
        exec_status = execute_ast(node->left, data);
        exit(exec_status);
    }
    if (waitpid(pid, &status, 0) == -1)
        return (EXIT_FAILURE);
    if (WIFSIGNALED(status))
        return (128 + WTERMSIG(status));
    return (WEXITSTATUS(status));
}
References execute_ast(), EXIT_FAILURE, s_ast::left, and open_and_redirect().
Referenced by execute_ast().