maxishell: /github/workspace/src/shell_variables/shell_variables_utils.c File Reference
shell_variables_utils.c File Reference
#include "shell.h"
#include "env.h"
#include "libft.h"
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
Functions
void set_shell_var (t_env **shell_var, const char *key, const char *value)
void add_shell_var_node (t_env **shell_var, const char *line)
char * get_shell_variable (t_env *shell_var, const char *key)
void free_shell_var_list (t_env *shell_var)
Function Documentation
add_shell_var_node()
void add_shell_var_node (t_env ** shell_var, const char * line)
Definition at line 26 of file shell_variables_utils.c.
{
    char    *key;
    char    *value;
    t_env   *new_node;
    t_env   *curr_node;
    if (!shell_var || !line)
        return ;
    key = ft_strcdup(line, '=');
    value = ft_strchr(line, '=') + 1;
    new_node = (t_env *)malloc(sizeof(t_env));
    new_node->key = ft_strdup(key);
    free(key);
    new_node->value = ft_strdup(value);
    new_node->next = NULL;
    if (*shell_var == NULL)
        *shell_var = new_node;
    else
    {
        curr_node = *shell_var;
        while (curr_node->next != NULL)
            curr_node = curr_node->next;
        curr_node->next = new_node;
    }
}
References ft_strcdup(), ft_strchr(), ft_strdup(), s_env::key, s_env::next, and s_env::value.
Referenced by handle_add_set_shell_variable().
free_shell_var_list()
void free_shell_var_list (t_env * shell_var)
Definition at line 90 of file shell_variables_utils.c.
{
    t_env   *curr_node;
    t_env   *next_node;
    curr_node = shell_var;
    while (curr_node)
    {
        next_node = curr_node->next;
        free(curr_node->key);
        free(curr_node->value);
        free(curr_node);
        curr_node = next_node;
    }
}
References s_env::key, s_env::next, and s_env::value.
Referenced by free_ms_data().
get_shell_variable()
char * get_shell_variable (t_env * shell_var, const char * key)
Definition at line 76 of file shell_variables_utils.c.
{
    t_env   *curr_node;
    curr_node = shell_var;
    while (curr_node)
    {
        if (ft_strcmp(curr_node->key, key) == 0)
            return (curr_node->value);
        curr_node = curr_node->next;
    }
    return (NULL);
}
References ft_strcmp(), s_env::key, s_env::next, and s_env::value.
Referenced by get_exit_status().
set_shell_var()
void set_shell_var (t_env ** shell_var, const char * key, const char * value)
Definition at line 53 of file shell_variables_utils.c.
{
    t_env   *current;
    t_env   *new_env;
    current = *shell_var;
    while (current)
    {
        if (ft_strcmp(current->key, key) == 0)
        {
            free(current->value);
            current->value = ft_strdup(value);
            return ;
        }
        current = current->next;
    }
    new_env = malloc(sizeof(t_env));
    new_env->key = ft_strdup(key);
    new_env->value = ft_strdup(value);
    new_env->next = *shell_var;
    *shell_var = new_env;
}
References ft_strcmp(), ft_strdup(), s_env::key, s_env::next, and s_env::value.
Referenced by builtin_env(), handle_add_set_shell_variable(), handle_exit(), init_ms_data(), set_shell_var_handler(), and shell_variable_update().