maxishell: /github/workspace/src/shell_variables/shell_variables.c File Reference
shell_variables.c File Reference
#include "shell.h"
#include "env.h"
#include "libft.h"
#include "tokens.h"
#include <stddef.h>
Functions
int handle_add_set_shell_variable (t_env **shell_var, char *line)
int handle_get_shell_variable (t_ms_data *data, const char *key)
int handle_shell_variable (t_ast *node, t_ms_data *data)
void shell_variable_update (t_ms_data *data, int status)
Function Documentation
handle_add_set_shell_variable()
int handle_add_set_shell_variable (t_env ** shell_var, char * line)
Definition at line 24 of file shell_variables.c.
{
    char    *key;
    char    *value;
    char    *nq_value;
    key = NULL;
    value = NULL;
    nq_value = NULL;
    if (*shell_var == NULL)
        add_shell_var_node(shell_var, line);
    else
    {
        key = ft_strcdup(line, '=');
        value = ft_strchr(line, '=') + 1;
        nq_value = ft_remove_quotes(value, '\"');
        set_shell_var(shell_var, key, nq_value);
        free(nq_value);
        free(key);
    }
    return (0);
}
References add_shell_var_node(), ft_remove_quotes(), ft_strcdup(), ft_strchr(), and set_shell_var().
Referenced by handle_local_vars(), and init_ms_data().
handle_get_shell_variable()
int handle_get_shell_variable (t_ms_data * data, const char * key)
Definition at line 47 of file shell_variables.c.
{
    char    *value;
    t_env   *shell_var;
    shell_var = data->shell_variables;
    value = get_env(shell_var, key);
    if (value)
    {
        ft_putstr_fd(value, data->std_out);
        ft_putstr_fd("\n", data->std_out);
        free(value);
        return (0);
    }
    return (-1);
}
References ft_putstr_fd(), get_env(), s_ms_data::shell_variables, and s_ms_data::std_out.
Referenced by handle_shell_variable().
handle_shell_variable()
int handle_shell_variable (t_ast * node, t_ms_data * data)
Definition at line 64 of file shell_variables.c.
{
    if (node->left && node->right == NULL)
        return (handle_get_shell_variable(data, node->args[0]));
    return (-1);
}
References s_ast::args, handle_get_shell_variable(), s_ast::left, and s_ast::right.
shell_variable_update()
void shell_variable_update (t_ms_data * data, int status)
Definition at line 71 of file shell_variables.c.
{
    char    *status_str;
    data->exit_status = status;
    status_str = ft_itoa(status);
    set_shell_var(&data->shell_variables, "?", status_str);
    free(status_str);
}
References s_ms_data::exit_status, ft_itoa(), set_shell_var(), and s_ms_data::shell_variables.