maxishell: /github/workspace/src/signals/signals_utils.c File Reference
signals_utils.c File Reference
#include "signals.h"
#include <readline/readline.h>
#include <readline/history.h>
#include <unistd.h>
#include "libft.h"
#include <sys/wait.h>
Functions
t_signal_context * get_context (t_ms_data *data)
void handle_sigint_heredoc (int signo)
int is_external_command_running (void)
Function Documentation
get_context()
t_signal_context * get_context (t_ms_data * data)
Definition at line 21 of file signals_utils.c.
{
    static t_signal_context *context = NULL;
    if (data != NULL)
    {
        if (!context)
        {
            context = malloc(sizeof(t_signal_context));
            if (!context)
                return (NULL);
        }
        context->data_cxt = data;
    }
    return (context);
}
References s_signal_context::data_cxt.
Referenced by free_signal_context().
handle_sigint_heredoc()
void handle_sigint_heredoc (int signo)
Definition at line 38 of file signals_utils.c.
{
    (void)signo;
    g_heredoc_interrupted = 1;
}
References g_heredoc_interrupted.
Referenced by setup_sigint_handler().
is_external_command_running()
int is_external_command_running (void)
Definition at line 44 of file signals_utils.c.
{
    pid_t   child_pid;
    child_pid = waitpid(-1, NULL, WNOHANG);
    if (child_pid == 0)
        return (1);
    else
        return (0);
}
Referenced by signal_reset_prompt().