maxishell: /github/workspace/src/signals/utils.c File Reference
utils.c File Reference
#include <signal.h>
#include <unistd.h>
#include <readline/readline.h>
#include <readline/history.h>
#include "libft.h"
#include "shell.h"
#include "signals.h"
Functions
void signals_handler (int signo, t_minishell_data *data)
void sigint_handler (int signo)
void sigquit_handler (int signo)
Function Documentation
sigint_handler()
void sigint_handler (int signo)
Definition at line 33 of file utils.c.
{
    g_signo = signo;
}
References g_signo.
Referenced by init_signals().
signals_handler()
void signals_handler (int signo, t_minishell_data * data)
Definition at line 13 of file utils.c.
{
    (void)data; // Чтобы избежать предупреждения о неиспользуемой переменной
    if (g_signo)
    {
        if (signo == SIGINT)
        {
            write(STDOUT_FILENO, "\n", 1);
            rl_on_new_line();
            rl_replace_line("", 0);
            rl_redisplay();
        }
        else if (signo == SIGQUIT)
        {
            // Обработка SIGQUIT, если необходимо
        }
    }
}
References g_signo.
Referenced by main_loop().
sigquit_handler()
void sigquit_handler (int signo)
Definition at line 38 of file utils.c.
{
    g_signo = signo;
}
References g_signo.
Referenced by init_signals().