maxishell: /github/workspace/inc/signals.h File Reference
signals.h File Reference
#include <termios.h>
#include <sys/ioctl.h>
#include <signal.h>
#include "shell.h"
Classes
struct s_signal_context
Macros
#define _GNU_SOURCE
Typedefs
typedef struct s_signal_context t_signal_context
Functions
t_signal_context * get_context (t_ms_data *data)
void signal_reset_prompt (int signo, siginfo_t *info, void *ucontext)
void set_signals_interactive (t_ms_data *data)
void signal_print_newline (int signal)
void sigquit_ignore (void)
void set_signals_noninteractive (void)
void handle_sigint_heredoc (int signo)
int ft_perror (char *str)
Variables
volatile sig_atomic_t g_heredoc_interrupted
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 15 of file signals.h.
Typedef Documentation
t_signal_context
typedef struct s_signal_context t_signal_context
Function Documentation
ft_perror()
int ft_perror (char * str)
Definition at line 18 of file exit_status_utils.c.
{
    perror (str);
    exit(EXIT_FAILURE);
}
get_context()
t_signal_context * get_context (t_ms_data * data)
Definition at line 20 of file signals_utils.c.
{
    static t_signal_context *context = NULL;
    if (data != NULL)
    {
        if (!context)
        {
            context = malloc(sizeof(t_signal_context));
            if (!context)
                return (NULL);
        }
        context->data_cxt = data;
    }
    return (context);
}
References s_signal_context::data_cxt.
Referenced by free_signal_context(), set_signals_interactive(), and signal_reset_prompt().
handle_sigint_heredoc()
void handle_sigint_heredoc (int signo)
Definition at line 37 of file signals_utils.c.
{
    (void)signo;
    g_heredoc_interrupted = 1;
}
References g_heredoc_interrupted.
Referenced by setup_sigint_handler().
set_signals_interactive()
void set_signals_interactive (t_ms_data * data)
Definition at line 43 of file signals.c.
{
    t_signal_context    *context;
    struct sigaction    sa;
    context = get_context(data);
    if (!context)
        return ;
    sa.sa_sigaction = signal_reset_prompt;
    sa.sa_flags = SA_RESTART | SA_SIGINFO;
    sigemptyset(&sa.sa_mask);
    sigaction(SIGINT, &sa, NULL);
}
References get_context(), and signal_reset_prompt().
Referenced by main_loop().
set_signals_noninteractive()
void set_signals_noninteractive (void)
Definition at line 79 of file signals.c.
{
    struct sigaction    sa;
    sa.sa_handler = SIG_IGN;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    sigaction(SIGQUIT, &sa, NULL);
}
Referenced by main_loop().
signal_print_newline()
void signal_print_newline (int signal)
Definition at line 26 of file signals.c.
{
    (void)signal;
    write(STDOUT_FILENO, "\n", 1);
    rl_on_new_line();
}
signal_reset_prompt()
void signal_reset_prompt (int signo, siginfo_t * info, void * ucontext)
Definition at line 57 of file signals.c.
{
    t_signal_context    *context;
    (void)signo;
    (void)info;
    (void)ucontext;
    context = get_context(NULL);
    if (!rl_line_buffer || rl_line_buffer[0] == '\0')
    {
        if (context && context->data_cxt)
        {
            ft_printf("\nexit\n");
            handle_exit(context->data_cxt, 0);
        }
    }
    write(1, "\n", 1);
    rl_on_new_line();
    rl_replace_line("", 0);
    rl_redisplay();
}
References s_signal_context::data_cxt, ft_printf(), get_context(), and handle_exit().
Referenced by set_signals_interactive().
sigquit_ignore()
void sigquit_ignore (void)
Definition at line 33 of file signals.c.
{
    struct sigaction    a;
    sigemptyset(&a.sa_mask);
    a.sa_flags = 0;
    a.sa_handler = SIG_IGN;
    sigaction(SIGQUIT, &a, NULL);
}
Variable Documentation
g_heredoc_interrupted
volatile sig_atomic_t g_heredoc_interrupted extern
Definition at line 27 of file redirect_heredoc.c.
Referenced by handle_heredoc_interruption(), handle_sigint_heredoc(), redirect_here_doc(), and write_heredoc_lines().