maxishell: /github/workspace/src/test/main.c File Reference
main.c File Reference
#include "test.h"
#include "shell.h"
#include <stdio.h>
#include <stdlib.h>
Functions
int main (int argc, char **argv, char **envp)
Function Documentation
main()
int main (int argc, char ** argv, char ** envp)
Definition at line 18 of file main.c.
{
    t_ms_data   data;
    if (argc > 1)
    {
        ft_printf("Usage: %s\n", argv[0]);
        exit(EXIT_FAILURE);
    }
    pipe_tests(&data);
    env_tests(&data, envp);
    return (0);
}
References env_tests(), EXIT_FAILURE, ft_printf(), and pipe_tests().