maxishell: /github/workspace/src/test/test.h File Reference
test.h File Reference
#include "shell.h"
Functions
void env_tests (t_ms_data *data, char **envp)
void pipe_tests (t_ms_data *data)
Function Documentation
env_tests()
void env_tests (t_ms_data * data, char ** envp)
Definition at line 25 of file env_test.c.
{
    ft_printf("\nENV TESTS\n");
    test_init_env(data, envp);
    test_get_env(data, envp);
    test_set_env(data, envp);
    test_unset_env(data);
    free_env(data->envp);
}
References s_ms_data::envp, free_env(), ft_printf(), test_get_env(), test_init_env(), test_set_env(), and test_unset_env().
Referenced by main().
pipe_tests()
void pipe_tests (t_ms_data * data)
Definition at line 22 of file pipe_test.c.
{
    ft_printf("\nPIPE TESTS\n");
    builtin_pipe_test(data);
    ft_printf("\033[0m");
    ft_printf("\033[0;32m");
    ft_printf("pipe_test    -> OK\n");
    ft_printf("\033[0m");
}
References builtin_pipe_test(), and ft_printf().
Referenced by main().