maxishell: /github/workspace/src/check_tokenise/tokeniser_helpers.c File Reference
tokeniser_helpers.c File Reference
#include "tokens.h"
Functions
void print_tokens (t_token *tokens, char *name)
void print_ast_args (t_ast *node)
void append_word_if_valid (char *start, char *str, t_token **tokens)
Function Documentation
append_word_if_valid()
void append_word_if_valid (char * start, char * str, t_token ** tokens)
Definition at line 49 of file tokeniser_helpers.c.
{
    char    *word;
    if (str > start)
    {
        word = ft_strndup(start, str - start);
        if (word)
        {
            append_token(tokens, new_token(word, PHRASE));
            free(word);
        }
        else
            ft_printf("Error: unable to allocate memory for token\n");
    }
}
References append_token(), ft_printf(), ft_strndup(), new_token(), and PHRASE.
Referenced by handle_phrase().
print_ast_args()
void print_ast_args (t_ast * node)
Definition at line 37 of file tokeniser_helpers.c.
{
    int     i;
    i = 0;
    while (node->args[i] != NULL)
    {
        ft_printf("ast arg[%d] ->  %s \n", i, node->args[i]);
        i++;
    }
}
References s_ast::args, and ft_printf().
print_tokens()
void print_tokens (t_token * tokens, char * name)
Definition at line 19 of file tokeniser_helpers.c.
{
    t_token *token;
    int     i;
    i = 0;
    token = tokens;
    if (ft_strlen(name) > 0)
        ft_printf(GRN"-----         %s[]        -----\n"RESET, name);
    while (token != NULL)
    {
        ft_printf(GRN"input[%d] ->      %s      at add:         %p\n"RESET, \
            i, token->data, &token->data);
        token = token->next;
        i++;
    }
}
References s_token::data, ft_printf(), ft_strlen(), GRN, s_token::next, and RESET.