maxishell: /github/workspace/src/check_tokenise/tokeniser.c File Reference
tokeniser.c File Reference
#include "tokens.h"
#include <string.h>
Functions
t_token * tokenise (char *str)
char * handle_special_chars (char *str, t_token **tokens)
t_token * new_token (char *value, t_token_type type)
void append_token (t_token **tokens, t_token *new_token)
char * handle_phrase (char *str, t_token **tokens)
Function Documentation
append_token()
void append_token (t_token ** tokens, t_token * new_token)
Definition at line 85 of file tokeniser.c.
{
    t_token *curr;
    if (!*tokens)
        *tokens = new_token;
    else
    {
        curr = *tokens;
        while (curr->next)
            curr = curr->next;
        curr->next = new_token;
    }
}
References new_token(), and s_token::next.
Referenced by append_word_if_valid(), and handle_special_chars().
handle_phrase()
char * handle_phrase (char * str, t_token ** tokens)
Definition at line 100 of file tokeniser.c.
{
    char    *start;
    char    quote_flag;
    char    quote_type;
    start = str;
    quote_flag = 0;
    quote_type = 0;
    while (*str)
    {
        if (!quote_flag && (*str == '\'' || *str == '\"'))
        {
            quote_flag = 1;
            quote_type = *str;
        }
        else if (quote_flag && *str == quote_type)
            quote_flag = 0;
        if (!quote_flag && ft_strchr(" \t\n\r\v\f<|>", *str) != NULL)
            break ;
        str++;
    }
    append_word_if_valid(start, str, tokens);
    return (str);
}
References append_word_if_valid(), and ft_strchr().
Referenced by tokenise().
handle_special_chars()
char * handle_special_chars (char * str, t_token ** tokens)
Definition at line 39 of file tokeniser.c.
{
    if (*str == '<')
    {
        if (*(str + 1) == '<')
        {
            append_token(tokens, new_token("<<", REDIR_HEREDOC));
            (str)++;
        }
        else
            append_token(tokens, new_token("<", REDIR_IN));
    }
    else if (*str == '>')
    {
        if (*(str + 1) == '>')
        {
            append_token(tokens, new_token(">>", REDIR_APPEND));
            (str)++;
        }
        else
            append_token(tokens, new_token(">", REDIR_OUT));
    }
    else if (*str == '|')
        append_token(tokens, new_token("|", PIPE));
    (str)++;
    return (str);
}
References append_token(), new_token(), PIPE, REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, and REDIR_OUT.
Referenced by tokenise().
new_token()
t_token * new_token (char * value, t_token_type type)
Definition at line 67 of file tokeniser.c.
{
    t_token *token;
    token = malloc(sizeof(t_token));
    if (!token)
        return (NULL);
    token->data = ft_strdup(value);
    if (!token->data)
    {
        free(token);
        return (NULL);
    }
    token->type = type;
    token->next = NULL;
    return (token);
}
References s_token::data, ft_strdup(), s_token::next, and s_token::type.
Referenced by append_token(), append_word_if_valid(), finalize_token(), handle_special_chars(), and process_single_token().
tokenise()
t_token * tokenise (char * str)
Definition at line 22 of file tokeniser.c.
{
    t_token *tokens;
    tokens = NULL;
    while (*str)
    {
        while (*str && ft_strchr(" \t\n\r\v\f", *str) != NULL)
            str++;
        if (ft_strchr("<|>", *str) != NULL)
            str = handle_special_chars(str, &tokens);
        else
            str = handle_phrase(str, &tokens);
    }
    return (tokens);
}
References ft_strchr(), handle_phrase(), and handle_special_chars().
Referenced by main_loop().