maxishell: /github/workspace/src/builtins/unset.c File Reference
unset.c File Reference
#include "shell.h"
#include "env.h"
#include "libft.h"
#include <unistd.h>
Functions
int builtin_unset (t_ms_data *data)
Function Documentation
builtin_unset()
int builtin_unset (t_ms_data * data)
Definition at line 26 of file unset.c.
{
    int     i;
    int     exit_status;
    char    *key;
    i = 0;
    exit_status = 0;
    while (data->args[++i])
    {
        key =  data->args[i];
        if (unset_env(&data->envp, key) == -1)
        {
            ft_putstr_fd("bash: unset: `", STDERR_FILENO);
            ft_putstr_fd(key, STDERR_FILENO);
            ft_putendl_fd("': not a valid identifier", STDERR_FILENO);
            exit_status = 1;
        }
    }
    data->exit_status = exit_status;
    return (exit_status);
}
References s_ms_data::args, s_ms_data::envp, s_ms_data::exit_status, ft_putendl_fd(), ft_putstr_fd(), and unset_env().
Referenced by execute().