maxishell: /github/workspace/src/execute/utils_1.c File Reference
utils_1.c File Reference
#include "libft.h"
#include "env.h"
#include "execute.h"
Functions
char * ft_find_path (char *cmd, t_env *envp)
function find the full path of the executed command
static void relative_path_handle (char *cmd, char *path, char **tmp_full_path)
Function Documentation
ft_find_path()
char * ft_find_path (char * cmd, t_env * envp)
function find the full path of the executed command
--
Parameters
cmd string from the first argument
Parameters
envp structure with environment variables
Returns
char* returns the full path of the command TODO: rewrite ft_find_path for working full path when $PATH deleted
Definition at line 32 of file utils_1.c.
{
    char    **path;
    char    *tmp_full_path;
    int     i;
    path = ft_split(get_env(envp, "PATH"), ':');
    i = -1;
    while (path[++i] != NULL)
    {
        if (ft_strncmp(cmd, "/", 1) != 0)
            relative_path_handle(cmd, path[i], &tmp_full_path);
        else
            tmp_full_path = ft_strdup(cmd);
        if (access(tmp_full_path, F_OK) == 0)
        {
            ft_free_2d_arr(path);
            return (tmp_full_path);
        }
        free(tmp_full_path);
    }
    ft_free_2d_arr(path);
    return (NULL);
}
References ft_free_2d_arr(), ft_split(), ft_strdup(), ft_strncmp(), get_env(), and relative_path_handle().
Referenced by child_process().
relative_path_handle()
static void relative_path_handle (char * cmd, char * path, char ** tmp_full_path) static
Definition at line 57 of file utils_1.c.
{
    char    *tmp_slash;
    tmp_slash = ft_strjoin(path, "/");
    *tmp_full_path = ft_strjoin(tmp_slash, cmd);
    free(tmp_slash);
}
References ft_strjoin().
Referenced by ft_find_path().