maxishell: /github/workspace/src/env/utils_utils.c File Reference
utils_utils.c File Reference
#include "env.h"
#include "libft.h"
#include <stdlib.h>
#include <stdio.h>
Functions
char * ft_remove_all_edge_quotes (char *str, char quote_type)
static char * remove_quotes (const char *value)
void add_new_env (t_env **env, const char *key, char *modified_value)
void set_env (t_env **env, const char *key, const char *value)
Function Documentation
add_new_env()
void add_new_env (t_env ** env, const char * key, char * modified_value)
Definition at line 31 of file utils_utils.c.
{
    t_env   *new_env;
    new_env = malloc(sizeof(t_env));
    if (!new_env)
        return ;
    new_env->key = ft_strdup(key);
    new_env->value = modified_value;
    new_env->next = *env;
    *env = new_env;
}
References ft_strdup(), s_env::key, s_env::next, and s_env::value.
Referenced by set_env().
ft_remove_all_edge_quotes()
char * ft_remove_all_edge_quotes (char * str, char quote_type)
Definition at line 24 of file env.c.
{
    int     start_quotes;
    int     end_quotes;
    int     len;
    char    *new_str;
    len = ft_strlen(str);
    start_quotes = 0;
    while (str[start_quotes] == quote_type)
        start_quotes++;
    end_quotes = 0;
    while (len - end_quotes - 1 >= 0 && str[len - end_quotes - 1] == quote_type)
        end_quotes++;
    if (start_quotes > 0 && start_quotes == end_quotes)
    {
        new_str = ft_strndup(str + start_quotes, len - 2 * start_quotes);
        return (new_str);
    }
    return (ft_strdup(str));
}
References ft_strdup(), ft_strlen(), and ft_strndup().
Referenced by remove_quotes().
remove_quotes()
static char * remove_quotes (const char * value) static
Definition at line 20 of file utils_utils.c.
{
    char    *temp;
    char    *result;
    temp = ft_remove_all_edge_quotes((char *)value, '\"');
    result = ft_remove_all_edge_quotes(temp, '\'');
    free(temp);
    return (result);
}
References ft_remove_all_edge_quotes().
Referenced by set_env().
set_env()
void set_env (t_env ** env, const char * key, const char * value)
Definition at line 44 of file utils_utils.c.
{
    t_env   *current;
    char    *modified_value;
    current = *env;
    modified_value = NULL;
    if (value[0] != '\0')
        modified_value = remove_quotes(value);
    else
        modified_value = ft_strdup(value);
    while (current)
    {
        if (ft_strcmp(current->key, key) == 0)
        {
            free(current->value);
            current->value = modified_value;
            return ;
        }
        current = current->next;
    }
    add_new_env(env, key, modified_value);
}
References add_new_env(), ft_strcmp(), ft_strdup(), s_env::key, s_env::next, remove_quotes(), and s_env::value.
Referenced by add_env(), builtin_cd(), test_set_env(), and test_unset_env().