maxishell: /github/workspace/src/execute/utils_0.c File Reference
utils_0.c File Reference
#include "libft.h"
#include "env.h"
#include <stdio.h>
#include "shell.h"
Functions
char * ft_find_path (char *cmd, t_env *envp)
function find the full path of the executed command
void ft_free_2d_arr (char **arr)
clean up 2d array
int ft_perror (char *str)
return error message and exit
void close_fds (int in, int out)
close two file descriptors
void handle_temp_fd (t_minishell_data *data)
void handle_io_fd (t_minishell_data *data)
close temporary input/output file descriptors and reset them to -1
Function Documentation
close_fds()
void close_fds (int in, int out)
close two file descriptors
--
Parameters
fds file descriptors
Definition at line 98 of file utils_0.c.
{
    close(in);
    close(out);
}
Referenced by builtin_pipe(), execute_child(), and new_process().
ft_find_path()
char * ft_find_path (char * cmd, t_env * envp)
function find the full path of the executed command
--
Parameters
cmd string from the first argument
Parameters
envp structure with environment variables
Returns
char* returns the full path of the command
Definition at line 32 of file utils_0.c.
{
    char    **path;
    char    *tmp_slash;
    char    *tmp_full_path;
    int     i;
    path = ft_split(get_env(envp, "PATH"), ':');
    i = -1;
    while (path[++i] != NULL)
    {
        if (ft_strncmp(cmd, "/", 1) != 0)
        {
            tmp_slash = ft_strjoin(path[i], "/");
            tmp_full_path = ft_strjoin(tmp_slash, cmd);
            free(tmp_slash);
        }
        else
            tmp_full_path = ft_strdup(cmd);
        if (access(tmp_full_path, F_OK) == 0)
        {
            ft_free_2d_arr(path);
            return (tmp_full_path);
        }
        free(tmp_full_path);
    }
    ft_free_2d_arr(path);
    return (NULL);
}
References ft_free_2d_arr(), ft_split(), ft_strdup(), ft_strjoin(), ft_strncmp(), and get_env().
Referenced by new_process().
ft_free_2d_arr()
void ft_free_2d_arr (char ** arr)
clean up 2d array
--
Parameters
arr simple two dimensional array
Definition at line 68 of file utils_0.c.
{
    int i;
    i = -1;
    while (arr[++i] != NULL)
        free(arr[i]);
    free(arr);
}
Referenced by ft_find_path().
ft_perror()
int ft_perror (char * str)
return error message and exit
--
Parameters
str paste the error message
Returns
int return status:
- 1: EXIT_FAILURE
Definition at line 86 of file utils_0.c.
{
    perror (str);
    exit(EXIT_FAILURE);
}
Referenced by builtin_pipe(), execute(), execute_child(), execute_child(), new_process(), and open_tmp_file().
handle_io_fd()
void handle_io_fd (t_minishell_data * data)
close temporary input/output file descriptors and reset them to -1
--
Parameters
data minishell structure
Definition at line 109 of file utils_0.c.
{
    if (data->std_in != -1 && data->std_out != -1)
    {
        close(data->std_in);
        close(data->std_out);
        data->std_in = -1;
        data->std_out = -1;
    }
}
References s_minishell_data::std_in, and s_minishell_data::std_out.
Referenced by main_loop().
handle_temp_fd()
void handle_temp_fd (t_minishell_data * data)