maxishell: /github/workspace/src/utils/visualiser.c File Reference
visualiser.c File Reference
#include "tokens.h"
Functions
const char * get_token_type_name (t_token_type type)
void print_ast_node (t_ast *node, int depth, char *prefix, int is_left)
void build_new_prefix (char *new_prefix, char *prefix, int is_left)
void print_ast_graphical (t_ast *node, int depth, char *prefix, int is_left)
void print_ast_root (t_ast *root)
Function Documentation
build_new_prefix()
void build_new_prefix (char * new_prefix, char * prefix, int is_left)
Definition at line 63 of file visualiser.c.
{
    int i;
    int j;
    i = 0;
    j = 0;
    while (prefix[i])
    {
        new_prefix[j] = prefix[i];
        i++;
        j++;
    }
    if (is_left)
    {
        new_prefix[j++] = '|';
        new_prefix[j++] = ' ';
        new_prefix[j++] = ' ';
    }
    else
    {
        new_prefix[j++] = ' ';
        new_prefix[j++] = ' ';
        new_prefix[j++] = ' ';
    }
    new_prefix[j] = '\0';
}
Referenced by print_ast_graphical().
get_token_type_name()
const char * get_token_type_name (t_token_type type)
Definition at line 15 of file visualiser.c.
{
    if (type == PHRASE)
        return ("PHRASE");
    else if (type == PIPE)
        return ("PIPE");
    else if (type == ENV_VAR)
        return ("ENV_VAR");
    else if (type == REDIR_IN)
        return ("REDIR_IN");
    else if (type == REDIR_OUT)
        return ("REDIR_OUT");
    else if (type == REDIR_APPEND)
        return ("REDIR_APPEND");
    else if (type == REDIR_HEREDOC)
        return ("REDIR_HEREDOC");
    else
        return ("UNKNOWN");
}
References ENV_VAR, PHRASE, PIPE, REDIR_APPEND, REDIR_HEREDOC, REDIR_IN, and REDIR_OUT.
Referenced by print_ast_node().
print_ast_graphical()
void print_ast_graphical (t_ast * node, int depth, char * prefix, int is_left)
Definition at line 91 of file visualiser.c.
{
    char    new_prefix[256];
    print_ast_node(node, depth, prefix, is_left);
    build_new_prefix(new_prefix, prefix, is_left);
    if (node->left)
        print_ast_graphical(node->left, depth + 1, new_prefix, 1);
    if (node->right)
        print_ast_graphical(node->right, depth + 1, new_prefix, 0);
}
References build_new_prefix(), s_ast::left, print_ast_graphical(), print_ast_node(), and s_ast::right.
Referenced by print_ast_graphical(), and print_ast_root().
print_ast_node()
void print_ast_node (t_ast * node, int depth, char * prefix, int is_left)
Definition at line 35 of file visualiser.c.
{
    int i;
    if (!node)
        return ;
    ft_printf("%s", prefix);
    if (depth == 0)
        ft_printf("Root-> ");
    else
    {
        if (is_left)
            ft_printf("L-> ");
        else
            ft_printf("R-> ");
    }
    ft_printf("Type: %s\n", get_token_type_name(node->type));
    if (node->args)
    {
        i = 0;
        while (node->args[i])
        {
            ft_printf("%s     Arg: %s\n", prefix, node->args[i]);
            i++;
        }
    }
}
References s_ast::args, ft_printf(), get_token_type_name(), and s_ast::type.
Referenced by print_ast_graphical().
print_ast_root()
void print_ast_root (t_ast * root)
Definition at line 103 of file visualiser.c.
{
    if (!root)
        return ;
    print_ast_graphical(root, 0, "", 0);
}
References print_ast_graphical().