name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Build project
      run: make
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: minishell
        path: ./project
