name: Valgrind Check

on:
  workflow_run:
    workflows: ["Build Project"]
    types:
      - completed

jobs:
  valgrind:
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: minishell
    - name: Unzip artifact
      run: unzip ./project/minishell.zip -d ./minishell
    - name: Install Valgrind
      run: sudo apt-get update && sudo apt-get install -y valgrind
    - name: Run Valgrind
      run: valgrind --leak-check=full --show-leak-kinds=all ./minishell/minishell
